### ISSUE TITLE
subtitle cycle back

### ISSUE THREAD

**Issue by amnek0** [stax76/mpv.net#10]
hi,

is it possible to cycle back the subtitles?

now i can only switch to next one with kp8.

**Comment by stax76** [comment]
Hi,

yes, I believe it's possible, you have to edit your input.conf

https://mpv.io/manual/master/#command-interface-cycle-%3Cproperty%3E-[up|down]

for a more detailed help on this kind of customization please post to the support forum:

https://github.com/stax76/mpv.net#support

I will do my best to help you in the forum with this.

Greetings

**Comment by amnek0** [comment]
thank you.

tried to add a new line, it's working now.

cycle sub = cycle sub up(by default).

![subd](https://user-images.githubusercontent.com/12832589/55279564-b88b3580-5354-11e9-88da-001f2bd1addd.png)

**Comment by stax76** [comment]
Nice, maybe I can add some features to the editor without taking away from its simplicity, I've some ideas.
