### ISSUE TITLE
mpv-youtube-quality script does not work at all

### ISSUE THREAD

**Issue by Naomi010Sentzke** [stax76/mpv.net#102]
https://github.com/jgreco/mpv-youtube-quality
![Untitled3](https://user-images.githubusercontent.com/53768184/66236376-f73ce680-e70f-11e9-9a97-88e4e7940d8c.png)
f is the key binding I set for this script

**Comment by Naomi010Sentzke** [comment]
After some tinkering, it does not show any error messages, but it still says "No key binding found for key 'f'." and ofcourse it does not work
![image](https://user-images.githubusercontent.com/53768184/66260134-0b4c1b00-e7d8-11e9-85f5-9b63053ab045.png)

**Comment by Naomi010Sentzke** [comment]
Seems like I have to remove the key-binding from script-opts and add `f script-binding quality-menu` to input.conf.

**Comment by Restia666Ashdoll** [comment]
Was playing around with this script and I noticed that if I let the script fetch formats, it takes some time to fetch them and it does not even work properly with Crunchyroll. So, I set `fetch_formats=no`  in youtube-quality.conf. And these are the format specifiers I set.
`quality_strings=[ {"Best" : "bestvideo[height>2160]+bestaudio[acodec=opus]/(bestvideo[height=2160][fps>30]+251)/bestvideo[height=2160]+251/bestvideo[height=2160]+140/(bestvideo[height=1440][fps>30]+251)/bestvideo[height=1440]+251/bestvideo[height=1440]+140/(bestvideo[height=1080][fps>30]+251)/bestvideo[height=1080]+251/bestvideo[height=1080]+140/(bestvideo[height=720][fps>30]+251)/bestvideo+251/bestvideo+bestaudio/best"}, {"4K (High Framerate)" : "(bestvideo[height=2160][fps>30]+251)/bestvideo[height=2160]+251/bestvideo[height=2160]+140/(bestvideo[height=1440][fps>30]+251)/bestvideo[height=1440]+251/bestvideo[height=1440]+140/(bestvideo[height=1080][fps>30]+251)/bestvideo[height=1080]+251/bestvideo[height=1080]+140/(bestvideo[height=720][fps>30]+251)/bestvideo[height<=?2160]+251/bestvideo[height<=?2160]+bestaudio/best[height<=?2160]"}, {"4K" : "(bestvideo[height=2160][fps<=30]+251)/(bestvideo[height=2160][fps<=30]+140)/bestvideo[height=1440]+251/bestvideo[height=1440]+140/bestvideo[height=1080]+251/bestvideo[height=1080]+140/(bestvideo[height<=?2160][fps<=30]+251)/(bestvideo[height<=?2160[fps<=30]]+bestaudio)/(best[height<=?2160][fps<=30])"}, {"2K (High Framerate)" : "(bestvideo[height=1440][fps>30]+251)/bestvideo[height=1440]+251/bestvideo[height=1440]+140/(bestvideo[height=1080][fps>30]+251)/bestvideo[height=1080]+251/bestvideo[height=1080]+140/(bestvideo[height=720][fps>30]+251)/bestvideo[height<=?1440]+251/bestvideo[height<=?1440]+bestaudio/best[height<=?1440]"}, {"2K" : "(bestvideo[height=1440][fps<=30]+251)/(bestvideo[height=1440][fps<=30]+140)/bestvideo[height=1080]+251/bestvideo[height=1080]+140/(bestvideo[height<=?1440][fps<=30]+251)/(bestvideo[height<=?1440][fps<=30]+bestaudio)/(best[height<=?1440][fps<=30])"}, {"1080p (High Framerate)" : "(bestvideo[height=1080][fps>30]+251)/bestvideo[height=1080]+251/bestvideo[height=1080]+140/(bestvideo[height=720][fps>30]+251)/bestvideo[height<=?1080]+251/bestvideo[height<=?1080]+bestaudio/best[height<=?1080]"}, {"1080p" : "(bestvideo[height=1080][fps<=30]+251)/(bestvideo[height=1080][fps<=30]+140)/(bestvideo[height<=?1080][fps<=30]+251)/(bestvideo[height<=?1080][fps<=30]+bestaudio)/(best[height<=?1080][fps<=30])"}, {"720p (High Framerate)" : "(bestvideo[height=720][fps>30]+251)/bestvideo[height<=?720]+251/bestvideo[height<=?720]+bestaudio/best[height<=?720]"}, {"720p" : "(bestvideo[height<=?720][fps<=30]+251)/(bestvideo[height<=?720][fps<=30]+bestaudio)/(best[height<=?720][fps<=30])"}, {"480p" : "bestvideo[height<=?480]+251/bestvideo[height<=?480]+bestaudio/best[height<=?480]"}, {"360p" : "bestvideo[height<=?360]+251/bestvideo[height<=?360]+bestaudio/best[height<=?360]"}, {"240p" : "bestvideo[height<=?240]+251/bestvideo[height<=?240]+bestaudio/best[height<=?240]"}, {"Audio Only" : "bestaudio[acodec=opus]/bestaudio"}, {"Worst" : "worstvideo+worstaudio/worst"} ]
`
Also, for formatting the labels
```
selected_and_active={\\c&HH00FF00&}▶ - 
selected_and_inactive={\\c&H33FFFF&}● - 
unselected_and_active={\\c&HAAAAAA&}▷ - 
unselected_and_inactive={\\c&HFFFFFF&}○ - 
```
