### ISSUE TITLE
I can not use the control programmatically

### ISSUE THREAD

**Issue by JassyPinkman** [stax76/mpv.net#104]
I delved into the code trying to find the ability to use play, pause, rewind from the code, but it doesn’t work. I'm new in .Net, tell me how to do this?

**Comment by stax76** [comment]
There is a mpv property called pause

https://mpv.io/manual/master/#options-pause

there are two ways to change it:

mp.set_property("pause", "no");

or:

mp.command("set pause no")

https://mpv.io/manual/master/#command-interface-set-%3Cname%3E-%3Cvalue%3E

**Comment by Restia666Ashdoll** [comment]
Add input.conf bindings for `cycle pause` for play pause.
`no osd seek` is for rewind forward/backwards. So, `no osd seek 7` will forward seek 7 seconds, `no osd seek -7` will go 7 seconds backward. `no-osd seek 00 absolute-percent` will go to the beginning of video.
