### ISSUE TITLE
'Open with mpv.net' through External Application Button

### ISSUE THREAD

**Issue by Restia666Ashdoll** [stax76/mpv.net#106]
I tested this on Edge Insider and I presume this should work with Chrome too.
1. Install External Application Button
https://chrome.google.com/webstore/detail/external-application-butt/bifmfjgpgndemajpeeoiopbeilbaifdo
2. Install native-client
https://github.com/andy-portmen/native-client/releases
Extract windows.zip anywhere and run install.bat
3. In extension options, allow access to file urls for External Application Button
4. Make sure mpv.net path is added as an Environment variable through OS setup.
5. Go to External Application Button options and add the following json file through import settings
[external-application-button-preferences.zip](https://github.com/stax76/mpv.net/files/3734489/external-application-button-preferences.zip)
This should work fine. I am still unable to make it display mpv.net icon in context menu(it displays just fine in toolbar) and there is a bit of delay compared to directly pasting the URL.

**Comment by stax76** [comment]
Is this for YouTube? How does it compare to:

https://github.com/stax76/mpv.net/blob/master/Manual.md#chrome-extension

This automatically pauses YouTube in the browser. I think it's perfect except that it uses the mpv icon instead of the mpv.net icon.

**Comment by Restia666Ashdoll** [comment]
It works on everything that is supported by youtube-dl. Youtube now pauses automatically if you scroll down. This is more customisable. I am still trying to figure out the delay and instead load as fast as pasting url directly. They natively support VLC(lol) though.
Never tried the extension in manual, since I always wanted a nice "Open with mpv.net" in my browser.

**Comment by Restia666Ashdoll** [comment]
Alright, this is better
[external-application-button-preferences.zip](https://github.com/stax76/mpv.net/files/3735164/external-application-button-preferences.zip)
Less delay. No reason to use mpv extension now.

**Comment by stax76** [comment]
I take a look at it if I have time.

**Comment by Restia666Ashdoll** [comment]
Now, I know how to change the icon in context menu. I tested this on Edge Insider, but there should be a path for Chrome too.
1. Go to "%USERPROFILE%\AppData\Local\Microsoft\Edge\User Data\Default\Extensions\bifmfjgpgndemajpeeoiopbeilbaifdo\0.3.4_0\data\icons"
2. Replace '32.png' with this
![32](https://user-images.githubusercontent.com/56309157/66984140-caa5a900-f0d7-11e9-8d51-3af6b5d9ad80.png)

**Comment by stax76** [comment]
I've still not tried it but have updated the manual now:

<https://github.com/stax76/mpv.net/blob/master/Manual.md#chrome-extensions>
