### ISSUE TITLE
Playlist shuffle feature

### ISSUE THREAD

**Issue by vmackey** [stax76/mpv.net#107]
Hello Frank, 

I am the person who asked for the 'playlist shuffle' feature on mpv.net by email. I think you added it in your last version according to the log, thank you very much.
However I cannot find it in the menu. I also searched for 'shuffle' in the keyboard shortcuts but I didn't find it there either. Can you tell me how to set it on?

Thank you.

**Comment by stax76** [comment]
Hello vmackey,

in the menu go to:

Settings > Open Config Folder

delete input.conf

If you customize input.conf which stores input bindings and the menu and don't want to delete it then just update it manually:

https://github.com/stax76/mpv.net/blob/master/mpv.net/Resources/inputConf.txt#L156

This will be hard in the beginning, it's part of the mpv experience, we all had to go through this, once you understand it, you will be amazed about how great the mpv player is compared to other players, trust me, in the end it will be great fun, use Visual Studio Code for text editing, another awesome piece of software.

**Comment by Restia666Ashdoll** [comment]
Why do you need VS Code to edit conf files? You can use Notepad or Notepad++. I use Notepads
https://www.microsoft.com/en-us/p/notepads-beta/9nhl4nsc67wm?activetab=pivot:overviewtab
It is tabbed, uses fluent design system and has lots of additional stuffs that Notepad lack.
Visual Studio Code is a source code editor, using it as a text editor is a bit overkill.

**Comment by stax76** [comment]
Notepad++ is one of the worst editors compared to leaders like VS code and Sublime Text, it takes some experience to understand why there is no alternative to VS code, text editing involves very often multi caret editing, especially when you write code or markup.

https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor

I'm sure I edit input.conf with multi caret regularly. Sublime Text has invented true multi caret editing and VS code supports it equally well and all other modern and popular editing techniques. VS code has the best language integration for all kind of languages, gives you both code completion and debugger for powershell which I write quite often lately and other languages and file types have first class support as well. For md I discovered Caret today.

**Comment by Restia666Ashdoll** [comment]
yeah but you are just editing conf files you dont need VS Code for editing input.conf. If you really want something better than Notepad, you can just use Notepads.
