### ISSUE TITLE
Beta Version introduces a new window size bug when minimizing and restoring

### ISSUE THREAD

**Issue by Restia666Ashdoll** [stax76/mpv.net#109]
In the beta version if I minimize and then restore, it will restore to the default window size. So, if your window is maximized or resized to a custom size, it will reset when minimizing and restoring.

**Comment by stax76** [comment]
It's difficult and I don't get what's the point in starting maximized, I hope I can fix it today.

**Comment by Restia666Ashdoll** [comment]
Thanks.

**Comment by stax76** [comment]
This time it's much likely properly fixed, I hope I can get a new build out shortly. Thanks for the feedback.
