### ISSUE TITLE
How to play a given file after startup

### ISSUE THREAD

**Issue by Seigarovaa** [stax76/mpv.net#11]
Please tell me how to start playing a particular *.mp4 file after compilation in Visual Studio? Where and how to specify the file (mp4) with playback options I need to play an encrypted file with the key --demuxer-lavf-o=decryption_key...my_key.. to have the player start playing my file right away ?  If you call mpvnet.exe from the command line with parameters, everything works fine and decrypts, but it is necessary from the program code to call playback.

**Comment by Seigarovaa** [comment]
Is that impossible ?

**Comment by stax76** [comment]
I thought it's solved because I answered here:

https://forum.videohelp.com/threads/392514-mpv-net-a-extendable-media-player-for-windows#post2547385

**Comment by Seigarovaa** [comment]
Thank you very much for your reply. This works, but after compilation these parameters are not saved in the finished project. Is it possible to pass these parameters in the code ?

**Comment by stax76** [comment]
Sorry but I don't give a programming course for beginners here. There aren't many possible entry points and ways to access command line arguments in dotnet, you can easily google it. C# is compared to let's say C++ relative easy to use and learn but if you don't have programmed before consider to start with Python or Visual Basic.NET.
