### ISSUE TITLE
update notifier

### ISSUE THREAD

**Issue by 0ANIMEFREAK0** [stax76/mpv.net#110]
can u implement some sort of update notifier to the app that'll notify when a update is available and after clicking on update button it'll  redirect u too github release page

**Comment by stax76** [comment]
I've done this for staxrip and it's relative simple, it downloads the release page once per day.

https://github.com/staxrip/staxrip/blob/master/General/Http.vb

mpv.net has more users which use it often daily, it would result in many web requests, I could make the check weekly I guess.

**Comment by ice44** [comment]
@stax76 Could you add an update.bat file as the original MPV has? I used that with the windows task scheduler to schedule the batch file to launch at the given time that worked best for my needs. It worked perfectly for me. Sounds like the best solution.

**Comment by Restia666Ashdoll** [comment]
@ice44 I created something similar here
https://github.com/stax76/mpv.net/issues/111

**Comment by ice44** [comment]
@Restia666Ashdoll Awesome. I'll take a look!

**Comment by stax76** [comment]
There is now a built-in update feature.
