### ISSUE TITLE
Using Powershell to update mpv.net

### ISSUE THREAD

**Issue by Restia666Ashdoll** [stax76/mpv.net#111]
I made this Powershell script to update to the latest mpv.net version and a bat script that runs the Powershell script within it. It will check for latest version and only update if you have an older version or if you dont have mpv.net at all.
[update(64-bit).zip](https://github.com/stax76/mpv.net/files/3827379/update.64-bit.zip)
[update(32-bit).zip](https://github.com/stax76/mpv.net/files/3827384/update.32-bit.zip)
Update : mpv.net now has a native update feature, so this is useless
https://github.com/stax76/mpv.net/blob/master/mpv.net/Misc/UpdateCheck.cs

**Comment by stax76** [comment]
Thanks for sharing, I'll examine it when I have time.

**Comment by Restia666Ashdoll** [comment]
Thanks, but please ensure that in future version tags in releases and version name in filename are either same or have a co-relation like the ffbinaries link I provided. Otherwise, this script wont work.

**Comment by Restia666Ashdoll** [comment]
So, now in the latest release, version tag and version in filename are same. So. this is the new update script
[update(64-bit).zip](https://github.com/stax76/mpv.net/files/3800189/update.64-bit.zip)
[update(32-bit).zip](https://github.com/stax76/mpv.net/files/3800190/update.32-bit.zip)

**Comment by Restia666Ashdoll** [comment]
I updated it so it should work now.

**Comment by Restia666Ashdoll** [comment]
Also, mpv.net can be installed and updated by Scoop if anyone is interested
```
scoop bucket add extras
scoop install mpv.net
```
