### ISSUE TITLE
Can't make mpv.net my default program after a recent Windows 10 update

### ISSUE THREAD

**Issue by ghost** [stax76/mpv.net#116]
Hi,

I have a little issue, since I accidentally updated my version of Windows 10 Pro to 18362.418, it became impossible to make mpv.net my default program for video, music, photo, anything or to integrate the program into the context menus. I tried to reset everything but it only was a reset of the same updated version. Turns out, my only way to go back would be to buy another key, I gave up when I realized that.
Would it be possible to fix that issue in the future? 

Best regards.

**Comment by stax76** [comment]
I don't think there is something I can do.

https://github.com/stax76/mpv.net/blob/master/Manual.md#file-associations

**Comment by Restia666Ashdoll** [comment]
Try starting mpv.net with admin privileges.

**Comment by 44vince44** [comment]
Ghost I updated to the latest version of Windows 10, which is 18363.476 (Home) and mpv.net is still set as my default video player.
