### ISSUE TITLE
Use syncplay with MPV.net

### ISSUE THREAD

**Issue by RaXorX** [stax76/mpv.net#120]
I use syncplay with MPV player but recently saw this project and was curious if I could use it with syncplay too.

**Comment by Restia666Ashdoll** [comment]
https://github.com/Syncplay/syncplay/issues/246

**Comment by RaXorX** [comment]
Ay, I commented on that thread instead. Although, just saw that the it works even if it throws the error. 
I had to close the error and then the first mvpnet window, after which it opened another window and then connected to Syncplay.

**Comment by stax76** [comment]
If I remember right then the syncplay developer removed passing --version so your problem is likely an outdated syncplay version.
