### ISSUE TITLE
Streamlink output files shows a blank white screen

### ISSUE THREAD

**Issue by RaXorX** [stax76/mpv.net#121]
Videos download through streamlink aren't playing in MPV. While those same files are playing fine in windows media player apparently. Any ideas what is happening here? It happens with MPV/MPVnet both. I can't play them in VLC either for that matter of fact.

Edit: I tried to run mpvnet console, just to see the errors it throws.
Two main errors I found were about the probesize and invalid PNG signature.

[ffmpeg/demuxer] png_pipe: Stream #0: not enough frames to estimate rate; consider increasing probesize
[ffmpeg/video] png: Invalid PNG signature

I found something for the probesize demuxer-lavf-probesize which should increase it's size, but unfortunately I have been unable to get that error to not persist. I keep seeing that, after which the console gets spammed with the invalid PNG sig error repeatedly and the player shows me a white screen as an output.

**Comment by stax76** [comment]
You can try to contact mpv support.

https://mpv.io/
