### ISSUE TITLE
mpv.net not importing tkinter

### ISSUE THREAD

**Issue by RaXorX** [stax76/mpv.net#122]
Recently had this issue while getting this script SubselectTK from https://github.com/zenyd/mpv-scripts to work with mpv.net

After some workarounds and having repeated errors with either python not being found or import exception from tkinter I got it to work with mpv. While the script is working fine with mpv unfortunately I had zero luck with mpv.net

Workaround for mpv is to change this:
`if python ~= nil then
      ret = utils.subprocess({ args = { python, options.subselect_path, video, options.down_dir, options.sub_language }})`
to
`if python == nil then
      ret = utils.subprocess({ args = { "python", options.subselect_path, video, options.down_dir, options.sub_language }})`

Apparently, both mpv and mpv.net weren't able to find python at all (I couldn't figure that part out much, I tried to install the necessary modules but apparently had no luck with it) so I improvised and changed the code so even if it doesn't find python the code still executes. This works well with mpv and I can see an output. Whereas in mpv.net I don't.

![image](https://user-images.githubusercontent.com/44987810/69673571-94891b00-10c0-11ea-98c9-b0c43e58ea9c.png)
![image](https://user-images.githubusercontent.com/44987810/69673574-981ca200-10c0-11ea-8e45-42212f6f2ce0.png)
As you can see above it works fine with mpv but not mpv.net I also updated mpv-1.dll to the current dev build but had no luck still. 

EDIT: Ah well, found out why the script was unable to find python. Apparently mpv.net works on ironpython. Now, I wonder if it is installed along with mpv.net or do I need to install it too, and get every other modules on it to get it to work.

**Comment by stax76** [comment]
You absolutely have to move the py script outside of the scripts folder. Maybe aks the script author for help, lua and subtitles are not my thing and i'm currently working on staxrip.

**Comment by RaXorX** [comment]
Thanks a lot. That worked apparently. Had no idea py scripts needed to be outside the scripts folder, is there some reason for it? In mpv it worked fine as it were.

**Comment by stax76** [comment]
There are two reasons why scripts folder don't work.

1. Py scripts in the scripts folder are executed with the built-in IronPython 2 interpreter, your script is designed to be executed by CPython 3. **Python 2 is not really compatible to Python 3**.

2. CPython is called from subselect Lua which **passes in specific command line arguments**, the interpreter of mpv.net don't pass in command line arguments.
