### ISSUE TITLE
It does not support Wheel_Left and Wheel_Right

### ISSUE THREAD

**Issue by muyangren907** [stax76/mpv.net#124]
When I use Apple Magic Mouse 2，mpv can set the shortcut key of  Wheel_Left and Wheel_Right Like：
>Wheel_Left    seek -1
 Wheel_Right   seek 1

but mpv.net does not support it.

**Comment by stax76** [comment]
It's difficult to fix without hardware.

**Comment by stax76** [comment]
Maybe you can try the last beta. I made a test with a software called X-Mouse Button Control, mpv.net did react with a repeat issue but it did react.
