### ISSUE TITLE
Only the first file is looped N times

### ISSUE THREAD

**Issue by vsub** [stax76/mpv.net#128]
I want to slideshow some images but the player just displays one for one second and then it goes to the next one
If I set 10 in "loop-file" only the first one is played 10 times(I want to have 10 seconds delay between the images)and then every next file is played once for 1 second and once it reaches the end and starts to loop the playlist,the first file is played only once

**Comment by stax76** [comment]
And it works better in mpv?

**Comment by stax76** [comment]
Closed because of missing reply.

**Comment by vsub** [comment]
Sorry about the delay
I forget about this post
But no,it works the same way in mpv

The first one is repeated 10 times and everything else is played for 1 second(unless there is some option I don't know about)

**Comment by stax76** [comment]
You can try reporting it on the mpv tracker.
