### ISSUE TITLE
File Association to Not Open Images

### ISSUE THREAD

**Issue by DReaper** [stax76/mpv.net#129]
I use mpv.net strictly for video files, and would not want it to load images when I am playing the files in a folder. Is there a way to disassociate images with mpv.net to not have it load with the playlist? Thank you.

**Comment by Restia666Ashdoll** [comment]
If you use Playlist manager, you can control what extensions to appear on playlist
https://github.com/jonniek/mpv-playlistmanager

**Comment by stax76** [comment]
I won't change something unless more people request it.

**Comment by stax76** [comment]
It's possible to disable the internal folder load feature with the option `auto-load-folder`.

Here is an alternative:

https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua

Might need customization to disable images.

**Comment by Sakusuke** [comment]
autoload.lua is great but it doesnt do what the op requested, which is opening folders with mpv and not queuing images files
