### ISSUE TITLE
Small key binding correction (small remark)

### ISSUE THREAD

**Issue by 44vince44** [stax76/mpv.net#13]
Hi Stax76, in the key bindings you have the line:
[           multiply speed 0.9     #menu: Speed > -10%

Where it should be :
[           multiply speed 1/1.1  #menu: Speed > -10%

With this syntax, if you increase-decrease-increase... speed as many times, you can always get back to the exact value of 1.00

**Comment by stax76** [comment]
I've corrected it, thanks.
