### ISSUE TITLE
Crash on window resize but only on one of my monitors.

### ISSUE THREAD

**Issue by bmferreira** [stax76/mpv.net#132]
![issue](https://user-images.githubusercontent.com/4138081/71323998-78b34200-24d1-11ea-96cd-b8a542b09ef6.gif)

I have 3 total monitors, 2 of them are connected to my dedictated graphics card (RX 480) and the remaining one (the one immediately next to my main one, in the GIF I included) is connected to the integrated Intel iGPU (I enabled it in bios to drive one of the monitors to reduce strain on the dedicated GPU).

I can resize mpv.net fine on both my main monitor and the other one (the 2 that are connected to the dedicated GPU). The one where it crashes on resize is the one connected to the iGPU, so I can already tell this is probably whats causing the issue but it happens with both HW acceleration on(auto) and completely off (SW only).

I included a short gif of the issue

Errors on EventViewer:

.Net Runtime | Application: mpvnet.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFF78984060

mpv.net | Faulting application name: mpvnet.exe, version: 5.4.4.0, time stamp: 0x5dd14d47
Faulting module name: atidxx64.dll, version: 26.20.15003.5016, time stamp: 0x5df7d2d3
Exception code: 0xc0000005
Fault offset: 0x0000000000014060
Faulting process id: 0x396c
Faulting application start time: 0x01d5b8df48542256
Faulting application path: C:\Program Files\mpv.net\mpvnet.exe
Faulting module path: C:\Windows\System32\DriverStore\FileRepository\u0349841.inf_amd64_01bbb629805d901e\B349895\atidxx64.dll
Report Id: dda5a872-b376-4c8d-b3f0-0d8a6297b53a
Faulting package full name: 
Faulting package-relative application ID: 

Installed graphics drivers version:

AMD: 19.12.3 (Latest Adrenalin 2020 Edition)
Intel: 26.20.100.7584

System Specs:
i7-9700K
RX480
16GB DDR4-3000

**Comment by stax76** [comment]
> Faulting module name: atidxx64.dll

Much likely a driver issue. There is not much I can do.

**Comment by bmferreira** [comment]
I was lacking the chipset driver from intel. Cheers.

**Comment by stax76** [comment]
No problem.
