### ISSUE TITLE
Window size is not remembered

### ISSUE THREAD

**Issue by TheBestPessimist** [stax76/mpv.net#133]
Possibly related: https://github.com/stax76/mpv.net/issues/42 

I have set `start-size=previous` and `remember-position=yes` so that the mpv.net window is always opened at the same location on screen and with the same window size. (for reference, i always keep the window on the half-right side of the screen (ie. "snapped right" by drag and drop of the titlebar).

The issue is that neither the size nor the positions are remembered. It doesn't matter if i set the window size while a video is playing (or not), or if i open mpv.net by double clicking the exe, or by opening a video file. This bug still happens.

Here's my full portable config: [portable_config.7z.txt](https://github.com/stax76/mpv.net/files/4021919/portable_config.7z.txt) (maybe it helps with debugging).

And a screenshot of what i believe to be the relevant settings: 
![image](https://user-images.githubusercontent.com/4482210/71765992-7e624c00-2f03-11ea-9c4b-3a7524728851.png)

**Comment by stax76** [comment]
Remembering the size isn't supported, only in the current session (previous/next video).

**Comment by TheBestPessimist** [comment]
Would it be difficult to add this feature for all sessions?

**Comment by stax76** [comment]
Probably yes, some Window functionality was rather difficult even it doesn't seem so, it has something to do with many features have multiple relations, not sure if my implementation is part of the problem. Feel free to request it with a new issue, it might take a while for me to catch up with all the open tickets.
