### ISSUE TITLE
minimum aspect ratio ignored

### ISSUE THREAD

**Issue by ll811** [stax76/mpv.net#134]
Getting black bars on the side despite the fact that I have this set to 0. Doesn't happen to everything, oddly enough vertical videos seem to work as they should, but a 708x480 dvdrip will leave black borders. Tried disabling autofit-smaller, didn't help.

**Comment by 44vince44** [comment]
I have noticed strange behaviours of Minimum aspect ratio, Most values have absolutely no effect. However, the value 0.5 worked. This value is just below the image format of a portrait 9/16 video.
minimum-aspect-ratio = 0.5

**Comment by ll811** [comment]
> NOTE: if your video's resolution is 708x480, and the video stream (or container) has a different defined AR, then you'll get the strips, because mpvnet seems to set the window size according to the video resolution, then correct the image with the AR factor, without scaling the window.

There's definitely something up with the file in question that I tested. The video size is listed as 708x540 but the height in pixels is 480. MPC-HC handles this without the black bars at a window size of 708x540, MPV gives black bars and a window with a size of 629x480 (708x480 if I count the black bars)

**Comment by stax76** [comment]
There was a black border issue fixed in the last beta:

https://github.com/stax76/mpv.net#beta

**Comment by stax76** [comment]
OK, there was still an issue with anamorphic videos, I try to upload the next build as soon as possible.

**Comment by stax76** [comment]
Should be fixed in 5.4.4.4 Beta.
