### ISSUE TITLE
Limited max window size

### ISSUE THREAD

**Issue by qazesz1** [stax76/mpv.net#136]
Hello,

I have configured "start-size" as "video" in the config editor, but the window size is limited to be 1387x780 when playing a 1080P video. Also I can't enlarge or shrink window with keyboard shortcut, but dragging with mouse is effective if border is on. My monitor is 1920x1080 and DPI is 100%.

This problem is not reproducible in original mpv. Since mpv.net implementes window in its own way, please investigate and make a fix.

**Comment by stax76** [comment]
I was able to reproduce and fix it and will upload a new release soon.

**Comment by qazesz1** [comment]
Nice to hear that

**Comment by stax76** [comment]
There is a new beta build available.

5.4.4.1

https://github.com/stax76/mpv.net/blob/master/Changelog.md

https://github.com/stax76/mpv.net#download

**Comment by qazesz1** [comment]
It seems the beta build doesn't solve the problem I mentioned in title. 1080p video still be displayed 
in a smaller size rather than a curtain size to fit my screen resolution. 
 ![0](https://user-images.githubusercontent.com/30799958/76922720-80398a00-690c-11ea-94ba-67e07c0458e4.PNG)

**Comment by stax76** [comment]
Please post a sample file.

**Comment by qazesz1** [comment]
This is what origin mpv behaviors
![mpv net](https://user-images.githubusercontent.com/30799958/77065808-f1686280-6a1c-11ea-9519-e2fcf5f7d8fb.JPG)

This is mpv.net
![mpv](https://user-images.githubusercontent.com/30799958/77065815-f3cabc80-6a1c-11ea-9604-d4755e589fff.JPG)

video sample
[Sony HD Demo - Paris-NO22FCBjbTQ_edit.zip](https://github.com/stax76/mpv.net/files/4354296/Sony.HD.Demo.-.Paris-NO22FCBjbTQ_edit.zip)

**Comment by stax76** [comment]
In the settings dialog there is:

autofit-smaller: <int> Minimum window height in percent. Default: 30

autofit-larger: <int> Maximum window height in percent. Default: 80

These defaults have changed recently, and there is also a hard coded limitation of max 90%, in the next build it will 95%.

**Comment by qazesz1** [comment]
Thanks for responding. 

I tried to set `autofit-larger` to 90 and the height of video window is 936, approximately 87% of 1080, then I toggled taskbar hidden automatically the height went to 972 that is 90% of 1080. Obviously taskbar is taken into account, so what's the meaning of limiting window height to 95%?

Another issue is that once `autofit-smaller` and `autofit-larger` be set, it becomes lower limit and upper limit of the window, enlarging or shrinking window to somewhere outside the range is not permitted except dragging border with mouse. In origin mpv I am able to adjust window freely with `autofit-smaller` and `autofit-larger` configured.

**Comment by stax76** [comment]
I don't understand what the problem is, there is normal window mode and there is fullscreen window mode. There is a screen size and there is a working area which is the screen size minus the task bar. There are situations where a window can be out of working area bounds which is a bad thing so there is a check to ensure the window will never be out of working area bounds. I can't do anything more here I think.

**Comment by qazesz1** [comment]
Thanks for your work. I also find out my answer in another issue thread. It's hard to say that is a problem, just different from other player I used before.
