### ISSUE TITLE
Virustotal detects as Virus.Win32.Floxif

### ISSUE THREAD

**Issue by debpalash** [stax76/mpv.net#137]
Ikarus engine detetcs as Virus.Win32.Floxif

File:  `mpv.net-setup-x64-5.4.4.0.exe`

https://www.virustotal.com/gui/file/013106590c9c63b950384621fe5d6fce2d2a7d709e8f2e192b755a18bb4acaba/detection

**Comment by bitsper2nd** [comment]
That is a false alarm. Nothing to worry about.
