### ISSUE TITLE
Fullscreen resets window size

### ISSUE THREAD

**Issue by darsain** [stax76/mpv.net#139]
Steps:

1. Launch some video = *window size **A***.
1. Resize the window = *window size **B***.
1. Enter & close fullscreen.

The window now reverted to window size **A**.

**Comment by stax76** [comment]
I'm not able to reproduce this, after fullscreen it goes back to the same size as before fullscreen as long as it's within the bounds of autofit-smaller and autofit-larger which by default is 40-75 %.

**Comment by qazesz1** [comment]
This is true in condition of `start-size=video`

**Comment by stax76** [comment]
With `start-size=video` it's not reproducible here either.

**Comment by qazesz1** [comment]
Tested on 5.4.4.0 and 5.4.4.1 x64 with portable config, only `start-size=video` modified.

**Comment by stax76** [comment]
My bad, I can reproduce it now.

**Comment by stax76** [comment]
I hope it's all good in 5.4.4.6 Beta which is now available.

Sorry for the long time to fix it.

It's however a feature I don't understand, it would help me much if somebody could explain why to use `start-size=video` ?

Download it here:

https://github.com/stax76/mpv.net/blob/master/Manual.md#beta
