### ISSUE TITLE
script for right click menu font size not working anymore

### ISSUE THREAD

**Issue by 44vince44** [stax76/mpv.net#14]
Dear Stax76, 
With older mpvnet like v2.0.0.0 we could still use this script to set font size of
the right-click menu:

-------------------------------------------------
using System;
using System.Drawing;
using mpvnet;
class Script
{
    public Script()
    {
        var form = MainForm.Instance;
        form.Invoke(new Action(() => form.CMS.Font = new Font("Segoe UI", 11)));
    }
}
---------------------------------------------------

Now this is not working anymore, I get an error at mpvnet launch "error CS1061: 'mpvnet.MainForm' does not contain a definition for 'CMS'".

Is there a way I can change the menu font size now?
Thanks!

**Comment by stax76** [comment]
It's because I've renamed CMS to ContextMenu, I'm not sure what works better but there is a non blocking BeginInvoke.

**Comment by 44vince44** [comment]
It worked, replacing CMS by ContextMenu in the script. Thank you!!
