### ISSUE TITLE
SSA Subtitle Issue: Vollkorn Font Rendered Double Size

### ISSUE THREAD

**Issue by nedragrevev** [stax76/mpv.net#141]
The Vollkorn font (a readily available google font) renders double the size it should be (or at least significantly larger than it should be). That means, any TS signs using this font look completely out of place and just ugly.
It's quite a specific issue but it may affect other fonts so I thought it was worth mentioning. Other players (and devices like iPad/Nvidia Shield) do not suffer this issue.

**Comment by stax76** [comment]
But is this mpv.net specific? Probably not, please try it mpv and if necessary report it on the mpv tracker.

**Comment by nedragrevev** [comment]
Good question, I should have thought of that. You are right, this is an mpv issue and not mpv.net specific.

**Comment by nedragrevev** [comment]
I've reopened this as this issue (which occurs with other fonts) has now been fixed, and is working correctly with mpv.

I understand you're taking a break, so it's fine if you don't respond for now. I'm just reopening this now rather than later. Just get to to it when you can. No rush.

Thanks.

**Comment by nedragrevev** [comment]
Fixed.
