### ISSUE TITLE
option scale the video player to a target size ?

### ISSUE THREAD

**Issue by amayra** [stax76/mpv.net#144]
we need option to resize a video to fit on your need like MPC Player
<img width="188" alt="1IiRV2pnKj" src="https://user-images.githubusercontent.com/7657277/78503627-c772a800-775f-11ea-95ba-fc4f25ab7f8b.png">

**Comment by stax76** [comment]
Half Size in mpcbe here reduces the video size without reducing or changing the window size so it creates black borders, what's the point?

**Comment by amayra** [comment]
so you can have original size of the video or change it to half or double in fullscreen.
my point : to be honest i only watch video in fullscreen and sometime you can't just stretch DVD in 1080p and i use double or zoom for specific details in video
there any problem with this options to be add ?
i try it this script but it didn't work :
https://github.com/VideoPlayerCode/mpv-tools/blob/master/scripts/quick-scale.lua

**Comment by stax76** [comment]
You can try if [video-zoom](https://mpv.io/manual/master/#options-video-zoom) does what you want. It's possible to customize mpv(.net), if you want improved defaults then please provide a much better description.
