### ISSUE TITLE
Duration still shows when seeking even though no-osd is explicitly used

### ISSUE THREAD

**Issue by tarantinosaur** [stax76/mpv.net#147]
It looks like [this](https://i.imgur.com/Gr7W6Sa.jpg) whenever I try to use any seeking command. [This is how all those seeking commands are configured.](https://i.imgur.com/pvzZ3sn.png) When I use osd-level = 0, every OSD messages get disabled except for the current time/duration message. I tried using the no-osd to other functions like volume and it worked. I don't know what's causing it to behave like that. I'm not a programmer so I'm not sure what I'm doing wrong.

**Comment by tarantinosaur** [comment]
After hours of trying to find the right command/code, I tried going through the installation folder and found a script called seek-show-position.py. I commented out everything inside and now the playback time doesn't show up anymore...

**Comment by stax76** [comment]
I'll add this to the documentation or possibly remove it from the defaults.

**Comment by tarantinosaur** [comment]
> I'll add this to the documentation or possibly remove it from the defaults.

Is there a way to properly disable that script?

**Comment by stax76** [comment]
It should be possible to delete a specific script or the complete folder.

**Comment by tarantinosaur** [comment]
Last question, what do I do so that whenever I exit from fullscreen, the window stays maximized? Right now, the window becomes smaller after exiting fullscreen.

**Comment by stax76** [comment]
Feel free to create ticket for it, I'll try to add support for that then.

**Comment by stax76** [comment]
I've excluded this script now and use it only personally, code is here:

https://github.com/stax76/mpv.net/blob/master/scripts/excluded/seek-show-position.js

**Comment by stax76** [comment]
New beta version is now available:

https://github.com/stax76/mpv.net#beta
