### ISSUE TITLE
Retain the pre-fullscreen window size after exiting fullscreen

### ISSUE THREAD

**Issue by tarantinosaur** [stax76/mpv.net#149]
Right now, the window becomes smaller when you exit from fullscreen.

**Comment by stax76** [comment]
If I understand right then the issue is going from maximized to full screen goes not back to maximized after leaving full screen.

**Comment by tarantinosaur** [comment]
Yeah, that's what I meant. Sorry for the poor phrasing.

**Comment by stax76** [comment]
No problem, I hope I can fix it but it's not high priority, related code was sometimes tricky in the past, we'll see.

**Comment by stax76** [comment]
I've added this now. When it's online I'll post here and close it.

**Comment by stax76** [comment]
New beta version is now available:

https://github.com/stax76/mpv.net#beta
