### ISSUE TITLE
Default menu items are broken in 3.4

### ISSUE THREAD

**Issue by ScottRFrost** [stax76/mpv.net#15]
Starting from a clean install of 3.4.0.0 downloaded from https://github.com/stax76/mpv.net/releases/tag/3.4 ==> mpv.net-setup-x64-3.4.0.0.exe

When clicking Preferences (or P hotkey):

> [Window Title]
> mpv.net
> 
> [Main Instruction]
> No command 'show-prefs' found.
> 
> [Content]
> Available commands are:
> 
> cycle-audio
> execute-mpv-command
> load-audio
> load-sub
> manage-file-associations
> open-conf-folder
> open-files
> open-url
> shell-execute
> show-about
> show-command-palette
> show-conf-editor
> show-history
> show-info
> show-input-editor
> 
> How to bind these commands can be seen in the default input bindings and menu definition.
> 
> [OK]
> 
> [Footer]
> Copy Message   Contact Support

When clicking Keys (or K hotkey):
> ... as above but ....
> [Main Instruction]
> No command 'show-keys' found.

When clicking Tools > Config Folder:
> ... as above but ....
> [Main Instruction]
> No command 'open-config-folder' found.

When clicking Tools > History:
> ... as above but ....
> [Main Instruction]
> No command 'history' found.

**Comment by stax76** [comment]
This happens whenever I remove or rename a command.

There are two ways you can repair it:

1. Delete input.conf

This will re-create input.conf with the defaults which can be found here:

<https://github.com/stax76/mpv.net/blob/master/mpv.net/Resources/inputConf.txt>

2. Edit input.conf

I will add migration code in the future if it's not hard to do. I always did that for staxrip but so far never for mpv.net.

**Comment by ScottRFrost** [comment]
Deleting the entire %AppData%\mpv folder seems to have worked.  Perhaps when a new version is detected it can overwrite input.conf if input.conf is the stock unmodified version of an old config?

**Comment by stax76** [comment]
I've added migration code now to handle it, thanks for the detailed description of the issue.

https://github.com/stax76/mpv.net/blob/master/mpv.net/Misc.cs#L247
