### ISSUE TITLE
Player close

### ISSUE THREAD

**Issue by Fran515** [stax76/mpv.net#151]
FileLoadException

Die Datei oder Assembly "System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" oder eine Abhängigkeit davon wurde nicht gefunden. Fehler bei der Überprüfung des starken Namens. (Ausnahme von HRESULT: 0x8013141A)

   bei mpvnet.MainForm.OnFormClosing(FormClosingEventArgs e)
   bei System.Windows.Forms.Form.WmClose(Message& m)
   bei mpvnet.MainForm.WndProc(Message& m) in D:\Projekte\CS\mpv.net\mpv.net\WinForms\MainForm.cs:Zeile 576.
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
By closing the Player.
Win 7 Pro x64.
mpv.net 5.4.4.3 Beta 20.04.2020

**Comment by stax76** [comment]
There is a PowerShell 5.1 dependency, it will be fixed in the next build.

**Comment by stax76** [comment]
Should be fixed in 5.4.4.4 Beta.
