### ISSUE TITLE
Disabling window border (using Toggle Border) should add close and minimize button on top right.

### ISSUE THREAD

**Issue by salarx** [stax76/mpv.net#154]
Just a suggestion. After toggling window border, a minimize and close button should be added on top right, which can have Visibility Option (and also the look) just like the OSC. Will give the player cleaner look.

**Comment by stax76** [comment]
In the latest beta by default there should be a top bar with min, max and close buttons, this is the default mpv OSC.

**Comment by salarx** [comment]
Oh it's already there in the beta... closing the issue.
