### ISSUE TITLE
Updater deleted my settings

### ISSUE THREAD

**Issue by pintassilgo** [stax76/mpv.net#155]
**Describe the bug**
I use mpv.net portable, with my settings in `portable_config` folder where mpvnet.exe is located (path in my setup: `E:\P\mpv.net\`).

**To Reproduce**
When I opened mpv.net, I was notified to update to 5.4.5.0. I accepted, but at the end of the PowerShell script my mpv.net folder was deleted along with my settings. The new version was put in a new folder named `new version` without my settings. That folder not even was renamed to `mpv.net`.

Deleted files didn't go to the recycle bin. I had to use specific software (Recuva) to recover my settings.

**Expected behavior**
Update should have been done without affecting my settings and keeping the name of the folder ( `mkv.net`).

**Comment by stax76** [comment]
I've improved it today using more checks and caution and delete to recycle bin. Will test it tomorrow.

**Comment by stax76** [comment]
Test succeeded, it's also preserving portable_config.

**Comment by stax76** [comment]
https://github.com/stax76/mpv.net/releases
