### ISSUE TITLE
Videos with certain unicode characters as title will throw an error

### ISSUE THREAD

**Issue by Naomi010Sentzke** [stax76/mpv.net#156]
**Describe the bug**
Opening the video file "【手描き】飴と鎖【ショートPV＋α】.mkv" will throw this error
```
ArgumentOutOfRangeException

No mapping for the Unicode character exists in the target multi-byte code page. (Exception from HRESULT: 0x80070459)

   at System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr ptr, Object structure, Boolean allowValueClasses)
   at System.Runtime.InteropServices.Marshal.PtrToStructure(IntPtr ptr, Type structureType)
   at mpvnet.mp.EventLoop() in D:\Projekte\CS\mpv.net\mpv.net\mpv\mp.cs:line 346
```
**To Reproduce**
1. Go to https://www.youtube.com/watch?v=6j8mQXkpdmg
2. Download it with youtube-dl or something(vp9 video and opus audio)
3. Keep the original video title
4. Open and see error

**Expected behavior**
The video plays just fine

**Screenshots**
![image](https://user-images.githubusercontent.com/53768184/80864565-29f88e80-8ca1-11ea-8d17-88da288b795e.png)

**Additional context**
This error is not present in 5.4.4.0

**Comment by Naomi010Sentzke** [comment]
Seems like repeatedly pressing Ok will make it go away. For some reason [Devil May Cry 5 - E3 2018 Announcement Trailer.mkv](https://www.youtube.com/watch?v=KMSGj9Y2T9Q) also has this, I only have to ok to ignore the error twice in this case.

**Comment by Naomi010Sentzke** [comment]
Also, if I stream them directly from youtube(you may need to update youtube-dl, either replace youtube-dl.exe or delete it and update the one in your path), theres no issues.

**Comment by stax76** [comment]
Hi, it should be fixed in the newest beta build.
