### ISSUE TITLE
Error while palying MKV Video with Chinese subtitle

### ISSUE THREAD

**Issue by sephiroth945** [stax76/mpv.net#157]
I update mpv.net to version 5.4.5.0, there is an erros while palying MKV Video with Chinese subtitle

[Window Title]
mpv.net

[Main Instruction]
ArgumentOutOfRangeException

[Content]
在多字节的目标代码页中，没有此 Unicode 字符可以映射到的字符。 (异常来自 HRESULT:0x80070459)

[Expanded Information]
   在 System.Runtime.InteropServices.Marshal.PtrToStructureHelper(IntPtr ptr, Object structure, Boolean allowValueClasses)
   在 System.Runtime.InteropServices.Marshal.PtrToStructure(IntPtr ptr, Type structureType)
   在 mpvnet.mp.EventLoop() 位置 D:\Projekte\CS\mpv.net\mpv.net\mpv\mp.cs:行号 346

![2020-05-03_231312](https://user-images.githubusercontent.com/7221339/80917962-de271180-8d94-11ea-9ddf-d22a8c51ffaf.png)

**Comment by stax76** [comment]
It's fixed in the last beta:

https://github.com/stax76/mpv.net/blob/master/Manual.md#beta

Because of that I need to make a new stable release soon, me and other western users didn't notice it unfortunately.

I leave this issue open until the next stable release is out.

**Comment by stax76** [comment]
New release is out:

https://github.com/stax76/mpv.net/releases

**Comment by sephiroth945** [comment]
Thank you！

stax76 <notifications@github.com> 于 2020年5月4日周一 12:13写道：
