### ISSUE TITLE
UOSC doesn't load

### ISSUE THREAD

**Issue by seagull** [stax76/mpv.net#159]
**Describe the bug**
Although UOSC is set up in a manner that works perfectly with vanilla MPV, mpv.net forces showing the OSC even with "osc = no" in the mpv.conf file, stopping it from loading.

**To Reproduce**
1. Copy UOSC to ~/scripts
2. Add the lines to mpv.conf:
```
osc = no
osd-bar = no
border = no
```

**Expected behaviour**
The OSC should not load and UOSC should load instead.
Instead, the OSC always loads, even when toggled (with DEL) to NEVER.

**Comment by bitsper2nd** [comment]
I use the latest uosc with the latest stable mpv.net release and it works for me. Just the the seekbar part since the functions and context menu are already provided by mpv.net.

**Comment by seagull** [comment]
I have MPV.net configured to use "portable_config" and my mpv.conf file is in C:\Program Files\mpv.net\portable_config.
Could you share your conf with me? It seems like whatever I do I can't get the inbuilt OSC to disappear to uOSC can interject.

**Comment by bitsper2nd** [comment]
> Could you share your conf with me? It seems like whatever I do I can't get the inbuilt OSC to disappear to uOSC can interject.

sure knock yourself [out](https://send.firefox.com/download/b03dfa4d15f96142/#_oudBfCrnQYmxc0bIt39zQ)!

**Comment by seagull** [comment]
Well I have no idea why, but your configuration files work perfectly @bitsper2nd.
Thank you for your help. This was the last step in my migration from MPC-HC to MPV.
