### ISSUE TITLE
mpv.net should make its own "mpv.net" appdata folder so as not to mess with regular mpv settings

### ISSUE THREAD

**Issue by Pentaphon** [stax76/mpv.net#16]
I use mpv and tried out mpv.net. When I used mpv again, I noticed it took the mpv.net settings instead of my own because they both use the same mpv appdata folder in AppData/Roaming. This shouldn't really happen because mpv.net isn't really mpv anymore. At this point, it is a separate project and should have it's own settings. 

Can we have mpv.net create its own "mpv.net" appdata folder going forward since it is a completely different project? This will let us use both if we want to, or let us test mpv.net without messing with existing settings, and make it clearer which settings go with which player.

**Comment by stax76** [comment]
The design is to be mpv compatible and share the settings. I don't see a problem, it has the advantage that both can be used and acquired knowledge can be re-used.

> When I used mpv again, I noticed it took the mpv.net settings instead of my own because they both use the same mpv appdata folder in AppData/Roaming.

This should not happen, it should not modify mpv settings unless you change something in the config editor and changes in the config editor are mpv compatible.

Where is your mpv.conf located? Maybe you have the some problem than this:

<https://forum.videohelp.com/threads/392514-mpv-net-a-lightweight-media-player-for-Windows#post2549995>

Next release will address it.

**Comment by Pentaphon** [comment]
My mpv.conf is located in the mpv folder under appdata/roaming. My problem is that it shares the settings when I don't want it to. I want mpv.net to have its own settings. I think it should have its own folder instead of messing with the settings of an existing mpv. That eliminates confusion for everybody. mpv.net is not mpv, and having them share settings just annoys people who use mpv but also want to test out mpv.net, because all of a sudden, their settings are being shared between the 2 players.

**Comment by stax76** [comment]
And if you create a portable_config folder next to mpvnet.exe?

**Comment by Pentaphon** [comment]
@stax76 That may work, but as soon as I open mpvnet.exe, it creates settings in my appdata/roaming/mpv folder. I think having it do that by default as soon as it opens is probably confusing a lot of people who already have mpv and want the 2 players to have separate settings out of the box.

**Comment by stax76** [comment]
Which version of mpv.net do you use?

**Comment by Pentaphon** [comment]
I used mpv.net-portable-x64-3.4.0.0.7z

**Comment by stax76** [comment]
> but as soon as I open mpvnet.exe, it creates settings in my appdata/roaming/mpv folder.

Didn't you say that you already have settings there for mpv?

**Comment by stax76** [comment]
What exactly do you want? You want mpv using settings in appdata and mpv.net not using this settings?

Just create a portable_config folder next to mpvnet.exe

**Comment by Pentaphon** [comment]
>Didn't you say that you already have settings there for mpv?
Yes

>What exactly do you want? You want mpv using settings in appdata and mpv.net not using this settings?
Yes. I want mpv.net to NOT generate settings there at all. That shouldn't be generated there by default. mpvnet.exe should create the portable_config folder next to it when mpvnet.exe is opened.

**Comment by stax76** [comment]
> Yes. I want mpv.net to NOT generate settings there at all.

If no settings exists then settings must be generated and mpv.net will ask where settings should be generated. If settings exist then no settings will be generated. I don't see a problem in my design, if you don't want mpv and mpv.net share settings just create a portable_config folder next to mpv or mpvnet.exe

**Comment by Pentaphon** [comment]
@stax76 That's the problem. It didn't ask me. It just generated them for me. If you want to avoid these problems entirely with the portable version, it should always and only create the portable_config folder next to mpvnet.exe instead of generating settings anywhere else on a user's machine. That's the only safe and sensible way to do a portable install of mpv.net.

**Comment by stax76** [comment]
Below is the logic in pseudo code, I still believe this logic is fine.

```
if not appdata folder exists and also not portable folder exists
    and also startup folder is writable and also
    not mpv.conf file exists in startup folder then

    ask where folder should be located
else
    if portable folder exists then use portable folder
    else if appdata folder exists then use appdata folder
    else if file mpv.conf exists in startup folder then use startup folder

if no folder exists create and use appdata folder
if not file input.conf exists then create file input.conf
if not file mpv.conf exists then create file mpv.conf
```

**Comment by stax76** [comment]
> That's the problem. It didn't ask me. It just generated them for me.

I can't see that in the logic!

**Comment by Pentaphon** [comment]
I have no way to prove that it did what it did and your new 3.5 version seems to address this so I will just close this issue.
