### ISSUE TITLE
Python support (temporarlily) removed, open in explorer file location not working, no alternative?

### ISSUE THREAD

**Issue by 44vince44** [stax76/mpv.net#163]
Hi again Stax, 

Python support was introduced, but the only script released used (afaik) is open in explorer.

Isn't there a way to include this feature without python, like so many other features that are included?

**Comment by stax76** [comment]
Hello Vince,

yes sorry, wasn't a good idea to add this script host. Here is a powershell replacement:

https://github.com/stax76/mpv.net/blob/master/scripts/powershell/show-in-file-explorer.ps1

**Comment by 44vince44** [comment]
@stax76 Hi Stax, thanks for helping me out, but I'm sorry it doesn't work and i never used powershell :(((
- I created a text file which i renamed (incl extension) to show-in-file-explorer.ps1.
- I included in the input.conf :   ctrl+e    script-message show-in-file-explorer 

a) if i put show-in-file-explorer.ps1 in configfolder\scripts, console shows me an error that it can't load unknown script, and doesn't work

b) if i put show-in-file-explorer.ps1 in configfolder\scripts\powershell it says error cannot find main.* etc and doesn't work

c) if i put show-in-file-explorer.ps1 in the mpv.net_program_folder\scripts, no error but doesn't work.

please explain to me what i have to do, i never used powershell in my life!

**Comment by stax76** [comment]
Sorry I forgot to mention that it must be put in the folder `config\scripts-ps`

**Comment by 44vince44** [comment]
@stax76 Thanks, i couldn't have guessed ;-)))))

**Comment by stax76** [comment]
mpv writes a warning to the console if something different from js and lua is in the scripts folder, so I decided to use scripts-ps. Such things must be documented. ;-)
