### ISSUE TITLE
How to Configure MpvLib?

### ISSUE THREAD

**Issue by mysteryx93** [stax76/mpv.net#164]
It's not a question about MPV.NET, but I wanted to ask you since you've done it -- with MpvLib.dll in .Net, how do you configure settings?

I want to use the library like if I was starting app with

    --af=rubberband=pitch-scale=0.981818181818181

I know you know the answer. Thanks :) And how can I change such settings on the fly at runtime.

**Comment by stax76** [comment]
Probably here:

https://github.com/mpv-player/mpv/blob/master/libmpv/client.h#L1128
