### ISSUE TITLE
Closing mpv.net from taskbar with right click makes sound alert

### ISSUE THREAD

**Issue by 44vince44** [stax76/mpv.net#165]
**Describe the bug**
When you close mpv.net from the taskbar (right-click, and select close), sometimes you get a system sound alert. version v5.4.7.3 x64 w10x64

**To Reproduce**
1. open mpv.net from the mpv.net icon or from a media file
2. immediately move the mouse pointer to the taskbar where you see mpv.net
3. right-click and select "close"

mpv.net will close with a system sound alert

**Expected behavior**
Should close without sound alert.

**Screenshots**
![SNAG-0000](https://user-images.githubusercontent.com/17828567/81465982-bb528e00-91d6-11ea-9420-a702b8f95921.jpg)

**Comment by stax76** [comment]
I think it was already fixed, probably the fix isn't reliable, unfortunately I don't remember how it was fixed.

**Comment by 44vince44** [comment]
It was long ago !!!

**Comment by 44vince44** [comment]
https://github.com/stax76/mpv.net/commit/327a097bcf3f6905c32e190bf1ddc0a6ff5fc425

**Comment by stax76** [comment]
Thanks searching for it, I could reproduce and fix it, verified with about 20 test runs.

**Comment by 44vince44** [comment]
@stax76 Thanks !!

**Comment by 44vince44** [comment]
@stax76 this is not fixed in 5.4.7.4 right? I'm still having the alert!

**Comment by stax76** [comment]
Probably I disabled the fix out of stupidity, it was disabled this morning. It's now enabled and I've added a comment with description to prevent that it gets removed again.

**Comment by 44vince44** [comment]
@stax76  thanks !!

**Comment by 44vince44** [comment]
@stax76 : it's all OK here with new release !! Thanks !!

**Comment by stax76** [comment]
OK, thanks for the feedback.
