### ISSUE TITLE
setting autofit makes 1 pixel black vertical appear on the right of the window, reproducible in specific case

### ISSUE THREAD

**Issue by 44vince44** [stax76/mpv.net#166]
**Describe the bug**
When autofit is set (values tested 55% and 65%), playing a video that has same resolution as the display, in windowed mode, makes a black vertical line appear on the right side of the window.
This vertical line is only 1 pixel width.

**To Reproduce**
1. if your display is 1920x1080p, chose a video that is EXACTLY 1920x1080p (and not 1920x800 etc)
2. set in mpv.conf autofit=65%
3. Play video, seek to a frame that is bright (at least on the right side), and look what happens at the right border.
A black vertical ligne of 1 pixel width is on the right, next to the border. If you remove borders, it is still there. This issues doesn't happen with original mpv, only with mpv.net with autofit set, and video WxH is exactly equal to display WxH.

![Untitled-1dd](https://user-images.githubusercontent.com/17828567/81502219-4d48bc80-92e5-11ea-9252-7274f18e26cb.jpg)

(this has been found by @ll811 and confirmed by me)

**Comment by ll811** [comment]
Can confirm this happens on 1080p files with a 1440p monitor as well.

**Comment by 44vince44** [comment]
So maybe it's happening only with files 1920x1080 ?

**Comment by stax76** [comment]
Thanks for investigating it. I think I found and fixed this, fortunately. On my 4K hardware it was tiny but still visible. I usually use rounding because it's more precise, in this case however truncating.

**Comment by 44vince44** [comment]
@stax76 wow thanks! that was fast!!!

**Comment by 44vince44** [comment]
Confirmed : it seems fixed all right! any thanks @stax76 !!!
