### ISSUE TITLE
Minimum aspect ratio (bug ? wording ? maybe could improve?)

### ISSUE THREAD

**Issue by 44vince44** [stax76/mpv.net#167]
Hi Stax,

The behaviour of Minimum aspect ratio is suugesting that :
- either it's not working correclty
or
- it is not a minimum, it's a threshold.

Because when I open a video that has an aspect ratio let's call it "fileAR".
On my setup,
if fileAR > minimum-aspect-ratio, then mpv window's aspect ratio will be fileAR
if fileAR < minimum-aspect-ratio, then mpv windows aspect ratio will be  1.77
This is what i understood from my tests.

So if this is true, It should be renamed to window-ar-threshold or something like that.
If this is not true, then maybe I'm missing the point, or there is a bug.
According to what you answer, i have more info, or suggestions.

**Comment by 44vince44** [comment]
actually, at this point, I'm suggesting no change, just want to understand what this is

**Comment by stax76** [comment]
Next build has a better description:

Minimum aspect ratio, if the AR is smaller than the defined value then the window AR is set to 16/9. This avoids a square window for Music with cover art. Default: 1.2 (mpv.net specific setting)

**Comment by 44vince44** [comment]
GOOD !!!! this is what i understood! and the new description is much clearer.

So I have a suggestion:
16/9 is the "target" aspect ratio of the window when the file AR is smaller than minimum-aspect-ratio. Can the user define the target aspect ratio ? I mean to create a new setting under minimum-aspect-ratio called **target-aspect-ratio** ?

so: 
**minimum-aspect-ratio** if the AR is smaller than the defined value, then the window AR is set to **target-aspect-ratio**  

with minimum-aspect ratio = 1.2 (default)
        target-aspect-ratio = 1.77 (default)

Of course target-aspect-ratio must be > minimum aspect ratio.

**Comment by stax76** [comment]
What's wrong with 16/9 ?

**Comment by 44vince44** [comment]
Nothing at all, 16/9 is good but we could be needing something else in some other cases. Here:

In the most common cases, the videos are in one of the following categories:
a) 16/9 (1.77) and more (2.35 etc) ; modern videos and cinema
b) 4/3 (1.33) the old video AR.
c) 9/16 (0.56) the portrait videos from the phones.

When usually windowed mode, usually you are doing something else or accessing something else on the desktop (otherwise you'd use full screen or maximize).
So if watching a video 16/9 or more, then there is nothing to say.
But if watching a video 4/3 or 9/16 (0.56) then the window of mpv.net is taking too much of the desktop area to show black bars.
For this usage, I would prefer setting target = 1 and not 16/9.
I would use minimum aspect ratio = 1, target = 1.

BTW I'm checking now the new release on both my laptop and the laptoop with the volume knob.

**Comment by 44vince44** [comment]
@stax76 are you going to change something? like create a new parameter "target-aspect-ratio" that is default 16/9 but could be set to 0.8, 1 or 3/4 ?

**Comment by stax76** [comment]
It does not seem very important, it takes time to build, too many options that hardly people use have a negative impact on usability. Look how clean mpc-be is and how messy vlc, potplayer and zoomplayer are.
