### ISSUE TITLE
Error when using mpv.net with Streamlink Twitch GUI

### ISSUE THREAD

**Issue by bnscv** [stax76/mpv.net#168]
**Describe the bug**
When using mpv.net with [Streamlink Twitch GUI](https://github.com/streamlink/streamlink-twitch-gui/), whenever I try to start a stream I get this error.

**To Reproduce**
1. Set up mpv.net as the default player (see screenshot 1);
2. Click on any stream to play it;
3. Get the error (see screenshot 2);
4. Click ok on the error window or close it;
5. The player open and the stream starts.

**Expected behavior**
No errors at all. The player should just open and start streaming.

**Screenshots**

Streamlink Twitch GUI settings, how mpv.net is setup:
![image](https://user-images.githubusercontent.com/32906075/81624461-9aec2480-93cc-11ea-8c71-8652d2329c19.png)

The error:
![image](https://user-images.githubusercontent.com/32906075/81624932-dc310400-93cd-11ea-833c-4aa3885927f5.png)

**Additional context**
The error pasted:

Exception

error setting property:  = yes

property not found

   at mpvnet.Core.HandleError(mpv_error err, Boolean throwException, String[] messages) in D:\Projekte\CS\mpv.net\mpv.net\mpv\core.cs:line 873
   at mpvnet.Core.set_property_string(String name, String value, Boolean throwException) in D:\Projekte\CS\mpv.net\mpv.net\mpv\core.cs:line 765
   at mpvnet.Core.ProcessCommandLine(Boolean preInit) in D:\Projekte\CS\mpv.net\mpv.net\mpv\core.cs:line 922

**Comment by stax76** [comment]
Please go into task manager and make a screenshot of the command line, it's probably not a mpv.net issue but rather incorrect command line arguments.

**Comment by bnscv** [comment]
> Please go into task manager and make a screenshot of the command line, it's probably not a mpv.net issue but rather incorrect command line arguments.

![image](https://user-images.githubusercontent.com/32906075/81630564-5e282980-93dc-11ea-88bb-b5ba4e4a4b50.png)

I also forgot to mention on my bug report that this didn't happened on an older version of mpv.net, when I tried it then (5.4.4.0 maybe).

**Comment by stax76** [comment]
Probably a bug, I'll investigate it.

**Comment by stax76** [comment]
5.4.8.1 Beta

Changelog:

https://github.com/stax76/mpv.net/blob/master/Changelog.md

Download:

https://github.com/stax76/mpv.net/blob/master/Manual.md#beta
