### ISSUE TITLE
Scrolling doesn't works on statistics page

### ISSUE THREAD

**Issue by Shashank066** [stax76/mpv.net#169]
On the statistics page scrolling doesn't works.

Tried the below options but scrolling didn't work

1. I tried to comment out the binds for up, down and mouse wheel from input config.
2.  Created script-opts/stats.conf with the following lines:
key_scroll_up=u
key_scroll_down=y
scroll_lines=1

![stats](https://user-images.githubusercontent.com/8770783/82066338-e401e880-96ec-11ea-91ce-c48a2e242f47.jpg)

**Comment by stax76** [comment]
How can it be reproduced? The frame times page fits on screen here.

It works in mpv?

**Comment by Shashank066** [comment]
On trying with mpv, scrolling also doesn't works. I had only started using mpv.net recently 3 days.

After rereading these pages it's confirmed it's mpv issue not mpv.net. Will ask there.

https://github.com/mpv-player/mpv/blob/master/DOCS/man/stats.rst
https://github.com/mpv-player/mpv/blob/master/player/lua/stats.lua

Thanks for mpv.net .

**Comment by stax76** [comment]
OK
