### ISSUE TITLE
mpv.net Portable should NOT create an user/appdata/roaming settings folder at all

### ISSUE THREAD

**Issue by Pentaphon** [stax76/mpv.net#17]
I think the Portable version of mpv.net should not make a settings folder in appdata/roaming. A portable version should have everything contained in one folder, so you don't leave your settings on a Windows machine, or so you can move settings, binaries, etc from machine to machine all in one folder. 

Anybody else think this makes sense? I think it's fine for the installer to create an appdata/roaming settings folder, but the Portable version should keep the settings, exe, etc all in one folder.

**Comment by stax76** [comment]
I don't understand why you see this in the latest release, it should detect where your config folder is and when it cannot find a config folder it should show a dialog asking you where it should create the config folder.

![Untitled](https://user-images.githubusercontent.com/11410540/57450751-95ab4580-725f-11e9-8985-afe1abcd7e20.png)

**Comment by Pentaphon** [comment]
>when it cannot find a config folder

@stax76 I think that's the problem. The portable version finds my mpv config folder, and uses it. It doesn't ask me anything. I think the portable version should just always remain portable and use the single folder you extract from the zip file for the settings, and nowhere else on the user's machine.

**Comment by stax76** [comment]
I still don't understand what the problem is, please elaborate.

> The portable version finds my mpv config folder, and uses it.

Isn't that what you want? Where is folder located?

> It doesn't ask me anything.

It only asks if no config folder exists, old releases didn't ask but create a config folder in appdata, maybe that's the problem, just delete it, new releases will ask.

Please ensure you have read the following:

<https://github.com/stax76/mpv.net#settings>

<https://mpv.io/manual/master/#files-on-windows>

**Comment by Pentaphon** [comment]
@stax76 The problem is that when I launch the portable version of mpvnet.exe, it automatically generates settings in my existing appdata/roaming/mpv folder that I am using for the original mpv.exe. I want it to NOT generate settings there and to instead, generate settings in a folder inside the folder that mpvnet.exe is in, AWAY from any existing settings on my PC.

**Comment by Pentaphon** [comment]
Your new 3.5 has 

>if conf files exist in the startup directory mpv.net will use the startup
directory as config directory instead of creating default conf files in appdata

So I will just close this issue.
