### ISSUE TITLE
Bluray titles are not able to be chosen.

### ISSUE THREAD

**Issue by adavier** [stax76/mpv.net#173]
**Is your feature request related to a problem? Please describe.**
Bluray Titles are not made are not available to navigate.

**Describe the solution you'd like**
A submenu of Navigate->Titles that will list all available titles (and ideally length)

**Describe alternatives you've considered**
The app can manually be started with the path br://x/D: where x is the title number.
The title information is made available in the MPV command line [see](https://gist.github.com/adavier/f65a5e97984b01d53e5c1ddaed82aac0)

**Additional context**
SMPlayer
![image](https://user-images.githubusercontent.com/30839200/83038934-6ebfdd00-a035-11ea-9438-84ae9ee6d860.png)

VLC
![image](https://user-images.githubusercontent.com/30839200/83038950-73849100-a035-11ea-8112-699e098887c1.png)
I'm not sure what processing VLC does compared to mpv to discard the shorter tracks.

I believe this applies to DVDs as well.

**Comment by stax76** [comment]
It's possible to get the title list by reading info level log messages with bd prefix. So yes, I plan to support this.

**Comment by stax76** [comment]
5.4.8.2 Beta

Changelog:

https://github.com/stax76/mpv.net/blob/master/Changelog.md

Download:

https://github.com/stax76/mpv.net/blob/master/Manual.md#beta
