### ISSUE TITLE
Video cutter integrated

### ISSUE THREAD

**Issue by vmackey** [stax76/mpv.net#176]
Hello Frank,

I hope you are doing fine.
I would like to request a new feature for mpv.net. It would be a simple cutter. We set a beginning mark and an end mark and MPV.net would cut that part, with the same quality than the original video. I already found this functionality in other projects for MPV itself:

https://gitlab.com/lvml/mpv-plugin-excerpt
https://github.com/Kagami/mpv_slicing
https://github.com/wiiaboo/mpv-scripts/blob/master/excerpt.lua

But since MPV.net is my main player, I would have loved to have it there. I think it would be a pretty great feature. So I hope you can consider it for the next update.

Thanks.

**Comment by Restia666Ashdoll** [comment]
Just use encode.lua
https://github.com/occivink/mpv-scripts

**Comment by vmackey** [comment]
Thank you for your reply.

I have set the script in MPVnet script folder and ffmpeg in the same folder as MPVnet, but I get this message:

Failed to load script
C:\Program Files\mpv.net\Scripts\excerpt.lua
Only scripts that ship with mpv.net are allowed in <startup>\scripts
User scripts have to use <config folder>\scripts
Never copy or install a new mpv.net version over a old mpv.net version.

Do you know how to fix this?

**Comment by vmackey** [comment]
Ok, I managed to fix the error message. Apparently, it was one script that caused and I removed it. However encode.lua doesn't seems to load. (I tried on the og MPV but same result.) Is the script working on your side?

**Comment by Restia666Ashdoll** [comment]
@vmackey You need to put it in your <config location>/Scripts and this
https://github.com/occivink/mpv-scripts/blob/master/script-opts/encode_slice.conf
in <config location>/script-opts
And put this in <config location>/input.conf
`c script-message-to encode set-timestamp encode_slice`

**Comment by Restia666Ashdoll** [comment]
enocode_slice does not capture subs, so I modified it to capture subs
```
# profile to slice the current video without reencoding it
# watch out that the extract will be snapped to keyframes; this is unavoidable when copying streams
# see encode_webm.conf for a detailed explanations of all the options

only_active_tracks=yes
preserve_filters=no
append_filter=
codec=-c copy
output_format=$f_$n.$x
output_directory=C:\mpvcapture\slices
detached=yes
ffmpeg_command=ffmpeg
print=yes
```
Change output to your own preferred directory.

**Comment by vmackey** [comment]
Thank you.
However, really sorry, but I still have an issue. I cannot find that /scripts-opts folder. It is in none of my disks (and more precisely, in any of mpv or mpv.net folder). I precise that I am on Windows 10, 64. Is it a factor?

**Comment by stax76** [comment]
In staxrip:

- install LAV Filters, needed for DSS2 to avoid indexing.
- load the Remux template, it has preprocessing like demuxing and indexing disabled, and it has audio and video encoding disabled.
- cut in the preview dialog, run job, done.

The lua script uses ffmpeg instead of mkvmerge and it's much likely that mkvmerge does this job much better! At least for complex files with many streams, features etc.

**Comment by vmackey** [comment]
Thanks guys. Unfortunately, I think these solutions are too technical for me (especially the last part about staxrip). I don't have the kind of knowledge to perform these tasks. So let's just hope the developer is interested in adding the cutter functionality in one of the next updates.

**Comment by vmackey** [comment]
Hello,
I just wanted to know if there was any update regarding the video cutter feature.

**Comment by cyzs233** [comment]
For video lossless cutting, you can try [lossless-cut](https://github.com/mifi/lossless-cut).  
I have been using it for years, surely a "The swiss army knife" for this task.

**Comment by stax76** [comment]
Another one is [vidcutter](https://github.com/ozmartian/vidcutter).

**Comment by stax76** [comment]
User script:

https://github.com/pvpscript/mpv-video-splice
