### ISSUE TITLE
First File is Never Shuffled

### ISSUE THREAD

**Issue by BinaryInk** [stax76/mpv.net#179]
**Describe the bug**
When running mpvnet from CLI using '-shuffle', the first file listed is always the first in the played, thus, the first item provided is not being shuffled with the rest.

**To Reproduce**
I have a TV folder organized by show then by season. Assume the structure is as below... 

A:\Videos\TV\Show A\Season 1\S01E01.mkv
A:\Videos\TV\Show A\Season 1\S01E02.mkv
...
A:\Videos\TV\Show A\Season 2\S02E01.mkv
...

If I do the following...
1. Open PowerShell
2. Type in and enter the following command: & mpvnet.exe "A:\Videos\TV\Show A" -shuffle
3. S01E01 will always play first.
4. Hit next and note that the rest are shuffled.

**Expected behavior**
I expect a different video to show up first every time I run the command.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by stax76** [comment]
It should be fixed in the next build.

**Comment by stax76** [comment]
5.4.8.2 Beta

Changelog:

https://github.com/stax76/mpv.net/blob/master/Changelog.md

Download:

https://github.com/stax76/mpv.net/blob/master/Manual.md#beta
