### ISSUE TITLE
MediaLoaded event delays when loading multiple files

### ISSUE THREAD

**Issue by mysteryx93** [stax76/mpv.net#18]
If I'm opening up 20 audio files at the same time, the first 8 files open right away, then each additional file gets the MediaLoaded event fired one per second, so it takes 12 seconds until the players are properly initiated. However, the file position shows they all started playing right away, but MediaLoaded is delaying.

What could be causing such a delay? Playback is working but it's screwing up the UI.

**Comment by stax76** [comment]
How do you open 20 files? Via command line? There isn't a MediaLoaded event, I tried and the FileLoaded event fires only once. Or do you start multiply player instances? Please show your code and tell me what is your goal.

**Comment by mysteryx93** [comment]
I have it in a usercontrol and I'm loading multiple instances. It would be a little bit difficult to share my code right now because it's spread out in several Git projects and libraries.

**Comment by mysteryx93** [comment]
Actually use [MpvPlayerUI ](https://github.com/mysteryx93/MediaPlayerUI.NET) like this. Bind it to a list of source files and it should display the list in separate players.

```
<ScrollViewer HorizontalAlignment="Right" Width="302">
    <ItemsControl ItemsSource="{Binding Playlist.Files}">
        <ItemsControl.ItemTemplate>
            <DataTemplate>
                <MpvPlayerUI:MpvMediaPlayer ui:UIProperties.IsLoopVisible="False">
                    <MpvPlayerUI:MpvMediaPlayerHost Source="{Binding FullPath, Mode=TwoWay}" Loop="True" />
                </MpvPlayerUI:MpvMediaPlayer>
            </DataTemplate>
        </ItemsControl.ItemTemplate>
    </ItemsControl>
</ScrollViewer>
```

**Comment by stax76** [comment]
https://github.com/hudec117/Mpv.NET/issues/5

**Comment by mysteryx93** [comment]
aaahhh got those 2 confused; and had just read about that earlier today. Would your version of it work in my case, for embedding the player into my application? What would you say is the difference between these two projects?

**Comment by mysteryx93** [comment]
Ah your version is a player application, not a re-usable DLL, so I'm better to stick to what I have and repost this into that other project. Thanks
