### ISSUE TITLE
allow multiple video windows (process instances)

### ISSUE THREAD

**Issue by SONGjiemo** [stax76/mpv.net#181]
最好在右键设置里面，添加一个多开选项。
多开功能，虽然不平凡。但是也算死刚需功能。
希望可以支持

**Comment by stax76** [comment]
Sorry but I don't understand, Google Translator:

> It is best to add a multi-open option in the right-click settings.
> Multi-open function, although not extraordinary. But it is still dead just need function.
> Hope to support

**Comment by SONGjiemo** [comment]
The software can open multiple video windows.

**Comment by SONGjiemo** [comment]
> Sorry but I don't understand, Google Translator:
> 
> > It is best to add a multi-open option in the right-click settings.
> > Multi-open function, although not extraordinary. But it is still dead just need function.
> > Hope to support

The software can open multiple video windows.

**Comment by OctaneTwisted** [comment]
set the "process-instance" setting in options to "multi"

**Comment by abh-oss01** [comment]
> set the "process-instance" setting in the config editor to "multi"

how? please provide the full syntax.

**Comment by OctaneTwisted** [comment]
> 
> 
> > set the "process-instance" setting in the config editor to "multi"
> 
> how? please provide the full syntax.

Right click in mpv.net -> Settings -> Show Config Editor -> Type "process-instance" in search -> Click "multi".

**Comment by abh-oss01** [comment]
@OctaneTwisted #176
