### ISSUE TITLE
Add dav files to the list of known video types

### ISSUE THREAD

**Issue by kpine** [stax76/mpv.net#182]
**Is your feature request related to a problem? Please describe.**
Dahua IP cameras generate video files in a proprietary format with the `.dav` file extension. Despite being an obscure format, mpv has no problems playing these video files (one of the very few that can play them besides the Dahua apps).

**Describe the solution you'd like**
Adding the .dav file extension to the [list](https://github.com/stax76/mpv.net/blob/50a2f13dbeaff8c8c5e8296892abbbd15bb37fa7/mpv.net/Misc/App.cs#L15) would allow me to use the F11/F12 next/previous file keys with the auto-load-folder option enabled. A camera directory may have tens of files, so it's convenient to view them this way. The directory is also littered with some kind index files so it takes several steps to load all the files into the playlist manually.

**Describe alternatives you've considered**
I work around this by changing the folder view to group by file type then select all the video files at once and drag and drop into mpv.net. It would be much simpler to just load the first file and go.

If there was a way to modify the list of video files via some script file or setting, I'd be happy to try that.

**Additional context**
None.

**Comment by stax76** [comment]
The internal auto load feature can be disabled in the conf editor. There is an auto load user script in the mpv wiki you could try. Maybe I'll just add this extension or make it customizable.

**Comment by stax76** [comment]
Will be supported in next beta.
