### ISSUE TITLE
Multiple instance setting doesn't work

### ISSUE THREAD

**Issue by tomzorz** [stax76/mpv.net#186]
**Describe the bug**
I'm trying to set up mpv.net so I can play multiple different videos at once. Despite setting the `process-instance = multi` setting in the config I still only have a single instance running no matter what I try.

**To Reproduce**
1. Change the `process-instance` setting to `multi`
2. Open a video with mpv.net
3. Open a 2nd video with mpv.net

**Expected behavior**
A 2nd instance of mpv.net opens and plays the 2nd video. 

**Actual behavior**
The video in the currently running instance changes instead.

**Additional context**
Windows 10 19041 (but existed in earlier updates too), mpv.net 5.4.4.0, using portable config

**Comment by abh-oss01** [comment]
doesn't work for me too, should this work for multiple audio files too?

**Comment by tomzorz** [comment]
@abh-oss01 I would imagine so, it shouldn't matter what the content is

**Comment by tomzorz** [comment]
Okay, so I cloned the project and managed to get multiple instances running as I edited Line 22 in App.cs: 

![image](https://user-images.githubusercontent.com/6363312/88160165-9636be80-cc0e-11ea-9271-33767a111af6.png)

This is checked on launch in Program.cs:

![image](https://user-images.githubusercontent.com/6363312/88160250-afd80600-cc0e-11ea-9000-a05e388b332a.png)

The only place where this value is written to is in App.cs, line 180: 

![image](https://user-images.githubusercontent.com/6363312/88160329-c9794d80-cc0e-11ea-804d-0a58edbc2362.png)

but this method wasn't called during any debug sessions I tried, so I'd imagine this is where the issue comes from - the settings I added in my mpv.conf are just simply not read/parsed/applied.

**Comment by abh-oss01** [comment]
so what has to be done from my side?

**Comment by stax76** [comment]
I'll investigate it but it might take some time due to summer break.

**Comment by tomzorz** [comment]
@stax76 thank you! Let me know if I can help out in any way.

**Comment by abh-oss01** [comment]
Thanks @stax76

**Comment by OctaneTwisted** [comment]
> the settings I added in my mpv.conf are just simply not read/parsed/applied

Don't you mean mpvnet.conf? That's where `process-instance = multi` and other mpv.net-specific settings would go.

**Comment by tomzorz** [comment]
heck @OctaneTwisted that was the trick! Sadly the docs were unclear in this regard and the config editor just placed the "process-instance" setting inside "mpv.conf" when I changed it - it didn't create an mpvnet.conf.

Thank you!

**Comment by abh-oss01** [comment]
Uh... what?

**Comment by tomzorz** [comment]
If you're like me, you had 2 config files in your folder: `mpv.conf` and`input.conf`. Apparently this `process-instance = multi` setting needs to live in a 3rd `mpvnet.conf` file.

**Comment by abh-oss01** [comment]
But that file doesn't exist for me :)
Should I create it manually?

**Comment by tomzorz** [comment]
Yes

**Comment by User486375** [comment]
You should just use the config editor in the player itself by press c then searching "multi" or "instance" and changing the setting to multi. This will create the file for you.

**Comment by stax76** [comment]
> Sadly the docs were unclear in this regard

mpv.net specific options are not yet documented in the manual. It's however possible to find them in the config editor by entering _mpv.net_ in the search field on top of the config editor.

> and the config editor just placed the "process-instance" setting inside "mpv.conf" when I changed it - it didn't create an mpvnet.conf.

Are you sure about this, can it be reproduced? Here it's written to mpvnet.conf.

**Comment by abh-oss01** [comment]
> > Sadly the docs were unclear in this regard
> 
> mpv.net specific options are not yet documented in the manual. It's however possible to find them in the config editor by entering _mpv.net_ in the search field on top of the config editor.
> 
> > and the config editor just placed the "process-instance" setting inside "mpv.conf" when I changed it - it didn't create an mpvnet.conf.
> 
> Are you sure about this, can it be reproduced? Here it's written to mpvnet.conf and works correctly.

The `mpvnet.conf` file doesn't exist by default for some users, it did exist for me, but not for everyone I suppose, in the folder `portable-config`.
I guess, that's the reason it's not a reproducible issue, and also, you're right about the docs, they're not as clear, hence most cannot enable multi instances at the first try.

**Comment by stax76** [comment]
It's probably not a bug or something but rather incorrect usage and lack of docs, there is now a new issue #189 suggesting improving the docs.

**Comment by tomzorz** [comment]
Ok, sorry about my confusion here @stax76  - I re-checked and the settings are applied to the correct place & the new mpvnet.conf file is created 👍

I assumed that the settings were written whenever I changed something, as there wasn't an "ok" or "apply" button in the window ; but now with testing I see that I need to close the window for that to happen: I'd maybe recommend some sort of UI informing us of that because it's not-conventional compared to other settings windows. (e.g. windows 10 settings - no save/ok button so the expectation is that changes are saved as they're made)

**Comment by abh-oss01** [comment]
Oh, and also, it has to be launched as admin everytime we change any config, can there be some way to launch the settings using admin everytime we want to change the config?
I'm obviously only referring to only C/Program Files installations.

**Comment by stax76** [comment]
Config editor has room for improvement I guess but it's a somehow difficult area and I don't plan working on it.
