### ISSUE TITLE
switching video for the first time doesn't respect window-maximized=yes

### ISSUE THREAD

**Issue by User486375** [stax76/mpv.net#188]
**Describe the bug**
When `window-maximized=yes` and you open a new instance of the player from clicking a video file, switching to another video in the folder for the first time will minimize the player, but maximizing it again and switching video keeps the player maximized. Also, if you open mpv.net directly and drop a file from a folder in, switching video for the first time doesn't minimize the player.

**To Reproduce**
1. Open a video and new instance of mpv.net by clicking a video file
2. Switch backwards or forwards to another video in the same folder
3. See that player is now minimized despite `window-maximized=yes`

**Expected behavior**
The player should remain maximized

**Additional context**
I'm new to mpv and wasn't sure if this is an issue unique to mpv.net. But with just some minimal testing using a `playlist.txt` file and `--playlist=playtlist.txt` to play consecutive videos in mpv directly. I can see that this issue is reproducible there, but only with different resolution videos. So for example if you switch between two 16:9 1080p videos it's fine but if you switch to a 720p video which also 16:9, it will minimize the player even if the player is re-maximized manually or started before dragging in multiple video files. Unlike mpv.net which only minimizes the player the first time and never when you start the player first.

Additionally, I thought of making an issue there myself related to their resolution specific minimizing issue, but considering I was making an issue here, as well as the fact that mpv.net seems to handle it fine when opened directly first (and I'm tired) I'll leave that decision up to you as it's ultimately to help you implement this feature easier.

**Comment by stax76** [comment]
It's fixed in the latest beta build 5.4.8.3.
