### ISSUE TITLE
How to compile?

### ISSUE THREAD

**Issue by rogersachan** [stax76/mpv.net#19]
I am unable to use the setup scripts to build the program, and building it in visual studio 2019 gives me a missing dll error.

**Comment by stax76** [comment]
Hi,

it should build, I just downloaded and tried. When you start debugging you would get:

System.DllNotFoundException: Unable to load DLL 'mpv-1.dll': The specified module could not be found.

This dll is libmpv, you have to download the binary release and put every file in the binary release in the output folder like it is defined in the project options. 

mpv.net\mpv.net\bin\x64\

What's your goal? Are you new to dotnet or new to programming in general?
