### ISSUE TITLE
Opening <10GB BD ISOs

### ISSUE THREAD

**Issue by DReaper** [stax76/mpv.net#190]
As per the changelog of 5.4.8.2 Beta:

> ISO image files can be opened like any other files, files smaller than 10 GB are handled as DVD and larger as BluRay.

However, there are BDs, in particular to ones bundled with music CDs that are smaller than 10 GB.

Will there be plans on supporting these? Thanks.

**Comment by stax76** [comment]
I've uploaded a new beta which addresses it:

Changelog:

https://github.com/stax76/mpv.net/blob/master/Changelog.md

Download:

https://github.com/stax76/mpv.net/blob/master/Manual.md#beta
