### ISSUE TITLE
Duration Time Not Showing When Seeking

### ISSUE THREAD

**Issue by DReaper** [stax76/mpv.net#191]
I'm currently on 5.4.8.4 Beta.

It looks to be related to this issue:
https://github.com/stax76/mpv.net/issues/147

However, unlike the poster there, I want to be able to see the duration timer when seeking. Setting to osd-level = 1 shows nothing, while level 2 and 3 permanently shows the duration timer. However, I only want to see it when seeking.

I don't see any option in the settings to bring this back.

**Comment by stax76** [comment]
I think you need to edit input.conf and remove no-osd prefix from the seek command.

https://mpv.io/manual/master/#command-interface-no-osd

https://github.com/stax76/mpv.net/blob/master/mpv.net/Resources/input.conf.txt#L60


Personally I prefer a script, this was removed from mpv.net.

https://github.com/stax76/mpv.net/blob/master/scripts/javascript/seek-show-position.js

**Comment by DReaper** [comment]
Removing the no-osd prefix from the seek command does not correct the issue. It brings back the OSD seek bar in the centre of the screen, which is not what I want. The duration timer does not come back.

Putting the script into the Scripts folder does not seem to work either.

**Comment by stax76** [comment]
> Removing the no-osd prefix from the seek command does not correct the issue. It brings back the OSD seek bar in the centre of the screen, which is not what I want. The duration timer does not come back.

You are right, you can use my script however, for me it works.

**Comment by stax76** [comment]
I believe they changed defaults, I've searched the manual for some keywords and found something:

https://mpv.io/manual/master/#options-osd-on-seek
