### ISSUE TITLE
"open dvd / blueray drive / folder" doesn't work

### ISSUE THREAD

**Issue by eNV25** [stax76/mpv.net#192]
Can't open folder.

### Steps
1. open mpv.net 
2. right click > "open dvd / blueray drive / folder"
3. select folder from within videos folder
4. click "ok"

### Expected behavior
open folder and start playing first video

### Actual
Nothing opens and starts playing. Is in same state as when you open program.

### Additional context
This should work the same way VLC does it.

### mpv.net
![image](https://user-images.githubusercontent.com/61089994/88943603-507e9380-d2a9-11ea-9a70-436077f4d178.png)

### VLC
![image](https://user-images.githubusercontent.com/61089994/88943839-9a677980-d2a9-11ea-88a4-dd9eef7e2fbf.png)

**Comment by stax76** [comment]
I can mount a BluRay ISO file with the mounting feature of Window 10 and then open the folder.

For DVD I don't have any test ISO files.

**Comment by eNV25** [comment]
The option is only for ISO or dvd/blue-ray? I thought it was also select folder.
Then you can close the issue. This only happens when opening folder in C drive.

**Comment by eNV25** [comment]
If it is only dvd/blue-ray, shouldn't there be an "open folder" option? Does it not work with disks?

**Comment by stax76** [comment]
A folder that contains a DVD/BD structure.
