### ISSUE TITLE
 mvp-1.dll not found

### ISSUE THREAD

**Issue by ahmetaksakall** [stax76/mpv.net#197]
When I download the source code and try to run it with visual studio with mpv.net.sln, I get such an error.(dllnotfoundexception)
![ex](https://user-images.githubusercontent.com/70489514/91669507-0db91100-eb1e-11ea-9463-ab5e33c7a4f9.PNG)

**Comment by ahmetaksakall** [comment]
Can anyone help? Please.

**Comment by stax76** [comment]
libmpv must be out dir...
