### ISSUE TITLE
 Accelerated caching of HTTP live streaming (HLS) protocol m3u8 video（加速缓冲HTTP Live Streaming（HLS）协议 M3U8视频）

### ISSUE THREAD

**Issue by SONGjiemo** [stax76/mpv.net#199]
The same m3u8 link uses QQ video playback cache faster. I hope it can be optimized.
Translation:
同样的m3u8链接  使用QQ影音播放缓存更快。希望可以优化一下。

**Comment by stax76** [comment]
Please request at the mpv tracker:

https://github.com/mpv-player/mpv/issues

**Comment by stax76** [comment]
Closing because it's probably a mpv or youtube-dl issue and not a mpv.net issue.
