### ISSUE TITLE
mpvnet.base

### ISSUE THREAD

**Issue by sodalom** [stax76/mpv.net#20]
Would it be possible to extract the libmpv wrapper code into core library. I am planning to use the library in non-GUI fashion.

**Comment by stax76** [comment]
There is a similar project which offers a library I think:

https://github.com/hudec117/Mpv.NET

I don't want to refactor a lot of code and break scripts and plugins, the design isn't great, nor bad, what you are looking for is in libmpv.cs and mp.cs.

What are you building?

**Comment by sodalom** [comment]
Thanks. That was what I was looking for.
