### ISSUE TITLE
Better subtitle list management

### ISSUE THREAD

**Issue by ArabCoders** [stax76/mpv.net#200]
**Is your feature request related to a problem? Please describe.**

I primarily use mpv.net to stream online content as it's handle so much, some videos have up to 30 subtitles cycling through the list takes so much time as i have to go thru each sub to check if its' correct sub or not, what even worse is sometimes subs shown as unknown.

**Describe the solution you'd like**

instead of just cycling through subs, i think being able to right click and presented with list of all the subs is much better idea than what is available right now. something similar to the attached photo will be even great.
![Untitled](https://user-images.githubusercontent.com/1621552/92500168-6fa40580-f205-11ea-8e21-a6b6e526429a.png)

**Comment by stax76** [comment]
With a URL I could take a look.

**Comment by ArabCoders** [comment]
you can try this attached file with has 16 subtitles embedded.

[test.zip](https://github.com/stax76/mpv.net/files/5287878/test.zip)

**Comment by ArabCoders** [comment]
> With a URL I could take a look.

@stax76 it does not have to be online even local you still have to cycle thru those 16 to reach the one you want.

**Comment by stax76** [comment]
Subtitle selection via menu is already supported. It's implemented for local files and Blu-ray.

https://raw.githubusercontent.com/stax76/mpv.net/master/img/Menu.png

**Comment by ArabCoders** [comment]
> Subtitle selection via menu is already supported. It's implemented for local files and Blu-ray.
> 
> https://raw.githubusercontent.com/stax76/mpv.net/master/img/Menu.png

@stax76 you are correct for local files it does show up, but for online sources it does not. see the attached picture
![mpvnet-no-tracks-online](https://user-images.githubusercontent.com/1621552/94509254-7f1ed900-021c-11eb-9790-e46cafa23a74.png)

for online test you can try this file [link](http://phanes.feralhosting.com/m7eesn/test.mkv)

**Comment by stax76** [comment]
Track selection for web streams will be available in the next build.
