### ISSUE TITLE
Default Image Zooming/Panning Scripts

### ISSUE THREAD

**Issue by brucethemoose** [stax76/mpv.net#201]
**Is your feature request related to a problem? Please describe.**

As an image viewer, mpv.net (as it comes out-of-the-box) is feature-light. Zooming and panning with the num pad is clunky.

**Describe the solution you'd like**
 
The integration of scripts similar to the zoom-on-cursor and click-to-pan scripts found here:

https://github.com/occivink/mpv-image-viewer (note that this is GPL 2.0)

Or the scripts here: https://gist.github.com/haasn/7919afd765e308fa91cbe19a64631d0f

In a way that they're only active when mpv.net opens image files.

**Describe alternatives you've considered**

Installing such scripts as a user seems easy enough.

**Additional context**

I saw someone on social media ask if mpv could be used as an image viewer, and I thought "yes, it would be great at that!.. but you have to script zooming/panning yourself."

This seems like a useful feature to include out of the box, and it wouldn't affect the playback of other file types.

**Comment by bitsper2nd** [comment]
mpv is not meant for image viewing. [Even the developers do not use it for such things](https://github.com/mpv-player/mpv/issues/7983).

**Comment by brucethemoose** [comment]
On the contrary, that thread seems pretty positive. The negative points seem to be

- ffmpeg quirks, but that's no different than video/audio files.
- Color spaces might not be read from image files, but at least one other participant claims that mpv gets that right.
- Huge images don't fit into small VRAM pools... at which point, graphics drivers will simply tap into system RAM, right?

**Comment by bitsper2nd** [comment]
The only ones enthusiastic about not officially endorsed or supported feats are users. If you really want mpv-like image viewer, I suggest to go with [qimgv](https://github.com/easymodo/qimgv).

**Comment by stax76** [comment]
At the moment I prefer having such functionality in external scripts.

If there is a problem with the integration of external scripts then I can take a look.
