### ISSUE TITLE
Recording feature

### ISSUE THREAD

**Issue by rapdodge** [stax76/mpv.net#203]
**Is your feature request related to a problem? Please describe.**
Recording a stream (like Record on VLC)

**Describe the solution you'd like**
I know, there is _--stream-record_, but it's not simple, and require to re-open the app...
Make an key binding like Ctrl + R

**Describe alternatives you've considered**
[none]

**Additional context**
Like this feature
![image](https://user-images.githubusercontent.com/33513626/94254264-beb1a080-ff50-11ea-97cd-73f2331f1d4a.png)

Thank you before

**Comment by stax76** [comment]
[stream-record](https://mpv.io/manual/master/#options-stream-record) is a property which can be set at runtime via key binding like so:

set stream-record aaa.mp4
