### ISSUE TITLE
Cannot the app because of DllNotFoundException in VS2019

### ISSUE THREAD

**Issue by abuasifkhan** [stax76/mpv.net#204]
I cannot run the project in VS2019. I have tried putting "mpv-1.dll" to the designated places (bin/x64) and adding it to the project by following the instructions. I would very much appreciate if someone could help me fix this issue. Thanks.

![image](https://user-images.githubusercontent.com/3448560/94366772-b8e7c680-00da-11eb-8f85-75b5cf2d7ba2.png)

**Comment by stax76** [comment]
It should work when libmpv is in the output folder.
