### ISSUE TITLE
Soccer playback

### ISSUE THREAD

**Issue by amian84** [stax76/mpv.net#205]
Hi, i'm trying to play my iptv channels in mpv.net. When i play a soccer channel, video has a linear deformation that is wierd.

There are any config to avoid and fix that visualization. For all channels or films work perfectly but when play faster mover cam as soccer match show that deforamtion.

I attach a screenshoot to show you.

Sorry for my english.

![image](https://user-images.githubusercontent.com/840567/95013016-a5d67880-063d-11eb-9dec-b2dca9cab729.png)
![image](https://user-images.githubusercontent.com/840567/95013029-b7b81b80-063d-11eb-9c4f-0eebe518d1d1.png)

Thanks!

**Comment by stax76** [comment]
It's interlaced, the default shortcut of mpv for deinterlacing is `d`.

I don't know if mpv has an automatic detection for it.

**Comment by amian84** [comment]
Thanks I'll try with that options

**Comment by amian84** [comment]
I jsut test that options and work perfectly, thanks so much.
