### ISSUE TITLE
Incorrect (non-multiple) resolution

### ISSUE THREAD

**Issue by Niotferdi** [stax76/mpv.net#207]
All videos that I open in mpv.net open in a window of the same size, regardless of the video resolution. Changing the scale of the window changes its scale relative to some other value, and not relative to the video resolution. Also, I did not find a way to open a video with a non-multiple resolution in full screen, leaving black bars for the ratio of video pixels to screen pixels 1:1.
How can you open a video in a 1:1 multiple window, changing the window scale, based on the video resolution, and be in full screen mode with black bars, keeping the same multiple?
There is no information on this in the manual (maybe I was looking badly, I don't know English).

**Comment by stax76** [comment]
I'm not really understanding what you want, does anybody else?

**Comment by Niotferdi** [comment]
Now I realized that I needed the "no-hidpi-window-scale" option. I could not find it when searching the manual on the first try.
