### ISSUE TITLE
Is there a way to scale and reset the window size relative to the video's native resolution?

### ISSUE THREAD

**Issue by YoJimbo0321** [stax76/mpv.net#208]
I was setting up my keybinds after downloading and noticed these bindings in input.conf:

```
 Alt++   no-osd set window-scale 1.2                 #menu: View > Window Size > Enlarge
 Alt+-   no-osd set window-scale 0.8                 #menu: View > Window Size > Shrink
```

However, I noticed that the behavior was kind of wonky in that the changes seem relative to the current size (i.e. if you repeatedly go back and forth between them the changes are not consistent).

I tried looking at the mpv documentation and I'm not sure if that is intended behavior or not, since the documentation seems to differentiate between window-scale and current-window-scale, but I'm not clear on how each works.

Additionally, the documentation states that "Setting [window-scale to] 1 will resize to original video size (or to be exact, the size the video filters output).", but `no-osd set window-scale 1` did not appear to do anything when I added that as a binding and tried it.

Ideally, I would like to be able to scale the window by factors of the original size, and also return to that original size with keybinds. Is this possible?

**Comment by stax76** [comment]
If you think that mpv can do better window scaling than mpv.net, then please tell me your full mpv configuration (mpv.conf and input.conf), I will try it then and tell you if it works for me and what I think about it.

Please note that I don't copy all features exactly but sometimes doing it my way because sometimes I think my way is better and other times it's too much work to copy it exactly.

Side note:

The tracker gets flooded with window requests since two years, it's tiring.

**Comment by cib3rpunker** [comment]
> 
> 
> If you think that mpv can do better window scaling than mpv.net, then please tell me your full mpv configuration (mpv.conf and input.conf), I will try it then and tell you if it works for me and what I think about it.
> 
> Please note that I don't copy all features exactly but sometimes doing it my way because sometimes I think my way is better and other times it's too much work to copy it exactly. And there might be occasions where I don't understand things well, like for instance why people care so much about native video size, I don't get it.
> 
> Side note:
> 
> The tracker gets flooded with window requests since two years, it's tiring.

I use the below command for WindowScale on MPV, please try to clone this functionality, it would be great to have it in a shortcut:

cycle-values window-scale "1.5" "2.0" "0.5" "1.0"

**Comment by stax76** [comment]
This will work in the next release.

The quotes are not needed, BTW.
