### ISSUE TITLE
Request for "set mpv.net as the system default palyer"

### ISSUE THREAD

**Issue by nkh0472** [stax76/mpv.net#209]
Maybe it could refers to the MPV installation script or something like this?

**Comment by bitsper2nd** [comment]
You can already do that. Using the context menu go to tools and you will see an option called setup. Click on that, then you will be able to set the default for audio, video and even set the variable path.

**Comment by nkh0472** [comment]
Thanks!
I'm using a portable version and I didn't expect this feature to be hidden there.
For most windows software, this function is placed in settings.
I think you probably could move this to settings, or make some kind of notice for first using the software, or simply put a readme file in the portable version.

**Comment by stax76** [comment]
The latest beta fixes this by showing the setup dialog automatically whenever mpv.net starts from a new location.
