### ISSUE TITLE
mpvnet does not recognize stdin as input

### ISSUE THREAD

**Issue by TETYYS** [stax76/mpv.net#21]
~When using streamlink with mpvnet player, player shows a blank screen with a logo in the middle of it.~

mpvnet doesn't seem to recognize stdin as input.

**Comment by stax76** [comment]
you mean this project

https://streamlink.github.io/

I need more detail like a command line or URL

**Comment by TETYYS** [comment]
Yes, but I believe that the issue is that mpvnet doesn't accept any stdin input. For example:

`ffmpeg -i video.mp4 -c:v copy -c:a copy -f matroska - | mpvnet -` doesn't work, but works fine for mpv (just replace `mpvnet` with `mpv`), tested on WSL command line.

**Comment by stax76** [comment]
It might not be possible to implement due to limitations of the Windows OS, I'll investigate it, thanks for the feedback.

**Comment by TETYYS** [comment]
I run Windows and it works fine with `mpv`.

**Comment by stax76** [comment]
That was fast, mpv has two executables, one for the console (mpv.com) and one for the windowing system (mpv.exe), probably they communicate via json ipc, I think that somewhere in the mpv documentation it is mentioned that this split is only needed on windows and Linux can do it together without a split.

**Comment by stax76** [comment]
All my attempts to make mpv work with input from stdin failed today. :(

**Comment by TETYYS** [comment]
Powershell and cmd is kinda bad with piping, that's why I used WSL.

**Comment by stax76** [comment]
My command line did not work because I used PowerShell instead of CMD.

mpv.net did a file exist check, that's why stdin don't work, it's gonna work in the next release. :-)

**Comment by stax76** [comment]
New release is online. Thanks for the feedback.
