### ISSUE TITLE
[Question] Force width instead of height?

### ISSUE THREAD

**Issue by m4gnify** [stax76/mpv.net#210]
Hey!
Just wondering if there's a way to force width instead of height, and preferably in pixels?
I use mpv.net to watch streams, and some of them are in weird resolutions, and end up with the correct height, but too "narrow".
Putting 2 windows next to one another therefor has an empty space between them. 
I'd like to force the width to 960 pixels; half of 1920p.

**Comment by stax76** [comment]
I don't understand the description well, maybe make a screencast.

After never ending window requests and weeks of work spent for them, I rather tired of window requests however...

**Comment by m4gnify** [comment]
Fair. Too small of an issue.
