### ISSUE TITLE
Can't play some youtube videos

### ISSUE THREAD

**Issue by abh-oss01** [stax76/mpv.net#211]
**Describe the bug**
The player can't play/open some youtube video links, it just gies blank and reverts to mpv's thumbnail.

**To Reproduce**
1. Open mpv.net
2. Paste a youtube link from your clipboard using "u" or "Right click --> Open --> Open URL"
3. Wait for some seconds
4. See error, it does't load or open.

**Expected behavior**
Video loads and plays

**Screenshots**
![Screenshot 2020-11-23 105407](https://user-images.githubusercontent.com/56572179/99931703-86c1b080-2d7b-11eb-89a9-0d084d771dd8.png)

**Additional context**
Many links still work, and there's no problem with them, but nowadays, many of the links do not play, I think an update to the program is long overdue.

OS: Windows 10 x64
mpv.net version: 5.4.8.0

**Comment by bitsper2nd** [comment]
Some videos are private, have geographic restrictions or require an account o watch. Not really an mpv.net or mpv issue tbh.

**Comment by abh-oss01** [comment]
I was able to play the very same videos in vlc, etc, the video is not really private.

I downloaded the latest youtube-dl .exe and pasted it in Mpv.net's DIR (in C:\Program Files\mpv.net) and tried playing the videos again, still no luck.

**Comment by bitsper2nd** [comment]
Not really an mpv.net issue. Rather a youtube-dl one.

**Comment by m4gnify** [comment]
Had same issue, updated youtube-dl from yesterday (14'th) and it works now at least.

**Comment by abh-oss01** [comment]
@stax76 the solution for this is updating youtube-dl 

and since mpv.net doesn't have it in it's install dir, I downloaded it manually from youtube-dl's Github page and pasted it there, and I update it manually using commands after an update is released.
Any way to automatically update it, through mpv.net?


Also wanna ask: The default icon (when nothing is playing) has changed to the with a christmas (Santa hat), how did it happen? It updated automatically? but the version number stayed same.

**Comment by stax76** [comment]
> Any way to automatically update it, through mpv.net?

No, except for users that know how to use a package manager like chocolatey or a scripting language like powershell or python, and know how to integrate it into the mpv.net menu. If you like you can make a feature request here or ask at the mpv section on reddit.

> Also wanna ask: The default icon (when nothing is playing) has changed to the with a christmas (Santa hat), how did it happen? It updated automatically? but the version number stayed same.

It appears on a certain date and can be disabled with:

script-opts = osc-greenandgrumpy,...

**Comment by abh-oss01** [comment]
>No, except for users that know how to use a package manager like chocolatey or a scripting language like powershell or python, and know how to integrate it into the mpv.net menu. If you like you can make a feature request here or ask at the mpv section on reddit.



Ok, please add this feature

**Comment by kawakamitatsuya** [comment]
> **バグの説明** プレーヤーが一部の YouTube ビデオ リンクを再生/開くことができず、空白になり、mpv のサムネイルに戻ります。
> 
> **** 動作を再現**するには:**
> 
> 1. mpv.net を開く
> 2. 「u」または「右クリック --> 開く --> URL を開く」を使用して、クリップボードから YouTube リンクを貼り付けます。
> 3. 数秒待ちます
> 4. エラーを参照してください。読み込まれないか、開きません。
> 
> **予想される動作** 動画の読み込みと再生
> 
> **スクリーンショット** ![スクリーンショット 2020-11-23 105407](https://user-images.githubusercontent.com/56572179/99931703-86c1b080-2d7b-11eb-89a9-0d084d771dd8.png)
> 
> **追加のコンテキスト** 多くのリンクはまだ機能しており、問題はありませんが、現在、多くのリンクが再生されていません。プログラムの更新が遅れていると思います。
> 
> OS: Windows 10 x64 mpv.net バージョン: 5.4.8.0

As of 2023/02/22, even with the latest .exe, I cannot play from the Youtube URL clipboard.

**Comment by kawakamitatsuya** [comment]
As of 2023/02/22, even with the latest .exe, I cannot play from the Youtube URL clipboard.
but....
As of 2023/02/23, I found out about app ”yt-dlp.exe” and put it in and it was correct and played the youtube clip. I thank the development author.

**Comment by Kamek437** [comment]
lul, sorry
