### ISSUE TITLE
Youtube quality

### ISSUE THREAD

**Issue by abh-oss01** [stax76/mpv.net#212]
How to select the best quality available in a youtube video while playing using the open URL option?
I intend to select the best available quality **by default** after the URL is pasted in the player using Right click -> Open -> URL.
Please guide accordingly, thanks.

**Comment by bitsper2nd** [comment]
Add the following to your mpv configuration file. More info about that in the mpv manual or wiki. 
```
[Youtube-dl]
profile = protocol.https
ytdl-format = bestvideo[height<=?1080]+bestaudio/best[height<=?1080]
demuxer-seekable-cache = yes
demuxer-max-bytes = 2048MiB
demuxer-max-back-bytes = 1024MiB
```

**Comment by abh-oss01** [comment]
Most videos nowadays are 4K, how to stream 4K 60fps, your config is limited to 1080p.

**Comment by bitsper2nd** [comment]
Easy. In the third line from the code I posted, change 1080 to 4230.

**Comment by abh-oss01** [comment]
Yes, I figured that, but, like, any option which selects the best available by default?
Without specifying it in that config.

**Comment by bitsper2nd** [comment]
just leave best video and best audio without being specific. See [this page](https://www.mankier.com/1/youtube-dl#Examples_(TL;DR)) for reference on ytdl.

**Comment by abh-oss01** [comment]
> just leave best video and best audio without being specific. See [this page](https://www.mankier.com/1/youtube-dl#Examples_(TL;DR)) for reference on ytdl.

sorry, I couldn't do this, I didn't understand, can you please tell this again, in a more simpler manner.
What I intend to do is -- 

Mpv.net selects best available video and audio quality after a youtube link is pasted **automatically**.

Thanks, and sorry for being not able to understand.

**Comment by 44vince44** [comment]
@abh-oss01 Currently in mpv.net there is no manner to specify that without editing the mpv.conf file, and adding a line in it.

What I understand is that you don't know how to do that, right ? You prefer it to be included in the settings window.
If this is right, then this is **a feature request**, and you'll have to wait that it gets implemented in a next version. 

@stax76 The lines would be (in mpv.conf)

4k =>             ytdl-format=bestvideo[height<=2160]+bestaudio/best[height<=2160]
1080p=>        ytdl-format=bestvideo[height<=1080]+bestaudio/best[height<=1080]
720p (default) => leave empty **or** ytdl-format=bestvideo[height<=720]+bestaudio/best[height<=720]
480p =>         ytdl-format=bestvideo[height<=480]+bestaudio/best[height<=480]
360p=>          ytdl-format=bestvideo[height<=360]+bestaudio/best[height<=360]

I think those options are more than enough.

**Comment by stax76** [comment]
Isn't the best possible quality already the default? Sorry, I lack both interest and experience in this topic.

**Comment by 44vince44** [comment]
> Isn't the best possible quality already the default? 

yes it is, I don't know why i remember 720p, but i've just checked:

From the doc:

> By default youtube-dl tries to download the best available quality, i.e. if you want the best quality you don't need to pass any special options, youtube-dl will guess it for you by default.

so my mistake, i've corrected my post

**Comment by stax76** [comment]
@44vince44 Ok, thanks for the clarification, can be closed then.

**Comment by abh-oss01** [comment]
> so my mistake, i've corrected my post, and we need do nothing...


really? I don't need to write any line in the conf? how so?
I have seen the videos play at low resolution, even when there is something like 1080p available, the one I paste and play in mpv.net seems 480p or 720p.

I have no changes regarding quality in the conf.

**Comment by 44vince44** [comment]
Yes the official documentation of youtube-dl says you need to add nothing to the conf file, because it will attempt best quality
However, if you want to be sure just put this line in the mpv.conf file:

ytdl-format=bestvideo[height<=2160]+bestaudio/best[height<=2160]

copy and paste it as is.
