### ISSUE TITLE
Window title is not updated properly when using `loadfile` with `replace`

### ISSUE THREAD

**Issue by mochaaP** [stax76/mpv.net#214]
**Describe the bug**
The window title will just show `"mpv.net " + Application.ProductVersion;` instead of `media-title` or `path` when invoking `loadfile video.mkv replace`. Progress bar works well.

**To Reproduce**
1. Open console
2. Do `loadfile video.mkv replace`
3. Wait for file loads
  ![Wrong title](https://user-images.githubusercontent.com/21154023/100484880-16c77780-3139-11eb-8f57-dd92d091fa4d.png)

**Expected behavior**
Implemented: Show `media-title` or `filename` if loaded correctly
Expectation: Dynamically updates title by observing the `title` property

**Additional context**
<https://github.com/stax76/mpv.net/blob/94eaf8144fe0fecfeed6dafd0ac72582f46ace99/mpv.net/WinForms/MainForm.cs#L484-L506>

**Comment by stax76** [comment]
Thx for reporting, fixed in next build.
