### ISSUE TITLE
Add logo overlay toggle

### ISSUE THREAD

**Issue by mochaaP** [stax76/mpv.net#216]
**Is your feature request related to a problem? Please describe.**
![Window showing mpv seasonal logo being overlayed by mpv.net logo](https://user-images.githubusercontent.com/21154023/101173733-e4100880-367d-11eb-9df6-23467b00253d.png)

Sometimes (e.g. Christmas) mpv will have a seasonal logo displayed instead of the original logo. I'd like to keep that taste.

**Describe the solution you'd like**
Give users an option to disable the mpv.net logo overlay in `mpvnet.conf`.

**Describe alternatives you've considered**
1. Draw additional seasonal icons for mpv.net.
2. use <https://github.com/mpv-player/mpv/blob/152b0e2/player/lua/osc.lua#L2493-L2503>

**Additional context**
<https://github.com/stax76/mpv.net/blob/85a3506403df0af7153de30d2f304c9d3b4176cc/mpv.net/mpv/Core.cs#L1171-L1198>
<https://github.com/stax76/mpv.net/blob/404a8f110d66416fa86fe20d74b6baaed2b6b7c6/mpv.net/Misc/App.cs#L170-L194>

**Comment by mochaaP** [comment]
A tempfix for those who are looking for solution:
```javascript
mp.register_idle(function() {
  setTimeout(function() {mp.command("overlay-remove 0")}, 100);
})
```

add this to `~~/.init.js`.

**Comment by stax76** [comment]
@mochaaP Ok, good idea.

I've changed mpv.conf defaults to:

script-opts = osc-scalewindowed=1.5,osc-hidetimeout=2000,**osc-greenandgrumpy=yes**,console-scale=1

This will remove the Santa hat, but I hope for a volunteer modifying the blue logo:

https://github.com/stax76/mpv.net/blob/master/mpv.net/Resources/mpvnet.png

So we get a blue logo that has the Santa hat on top.

**Comment by mochaaP** [comment]
Thanks for the reply!

However, I will prefer drawing a vector image instead of a bitmap (just like how they did it in `osc.lua`, or overlay the Santa hat from `osc.lua`.

Suggestions welcome.

**Comment by stax76** [comment]
The beta from today shows a Santa hat.
