### ISSUE TITLE
5.4.8.5 problem with "Would you like to setup mpv.net" when mpv.net exists in several places

### ISSUE THREAD

**Issue by 44vince44** [stax76/mpv.net#218]
**Describe the bug**

Introduction:
There are TWO mpv.net 5.4.8.5 on any user's computer, when uses mpv.net and staxrip.
One mpv.net usually in C:\Program files\mpv.net\
One mpv.net usually in C:\Program files\Staxrip\Apps\Support\mpv.net

THE BUG:

When you use one of them, you are asked "Would you like to setup mpv.net" .
When you use the other one you are still asked "Would you like to setup mpv.net" 
When you use the first one again, you are asked AGAIN "Would you like to setup mpv.net" 
....

**Comment by stax76** [comment]
It's by design, kind of, probably not the best possible design. 😀 I had worked around it by using a custom path in StaxRip, so in your example staxrip uses _C:\Program files\mpv.net_. I think I will have to change this to allow multiple paths.

**Comment by 44vince44** [comment]
Well, it's something like: mpv.net checks if its current location is "new" compared to the one stored somewhere (registry?).
So indeed, if you allow in registry (?) several paths for mpv.net, and mpv.net checks all the paths stored there, then the problem wouldn't occur anymore.
(did I understand the problem correctly?)
BTW don't forget to put in next beta youtube-dl or a txt file with a url where to download it...

**Comment by stax76** [comment]
@44vince44 Thanks for reporting the issues.


I've just updated the manual:

https://github.com/stax76/mpv.net/blob/master/Manual.md#installation

https://github.com/stax76/mpv.net/blob/master/Manual.md#open--open-url-or-file-path-from-clipboard


And fixed the mpv.net setup dialog issue.

**Comment by 44vince44** [comment]
Many thanks !!

**Comment by stax76** [comment]
You're welcome. 🙂
