### ISSUE TITLE
Am i running mpv commands wrong?

### ISSUE THREAD

**Issue by TheBestPessimist** [stax76/mpv.net#219]
mpv is at location:  `C:\all\mpv.net\mpvnet.exe`
current directory: `H:\reunion\testing handbrake`
	which has 2 files:  `VID_20201021_161445.mp4`  and `q0.mkv`

I want to play my 2 video files side by side, as in the example here: https://github.com/mpv-player/mpv/issues/3854#issuecomment-263884657, but i keep getting an error, as if wrong params are sent to mpv.

used cli: `C:\all\mpv.net\mpvnet.exe VID_20201021_161445.mp4  --external-file=q0.mkv --lavfi-complex='[vid1] [vid2] hstack [vo]'`

Am i doing something wrong?

Full exception:
```
Exception

error setting property: external-file = q0.mkv

property not found

   at mpvnet.Core.HandleError(mpv_error err, Boolean throwException, String[] messages) in D:\Projekte\CS\mpv.net\mpv.net\mpv\core.cs:line 873
   at mpvnet.Core.set_property_string(String name, String value, Boolean throwException) in D:\Projekte\CS\mpv.net\mpv.net\mpv\core.cs:line 765
   at mpvnet.Core.ProcessCommandLine(Boolean preInit) in D:\Projekte\CS\mpv.net\mpv.net\mpv\core.cs:line 922
```

Printscreen:
![image](https://user-images.githubusercontent.com/4482210/103152052-ba359780-478c-11eb-9ce9-ab7772b425e0.png)

**Comment by stax76** [comment]
The error message clearly says that a property named external-file does not exist.

You can show available properties from the menu using:

View > Show Properties

There you can also see that there is no external-file property, but there is an external-file**s** property, I suggest trying this property instead.

**Comment by TheBestPessimist** [comment]
Thank you, `--external-files` works :). (it's funny how this little thing fixed it)


However, there is `--external-file` as an alias.
![image](https://user-images.githubusercontent.com/4482210/103157796-90e22f00-47bf-11eb-9e8d-dd15490d5994.png)

I also tried `--external-files-append`, but that gives error as well

**Comment by stax76** [comment]
Next build will handle external-file.

List option features like append are not yet supported, do you have a real use case for it?

**Comment by TheBestPessimist** [comment]
> List option features like append are not yet supported, do you have a real use case for it?

None. I have found this issue/question since because I needed a way to pixel peep at some videos with different compressions.

Thank you for the advice and please don't invest more time on this.
