### ISSUE TITLE
Playlist

### ISSUE THREAD

**Issue by Bhooty** [stax76/mpv.net#227]
How to select the channels on playlist after pressing f8
cant seem to move it

**Comment by stax76** [comment]
I don't understand the question, what has the playlist to do with channels?

**Comment by Bhooty** [comment]
Sry for misunderstanding 
Its a iptv playlist m3u 
I can see the playlist by pressing f8 but can't go to a different one in list like in vlc

**Comment by stax76** [comment]
In the context menu please try:

Navigate > Previous File (F11)
Navigate > Next File (F12)

If you search something the easiest way is to press F1 to show the command list which has a useful search feature.

**Comment by Bhooty** [comment]
> 
> 
> Ah OK, In the context menu please try:
> 
> Navigate > Previous File (F11)
> Navigate > Next File (F12)
> 
> If you search something the easiest way to find it is pressing F1 to show the command list which has a useful search feature.

it goes one by one i know
 i want to go a one directly instead of going one by one as there are lot on list
![image](https://user-images.githubusercontent.com/46019727/107852848-150a7780-6e3d-11eb-93dd-3f73c0192f30.png)

suppose i want to go to Gazi Tv directly

**Comment by stax76** [comment]
I don't have a solution for this at the moment.

**Comment by HGhostRevisionist88** [comment]
I know this is an old issue, but for other people (and maybe still the OP) I want to add that the solution to this issue should be to use scripts that mpv has always offered to make the player better by the users and for the users.
In the case of a playlist, it is easy to find https://github.com/jonniek/mpv-playlistmanager which is easy to use and doesn't take long to add to mpvnet. It has many features like you can fo to whatever entry you want on the playlist without going one by one, you can also rearrange elements and has other features like saving playlists, reverse it, loaded other files from the folder you loaded your local file(s) etc etc, it is so much better than what mpv offers 'out of the box' with the f8 key. So I would suggest to try it.

I mean, I understand people wanting mpvnet to offer everything out of the box that is missing in mpv, but sometimes we should not forget mpvnet is still mpv and mpv was made this way with scripts and stuff and people can improve the experience themselves and as a community, and unless stax decided to build an alternative solution for a playlist manager or any other feature natively for mpvnet, we might usually find a 3rd party lua script that will improve the player for something we need like this.

**Comment by stax76** [comment]
It hopefully works in the last beta.
