### ISSUE TITLE
FR: Allow disabling clipboard monitoring for URLs

### ISSUE THREAD

**Issue by pickx** [stax76/mpv.net#23]
I find this feature annoying. Most of the time I don't want to play the URL I happen to have in my clipboard. If I do I can just use the "Open URL" feature.

Also, thanks for this program!

**Comment by stax76** [comment]
Thanks for the feedback! Next release will have a setting in the config dialog, working on this caused me doing much refactoring, I hope it will be stable.

**Comment by stax76** [comment]
The new release is available.
