### ISSUE TITLE
input.conf commands without shortcut or menu entry in command palette

### ISSUE THREAD

**Issue by butterw** [stax76/mpv.net#231]
**Is your feature request related to a problem? Please describe.**
I'm trying to put together a minimalistic menu in mpv.net, which means cutting a lot of commands.
I would like to still be able to access these commands via the command-palette, without having to affect a hotkey to them like in mpv. Currently the only way to do this is to put them in a submenu, ex input.conf:
 _      add saturation  1      		  #menu: Tools > Controls > Increase Saturation	

It seems the following could work, but it doesn't currently (the command doesn't show up in the command palette): 
 _      add saturation  1

**Comment by butterw** [comment]
After further investigation:
- The command palette currently only shows the commands as displayed in the menu.
- But the input config shows menu display name, hotkey and command. If there was an associated execute option and if hotkey _ was shown, it could handle commands without hotkey or menu entry.

![](https://files.videohelp.com/u/295418/mpvnet_command-palette.png)

**Comment by bitsper2nd** [comment]
Not related to your issue, but could you share the input.conf that you are making?

**Comment by butterw** [comment]
Will do once this issue gets addressed.

**Comment by stax76** [comment]
New hotfix is online with implementation for this request.

It has also window scaling improvements, default menu was improved and can scale beyond autofit-smaller and autofit-larger.

```
 Alt++   script-message mpv.net scale-window 1.2     #menu: View > Zoom > Enlarge
 Alt+-   script-message mpv.net scale-window 0.8     #menu: View > Zoom > Shrink
 _       ignore                                      #menu: View > Zoom > -
 Alt+0   set window-scale 0.5                        #menu: View > Zoom > 50 %
 Alt+1   set window-scale 1.0                        #menu: View > Zoom > 100 %
 Alt+2   set window-scale 2.0                        #menu: View > Zoom > 200 %
```

Thanks for the feedback.

**Comment by butterw** [comment]
I tested the hotfix mpvnet.exe 2021.03.10.
- window-scale seems to be working as expected.

The new command palette display works well overall (commands without a menu entry and/or without a hotkey) are displayed and can be launched.

This command in input.conf did cause a layout problem however (hotkeys no longer visible without horizontal scrolling): 
 F4 cycle-values glsl-shaders s/bw.hook s/bw-4.hk s/sepia_paint-4.hk ""

Commands much longer than this are possible, so it is seems necessary to shorten the displayed command if it is too long or place the hotkeys first.

**Comment by stax76** [comment]
OK, thanks for the feedback, it might take some days.
