### ISSUE TITLE
please add extension mpc to audio types

### ISSUE THREAD

**Issue by 44vince44** [stax76/mpv.net#233]
Hi Stax76, please consider simply adding the extension mpc to audio types.
It is a rare format, but is in use, and few players decode it.

**Comment by stax76** [comment]
Hello 44vince44,

nice to see somebody familiar around here. I think Dendraspis is not yet mpv convinced.

I've added it, but when people complain I might have to remove it again.

In case you have something even more rare there is the option `audio-file-extensionsstring`:

https://github.com/stax76/mpv.net/blob/master/Manual.md#--audio-file-extensionsstring

**Comment by 44vince44** [comment]
@stax76 Thanks!

Well I am convinced with mpv and especially mpv.net. I like very much what you did, to make mpv usable imho.
I use it as my main and only video player.
Also I have customized the menu to add a few image and color correction features...
