### ISSUE TITLE
Add a playlist panel similar to MPC-HC/BE and VLC

### ISSUE THREAD

**Issue by tanvir175** [stax76/mpv.net#235]
# **Is your feature request related to a problem? Please describe.**
Yes and no. I think this would be a good feature to have, regardless, but it does sort of solve a problem where the autoload script does not load files into the playlist in order. Here are some examples of the problem:

[Example 1](https://imgur.com/Y4rdjPU)
When I go into the folder, select all files, and drag and drop them into the player with my mouse cursor starting from the 1st episode, it will properly load all files in order.

When I drag the folder itself into the player, it will instead start with file 13.5, then go in order to file 38 and then loop back to file 1 and play until file 13. The expected behavior is that it should play all files in folder order 1-38. 

[Example 2](https://imgur.com/UzBWsDK)
Similar to Example 1, if I drag the files inside each inner folder, it will properly add to the playlist in order. However, if I try to drag the outer folder, it will add them randomly. The files get mixed up. 

# **Describe the solution you'd like**
I would like to see a playlist panel implemented. One just like [MPC-HC/BE](https://imgur.com/RUjXaEn) and [VLC](https://imgur.com/VSqP9nj) where you can drag the files onto the playlist panel and then reorder the files and add/remove files without redoing the entire playlist, if needed. 

# **Describe alternatives you've considered**
An alternative would just be to load them in one folder, at a time, for example 2. For example 1, the alternative is already there. Regardless, I think this is a good feature to have. As it is now, there is no way (that I know of) to drag one folder into the player and then drag a second separate folder into the player and have them be one single playlist. If I drag and drop a second set of files, it will start the new files immediately and remove the old files from the playlist.

**Comment by stax76** [comment]
Please I'm building here not a 90's styled noob player. There will be a brand-new command palette implementation used as playlist, the new command palette will look as nice as the command palette of Windows Terminal.

**Comment by tanvir175** [comment]
Do it however you'd like lol. I would just like a playlist that works as good as those 90's styled noob players because mpv currently does not. Thanks for the work you put into this project.

**Comment by stax76** [comment]
There is a new beta version addressing this issue.
