### ISSUE TITLE
vb.net WebRequest stream to mpv.net

### ISSUE THREAD

**Issue by 99bobster99** [stax76/mpv.net#236]
I'd like to send a WebRequest response stream into MPV.net, using VB.net. 

Is this possible? If so, do you have some sample code on how it should be done?

Trying this does not work, but this is the functionality I'm hoping for;

```
Dim responseReader As IO.StreamReader = New IO.StreamReader(response.GetResponseStream(), System.Text.Encoding.UTF8)
strResponse = responseReader.ReadToEnd()
player.Load(strResponse)    <- get error here, not a valid string
```

**Comment by stax76** [comment]
I don't think mpv.net has a method called load.
