### ISSUE TITLE
Option to disable image playback or only allow video files with auto-load-folder

### ISSUE THREAD

**Issue by parasiteoflife** [stax76/mpv.net#237]
**Is your feature request related to a problem? Please describe.**
When playing video files the images within the same folder are automatically played by mpv.net when auto-load-folder is enabled.

**Describe the solution you'd like**
It would be great to have an option to disable image playback entirely or an option to only load files of the same type with auto-load-folder so when we open a video file only other video files are played automatically.

**Comment by butterw** [comment]
This feature is available in the test build. 
https://forum.doom9.org/showthread.php?p=1937662#post1937662

**Comment by parasiteoflife** [comment]
Yes, it's working great.
