### ISSUE TITLE
Aspect ratio preserving is broken for mixed-DPI multiple monitor setups

### ISSUE THREAD

**Issue by kg** [stax76/mpv.net#238]
**Describe the bug**
I have a dual-monitor setup where one panel is 4K with a windows 10 scale setting of 150%, and the other panel is a 1440p monitor with a scale value of 100% (both of these are Windows' 'recommended' values for the monitors).
On the 4K panel (my main display), MPV.net accurately resizes video content to fill the window on all sides, so there are no black bars. If I drag the window over to the 1440p panel, however, once I resize the window there will always be black bars at the top and bottom no matter what I do. If I resize the window once on the 4k monitor and then drag it over, it will maintain its current size (and lack of black bars) but the moment I touch its size to adjust it, I get the bad black bars again. I suspect this is because the size of the system chrome (title bar, etc) varying between monitors is not being factored in to mpv.net's size calculations. 

**To Reproduce**
1. Open a video on a mixed-DPI setup with mpv.net on the highest scale monitor
2. Resize the window, observe MPV.net trying to preserve aspect ratio and size the window appropriately
3. Drag the window to another monitor with a lower scale value
4. Resize the window, observe black bars

**Expected behavior**
The automatic sizing should never produce black bars if it's enabled

**Screenshots**
Here is the window on my main display:
![image](https://user-images.githubusercontent.com/198130/115630337-b5a36a80-a2b8-11eb-8bac-3431308b96ad.png)
And here is the window once I drag it to my other display and resize it by one pixel (notice the title bar is smaller due to the OS scaling the chrome, and the black bars have appeared):
![image](https://user-images.githubusercontent.com/198130/115630377-c81da400-a2b8-11eb-8028-80fc26c77298.png)

**Additional context**
I'd also be happy with an option to disable the automatic sizing, since I don't actually want it. But it was a little surprising to discover that it also wasn't working right.

**Comment by stax76** [comment]
This is fixed but not yet uploaded. It was difficult to fix.

**Comment by kg** [comment]
Thank you very much for the effort!

**Comment by stax76** [comment]
New release is online.
