### ISSUE TITLE
Crashed with latest libmpv

### ISSUE THREAD

**Issue by nkh0472** [stax76/mpv.net#239]
**Describe the bug**
Usually, download the latest libmpv from the [official binary distribution of libmpv](https://sourceforge.net/projects/mpv-player-windows/files/libmpv/) and replace the mpv.net's mpv-1.dll. The program can run normally. However, when I replace the file with the latest build (mpv-dev-i686-20210404-git-dd86f19), the mpvnet.exe crashed with no warning when open it. 
Using mpvnet.com instead to try to find a further warning. However, the console window kept blanked, and the GUI window crashed without any info.
Using Dnspy 6.1.8 to try to debug. However, there is no warning/info either.

**To Reproduce**
1. Download & unpack [mpv.net-portable-x64-5.4.8.0.7z](https://github.com/stax76/mpv.net/releases/download/5.4.8.0/mpv.net-portable-x64-5.4.8.0.7z)
2. Download & unpack [mpv-dev-i686-20210404-git-dd86f19.7z](https://versaweb.dl.sourceforge.net/project/mpv-player-windows/libmpv/mpv-dev-i686-20210404-git-dd86f19.7z)
3. Replace mpv-1.dll in .\mpv-dev-i686-20210404-git-dd86f19 to .\mpv.net-portable-x64-5.4.8.0
4. Start mpvnet.exe, the program crashed without any info
5. Start mpvnet.com, the program crashed without any info

**Additional context**
Libmpv became incompatible since [mpv-dev-x86_64-20210316-git-5824d9f](https://iweb.dl.sourceforge.net/project/mpv-player-windows/libmpv/mpv-dev-x86_64-20210316-git-5824d9f.7z). 
[mpv-dev-x86_64-20210228-git-d1be8bb](https://pilotfiber.dl.sourceforge.net/project/mpv-player-windows/libmpv/mpv-dev-x86_64-20210228-git-d1be8bb.7z) works well with mpv.net 5.4.8.0.

**Comment by stax76** [comment]
It should work when you remove the included js file.

https://github.com/shinchiro/mpv-winbuild-cmake/issues/112

https://github.com/mpv-player/mpv/issues/8667

**Comment by nkh0472** [comment]
> It should work when you remove the included js file.
> 
> [shinchiro/mpv-winbuild-cmake#112](https://github.com/shinchiro/mpv-winbuild-cmake/issues/112)
> 
> [mpv-player/mpv#8667](https://github.com/mpv-player/mpv/issues/8667)

Useful information. Tkx!

**Comment by nkh0472** [comment]
Confirm [mpv-dev-x86_64-20210509-git-ea89e81](https://sourceforge.net/projects/mpv-player-windows/files/libmpv/mpv-dev-x86_64-20210509-git-ea89e81.7z/download) fixed this problem.
