### ISSUE TITLE
Feature Request: Allow only one instance

### ISSUE THREAD

**Issue by stefannitsche** [stax76/mpv.net#24]
First of all thank you for a wonderful application. The only thing I feel I'm missing at the moment is an easy way  reuse the already open instance. So that when you open a new file from Explorer it opens in the already started instance, either by replacing the currently open/playing file or by queuing it up.

**Comment by stax76** [comment]
Thanks for the feedback. I'll research it and add it if it's easy, clean, simple and fast enough, chances are good I guess.

**Comment by stax76** [comment]
In the next release you will be able to choose from:

-multi
-replacing
-queuing

Again, Thanks for the feedback!

**Comment by stefannitsche** [comment]
Man, you're awesome! I'm really looking forward to the next release.

**Comment by stax76** [comment]
The new release is available.
