### ISSUE TITLE
OSC Visibility = never; by default.

### ISSUE THREAD

**Issue by yontekh** [stax76/mpv.net#240]
Hello! This player is PERFECT for my use-case, thanks so much. I got really fed up with VLC and MPV.

Question:
Is there a way to hide the OSC on startup? without needing to toggle it manually by pressing a button.
Either a command-line parameter or setting in the config file would work for me.

I would really love this feature.

**Comment by 44vince44** [comment]
Yes there is a way to do that already, edit the mpv.conf file and place inside it:

`script-opts = osc-visibility=never`

if there is already a script-opts line then just append at the end of it, with comma separations:
`script-opts = osc-scalewindowed=1.2,osc-hidetimeout=2000,console-scale=1,osc-visibility=never`

This is a feature from original mpv, you can learn much there: https://mpv.io/manual/master/

**Comment by stax76** [comment]
Thanks @44vince44
