### ISSUE TITLE
How to disable window resizing?

### ISSUE THREAD

**Issue by parasiteoflife** [stax76/mpv.net#241]
Every time I open a video file the window resizes to the 60% of the resolution of said file, then if I open another video it resizes again. How can I do so mpv doesn't do that and preserves the window size it started with? I don't mind seeing black bars I just don't want the window to be resized at all.

**Comment by stax76** [comment]
This is supported in the next release.

https://github.com/stax76/mpv.net/blob/master/docs/Manual.md#--start-sizevalue

**Comment by parasiteoflife** [comment]
Thanks. But just to have it more clear. I can see the option in the config editor and it works well if I edit it manually and enter `width-always` or `height-always` but if I enter `always` the window size changes when it -as far as I understand reading the manual- shouldn't change at all.

Please, release a new beta with the new function.

**Comment by stax76** [comment]
It will be available in 5.4.9.0, I will try to upload it soon.

**Comment by stax76** [comment]
New release is online.
