### ISSUE TITLE
auto-load-folder should be off by default

### ISSUE THREAD

**Issue by asianmusicguy** [stax76/mpv.net#242]
For single files automatically load the entire directory into the playlist. Can be suppressed via shift key. (mpv.net specific setting)

this setting should  be off by default im sure many users do not want to play a single file then have it load everything after it

 i was very confused what happening when i played my first file and it started cycling through everything on the drive after install

**Comment by asianmusicguy** [comment]
it makes sense for image files but not video most people i think  use it for video only  well it could make sense if videos are well sorted and episodic, but if you're watching a movie you generally don't want another right after
so this is somthing that should be off until users want it on depending on use case

**Comment by stax76** [comment]
I think `auto-load-folder=yes` is a good default. It can easily be found by searching the config editor or the manual.
