### ISSUE TITLE
Make video rotation available by default in context menu

### ISSUE THREAD

**Issue by Oggom** [stax76/mpv.net#245]
**Is your feature request related to a problem? Please describe.**
It is currently not possible to rotate a video using mpv.net's GUI. I think it would be a useful feature to have.

**Describe the solution you'd like**
Add an option to rotate the video to the context menu.
For example: Right Click -> Video -> Rotate 90° Clockwise/Rotate 90° Counterclockwise

**Describe alternatives you've considered**
My current solution was to add the following keybindings to input.conf:

Alt+RIGHT add video-rotate 90
Alt+LEFT add video-rotate -90

**Additional context**
Thank your for efforts. mpv.net has become my video player of choice over the recent years!

**Comment by butterw** [comment]
In mpv.net the context menu is also customizable:
Alt+RIGHT add video-rotate 90 #menu: View > Window >Rotate

**Comment by bitsper2nd** [comment]
Like @butterw wrote before. This is a non-issue. You can add it easily in the input configuration. Simply copy/paste this line:
` alt+r      no-osd cycle-values video-rotate 90 180 270 0 #menu: View > Rotate Video`
Feel free to alter this in accordance to the keybinding and context menu entry you want.

**Comment by Oggom** [comment]
Of course it's not an "issue" per se, it's about making mpv's playback features more accessible to people through the GUI. The aim of mpv.net is to add a modern Windows interface on top of mpv in order to provide a more user-friendly experience. Editing config files is always an option but it's not something the average user would be willing to do.

**Comment by bitsper2nd** [comment]
Then I suggest to close this issue. mpv.net has a input editor GUI already.

**Comment by butterw** [comment]
- You should change your feature request to: 
Make video rotation available **by default** in context menu.

I would agree that having good programs defaults is important to many new/casual users.

**Comment by bitsper2nd** [comment]
@Oggom, you can use my [keybindings](https://github.com/stax76/mpv.net/files/6533951/input.zip) . I made it so mpv.net feels more like the video player used in youtube and Netflix. It is more accessible. You can learn the shortcuts, use them from the command palette or simply the context menu.

**Comment by stax76** [comment]
It was a lot of work.

I'll upload a new release supporting it this week.

**Comment by Oggom** [comment]
Thank you very much for your work!
