### ISSUE TITLE
Is it possible to add the rating extension to a regular mpv build?

### ISSUE THREAD

**Issue by millysecurity** [stax76/mpv.net#246]
What would I need to do to go about adding it to a regular mpv build? If it's too difficult of a process I understand but it's a really neat feature.

Also, the reason I even came across this repo is because on my mpv build I have 
`MBTN_FORWARD frame-step`
but the issue I'm having is that it sometimes jumps more than one frame forward. I tried this same input using mpv.net but if I push the mbtn_forward too many times it'll jump 5-6 frames forward. I tried fixing this using logitech g-hubs macros but it seems no matter what MPV always wants to ignore the delay and jump more than one frame. Thoughts on fixing this?

**Comment by stax76** [comment]
It's implemented in C#, so not mpv compatible.

In the future if it's possible and not too hard I will try to write everything in a way so that it is mpv compatible.

If I have time I make existing functionality mpv compatible.

**Comment by stax76** [comment]
Script is now available for mpv:

https://github.com/stax76/mpv-scripts
