### ISSUE TITLE
Default subtitle selection does not work correctly

### ISSUE THREAD

**Issue by FCrane** [stax76/mpv.net#247]
Hi!

When an MKV file contains several audio and subtitle tracks, mpv.net should correctly select the tracks that have the "Default" flag set. This seems to work mostly, but if no subtitle track has the "Default" flag, no subtitle should be shown. However, if there is any subtitle (even in a different language than the selected audio), the player will select the forced subtitle. This is an unwanted behavior! E.g. if an MKV contains audio tracks in English (Default) and German and subtitle tracks German and German Forced, mpv.net will play the English audio and show the German Forced subtitle by default, which is obviously incorrect! Since no subtitle track has the "Default" flag set, no subtitle should be shown by default.

I hope this can be fixed, because otherwise it's very inconvenient...

Thanks!

**Comment by stax76** [comment]
That is mpv and not mpv.net specific.

**Comment by FCrane** [comment]
No, it works correctly in mpv.

**Comment by stax76** [comment]
I don't understand it the way you described it, I think it's not described very well, and it would surprise me if mpv behaves differently.
