### ISSUE TITLE
cannot show console

### ISSUE THREAD

**Issue by hooke007** [stax76/mpv.net#249]
**Describe the bug**
The git version `45d3386` cannot show console
(However, the 5.4.8.0 release version can show)

**To Reproduce**
1.click the console key
2.nothing appeared. But I know it works, because I input the "seek 5" and it worked as what I expected. It just didn't show console.

**Expected behavior**
show console

**Screenshots**
![git-ty](https://user-images.githubusercontent.com/41094733/119037611-cb559e00-b9e4-11eb-8acb-9fbddffaec90.jpg)
![release-ty](https://user-images.githubusercontent.com/41094733/119037619-cd1f6180-b9e4-11eb-9304-9f6eb8eb1a22.jpg)

**Additional context**
No.

**Comment by hooke007** [comment]
I found that,
https://github.com/stax76/mpv.net/blob/45d3386a88f0ad888ab178158d1dc75cc560fcf7/src/Resources/mpv.conf.txt#L9

But in my device, `console-scale` was automatically replaced to 0 instead.

**Comment by stax76** [comment]
Thanks for reporting, it was a regression that happened fixing #238, now both fixed.
