### ISSUE TITLE
mpv.net opens first file in folder

### ISSUE THREAD

**Issue by TETYYS** [stax76/mpv.net#25]
mpv.net randomly opens first file in folder (sorted in ascending order by name) despite user clicking on some other file. Most of the time it opens files fine, sometimes you get the first file, not sure what causes this.

Doesn't happen if file is dragged into already open player

**Comment by stax76** [comment]
It never occurred to me, please let me know if you find a way to make it reproducible.

**Comment by TETYYS** [comment]
If `mp.commandv("loadfile", file, "append")` is asynchronous, [here](https://github.com/stax76/mpv.net/blob/63ee598ebdcc990d1f976bc669b341ec65be76d6/mpv.net/mpv/mp.cs#L560) might be a race condition happening.

**Comment by stax76** [comment]
Could be, I'll study the API, find it here:

https://github.com/mpv-player/mpv/blob/master/libmpv/client.h

**Comment by stax76** [comment]
I checked the api, it says async calls end with _async, mpv.net does not use any _async calls.

What I probably will be able to do is add a debug-mode which implements an alternative implementation for the Load function and also for the other issue with user input.

**Comment by stax76** [comment]
I tried an alternative implementation today, it's very simple, the code only works when using sleep so there must be a problem in libmpv.

```
            mp.commandv("stop"); // clears the playlist
            Thread.Sleep(50);
            foreach (string file in files)
                mp.commandv("loadfile", file, "append");
            Thread.Sleep(50);
            mp.set_property_int("playlist-pos", 0); // starts playback at pos 0
```

**Comment by TETYYS** [comment]
Just to note, I'm not saying this is definetely multithreading issue - it's just the first thing that came to mind

**Comment by stax76** [comment]
I was able to rewrite it, I think it's much better.

old: https://github.com/stax76/mpv.net/blob/63ee598ebdcc990d1f976bc669b341ec65be76d6/mpv.net/mpv/mp.cs#L560

new: https://github.com/stax76/mpv.net/blob/9f6aba6cbdf6368bf4da7b69ec1b1257b5aa52e8/mpv.net/mpv/mp.cs#L563

**Comment by TETYYS** [comment]
Still happens, but it's much rarer.

**Comment by stax76** [comment]
I've committed a change that might fix it, I believe it's a race condition in libmpv, it's difficult to find the root cause because the mpv developers don't work with my C# code. Last time I tried to reproduce a race condition with JavaScript without success.

https://github.com/stax76/mpv.net/blob/master/mpv.net/mpv/mp.cs#L577

**Comment by TETYYS** [comment]
Well, I don't seem to be able to reproduce it since that commit. I guess that could be a bypass until a proper fix.
