### ISSUE TITLE
Mpv command `window-scale` does not work with 5.4.8.9 beta

### ISSUE THREAD

**Issue by TheBestPessimist** [stax76/mpv.net#251]
**Describe the bug**
I have set in my keybindings the following:

<kbd>ctrl</kbd>+<kbd>=</kbd>:     `View > Window Size > Enlarge`        `set window-scale 1.04`

to increase the window size by "a little".
Similar keybinding for decreasing window scale:

![image](https://user-images.githubusercontent.com/4482210/119248097-8a51bb00-bb97-11eb-9134-b0e98a761544.png)

**To Reproduce**

Press <kbd>ctrl</kbd>+<kbd>=</kbd>:   

**Expected behavior**
I expect the command `window-scale` to change the dimensions of the mpv.net window.

**Additional context**

In beta 5.4.8.9. this command no longer works. With last mpv.net stable version, it works.

I have also tried to `add` to `window-scale`, but that doesn't work either: `add window-scale 1.04`.

**Comment by hooke007** [comment]
Because developer removed the support for it.
```
- There is an issue with the `window-scale` mpv property, it does not
  work correctly in mpv either, so I've removed support for it and
  added my own implementation `script-message mpv.net window-scale`.
```

**Comment by TheBestPessimist** [comment]
@hooke007 thank you for the help. 
You are right!


The command for resizing window is `script-message mpv.net scale-window 1.04`


Ref: https://github.com/stax76/mpv.net/blob/b1388e10e59dddf1a36d37800e4bd0264bd34a33/src/Resources/input.conf.txt#L135

**Comment by stax76** [comment]
`scale-window` doesn't work properly in mpv, play file with mpv.exe and set:

set scale-window 1

It does not work because the event don't fire, somebody should report it.

**Comment by hooke007** [comment]
> `window-scale 1` does not work correctly in mpv

Hmm...In fact It can be avoid easily.
But the no support for window-scale make me impossible to find the current scale factors in the stats lists.
