### ISSUE TITLE
Setup function cannot work in the git version (5.4.8.9)

### ISSUE THREAD

**Issue by hooke007** [stax76/mpv.net#252]
**Describe the bug**
`make shortcut, File association and add environment variable` do not work.

**To Reproduce**
Just click the button.

**Expected behavior**
I can see the window message tell me it succeeded.

**Screenshots**
A window quickly flashed and then nothing happened.

**Additional context**
No.

**Comment by hooke007** [comment]
![Snipaste_2021-05-24_13-46-34-ty](https://user-images.githubusercontent.com/41094733/119302464-bbfd7b80-bc96-11eb-87b4-80596ae285c7.jpg)

The screenshot I caught may be help with it.

**Comment by stax76** [comment]
Which button exactly does not work?

**Comment by hooke007** [comment]
![Snipaste_2021-05-24_17-26-08](https://user-images.githubusercontent.com/41094733/119327094-31784480-bcb5-11eb-89fd-7d34e1b01e6b.jpg)

All the buttons in the red area.

**Comment by stax76** [comment]
It's because the buttons invoke PowerShell scripts you don't have.
