### ISSUE TITLE
About theme.conf

### ISSUE THREAD

**Issue by hooke007** [stax76/mpv.net#254]
1. ![Snipaste_2021-05-27_01-30-58](https://user-images.githubusercontent.com/41094733/119713776-ac4b8600-be94-11eb-8ff9-0999e7001d25.jpg)
Sorry, I don't know that these codes in the `theme.conf` will change which buttons.

2. <s>I checked the **https://github.com/stax76/mpv.net/issues/14** but it cannot work in the latest git.</s>
It worked after I restarted the system...

**Comment by bitsper2nd** [comment]
You want to change the color and fonts in the OSC as in the minimal gui in mpv? Or do you want to change mpv.net's own gui?

A = mpv osc
![preview](https://user-images.githubusercontent.com/22452474/119721132-2d792d80-be41-11eb-8dff-c28e96e94221.png)


B = mpv.net
![ConfEditor](https://user-images.githubusercontent.com/22452474/119721010-04f13380-be41-11eb-8266-63fe6ef7eff8.png)

**Comment by hooke007** [comment]
Two things you described are not related.
I just wonder these codes link to which buttons.

**Comment by stax76** [comment]
> Sorry, I don't know that these codes in the theme.conf will change which buttons.

I remember I've worked on it recently but already have forgotten it 🙁, these properties seem to be orphaned, will be removed in the next commit.
