### ISSUE TITLE
Two issues about input editor (5.4.8.9)

### ISSUE THREAD

**Issue by hooke007** [stax76/mpv.net#255]
**Describe the bug**
bug1.add the new item by `input editor`, it will copy the previous all items to into the input.conf
bug2.`Learn input` cannot receive `CTRL+ALT+a` this kind of bindings.

**To Reproduce**
For bug1, just do as the description and check the input.conf, you'll see much more codes was added.
For bug2, open the Learn input and try any `CTRL+ALT+a/b/c/....`, no response.

**Expected behavior**
1. Only add the items user add.
2. user can bind this kind of keys by `Learn input`.

**Screenshots**
![Snipaste_2021-05-28_21-03-16](https://user-images.githubusercontent.com/41094733/119988025-3c561080-bff8-11eb-82f2-30e73bbf9675.jpg)
Also, it will lead that menu looks strange.

**Additional context**
For bug2, users can directly edit the `input.conf` and see it works well in mpv.net.

**Comment by stax76** [comment]
Both not reproducible here.

1. Is possibly your text editor doing this.

2. On my Western/German keyboard ctrl+alt is the same as alt gr, it's used by certain characters like ~ Tilde and works here for both ctrl+alt and also alt gr.

**Comment by hooke007** [comment]
B1. (Tested by latest git) It cannot be, I didn't use the text editor to open input.conf file before I found the strange context menu. I will test in more devices to check.
B2.Sorry no Western/German keyboard , I just use the universal 104 keyborad. And a new finding: some words will have reaction, but what it shows is not what I expected. For example, `ctrl+alt+a` shows
![Snipaste_2021-05-29_02-37-25](https://user-images.githubusercontent.com/41094733/120028317-1eec6b00-c027-11eb-9c23-144b52d5a0c3.jpg)

**Comment by stax76** [comment]
That is normal because Windows handles ctrl+alt same as alt gr.

**Comment by hooke007** [comment]
B1. The version built by myself always reproduce this problem. Too confused.
B2. It seems no way to handle this?

**Comment by Xianglos** [comment]
hi bro, It seems like, i had the same problem
bug1
