### ISSUE TITLE
5.4.9.0 error message: RatingExtension 

### ISSUE THREAD

**Issue by ll811** [stax76/mpv.net#256]
Launching mpvnet gives this error message every time. 

![Clipboard03](https://user-images.githubusercontent.com/54498049/120067696-42420500-c07d-11eb-8e07-7b3bad25b551.jpg)

**Comment by bitsper2nd** [comment]
temporary solution is to move or delete the extensions folder in mpv.net

**Comment by stax76** [comment]
I have forgotten to disable extensions being loaded from the startup directory, that feature will be removed in the next build.

It reveals however that you overwrote the files of an old version with files of a new version, that is generally not a good idea, it can lead to problems as you just learned.

**Comment by ll811** [comment]
> It reveals however that you overwrote the files of an old version with files of a new version, that is generally not a good idea, it can lead to problems as you just learned.

I just updated it. Am I supposed to remove it before installing newer versions?

**Comment by stax76** [comment]
I've disabled now extensions from being loaded from the startup directory, they are now only loaded from the settings directory like scripts. So this issue cannot happen in the next release.

And I've improved the manual:

> An old version should be uninstalled before installing a new version,
> it's generally not a good idea to install a new version on top of an old version,
> the setup don't enforce it because it's not easy to implement.
