### ISSUE TITLE
Portable config not working?

### ISSUE THREAD

**Issue by 1024mb** [stax76/mpv.net#258]
I have an instance of mpv.net installed and now I want to use another instance in portable mode so I can have two configurations.
I've extracted the portable package and created the directories `Startup\portable-config` and copied the config of the installed instance but every time I start the portable instance and use `Ctrl+F` to go to the configuration folder it sents me to `%APPDATA%\mpv.net` so it is not using the portable configuration.  

What I'm doing wrong here?
The mpv.net portable directory looks like this:

```
\mpv.net
			\ startup
						\ portable_config
											\ < ---- HERE ARE THE COPIED CONFIG FILES ---- >
```

**Comment by hooke007** [comment]
`portable_config`

Not portable-config

**Comment by 1024mb** [comment]
Oh, yes, I misspelled, I have it like `portable_config`. Can you test it? It is working in your end?
Just to remark this: I have an installed instance and I'm executing another instance in portable mode. I'm on Windows 10.

**Comment by hooke007** [comment]
I just use `portable_config` since I started to use mpv.

**Comment by 1024mb** [comment]
Maybe the issue has something to do with mpv.net first searching for the config on `%APPDATA%` instead of `.\startup/portable_config`?

**Comment by hooke007** [comment]
If you want to use the global settings (%APPDATA%) rather than personal setting, why not delete the `portable_config` folder?

**Comment by 1024mb** [comment]
No, the issue is the opposite. I want to use the portable configuration instead of mpv.net using the AppData one.
The installed instance is using the AppData as it should, but my portable instance is also using the AppData configuration instead of the portable one.

**Comment by hooke007** [comment]
I have said that ——

> `portable_config`
> 
> Not portable-config

start-up is not the folder name. It means the directory where mpvnet.exe located.

**Comment by 1024mb** [comment]
I thought we had to make an startup folder lol. But seriously the wording was a little confusing, the thought of `startup` meaning the mpv.net root directory didn't cross my mind at all. I suggest you change `startup` for `mpv.net root directory`.

I've tested this and of course is working.
Thanks for your help!
