### ISSUE TITLE
Context menu font does not appear properly.

### ISSUE THREAD

**Issue by KaranKad** [stax76/mpv.net#259]
**Describe the bug**
Font in context menu does not appear properly

**To Reproduce**
1. Install mpv.net
2. Open a video in it
3. Right click to see context menu
4. See font

**Expected behavior**
I expect the font to look like this
![image](https://raw.githubusercontent.com/stax76/mpv.net/master/docs/img/Menu.jpg)

**Screenshots**
As you can see, font renders poorly compared to the one in **Expected behavior**
![image](https://user-images.githubusercontent.com/71691514/120105654-81548100-c177-11eb-90fd-0a7a4892cf2a.png)

**Additional context**
I have a 1366x768 display with scaling set to 100%
Windows version 21H1
Font at every other place appears fine

**Comment by stax76** [comment]
Please try:

[mpvnet.zip](https://github.com/stax76/mpv.net/files/6566347/mpvnet.zip)

**Comment by stax76** [comment]
If possible also try how menu fonts of staxrip look.

**Comment by stax76** [comment]
Here is a second build you can try:

[mpvnet2.zip](https://github.com/stax76/mpv.net/files/6566374/mpvnet2.zip)

**Comment by KaranKad** [comment]
First exe didn't work, the second one worked, thanks for your help
![image](https://user-images.githubusercontent.com/71691514/120108814-62a8b700-c184-11eb-8594-87d7f39f5e30.png)

**Comment by KaranKad** [comment]
StaxRip doesn't have this issue.
![image](https://user-images.githubusercontent.com/71691514/120109567-9c2ef180-c187-11eb-98f7-98ae6ce8bc13.png)
![image](https://user-images.githubusercontent.com/71691514/120109614-c41e5500-c187-11eb-8ee0-0af9cc29363b.png)

**Comment by stax76** [comment]
There is a new beta version addressing this issue.
