### ISSUE TITLE
CompositionException error at startup

### ISSUE THREAD

**Issue by ze0ss** [stax76/mpv.net#261]
Just installed v5.4.9.0 portable, and double clicked it, and I got this error as soon as the app opened.
Previously I had v5.4.8.8 portable, beta, no such error occured.

![wdrycUT](https://user-images.githubusercontent.com/56572179/120262970-650c2d80-c2b8-11eb-89f5-827fc8432ecb.jpg)

**Comment by hooke007** [comment]
duplicate https://github.com/stax76/mpv.net/issues/256

**Comment by ze0ss** [comment]
@hooke007 ok but I deleted the Extensions folder but still the player can't play videos.

**Comment by acotor** [comment]
Same error occurs every time on startup. Application still runs background and this can be ignored.
![image](https://user-images.githubusercontent.com/22100376/122322743-8c215b00-cf58-11eb-8fa3-444be90b1405.png)
Version: 5.4.9.0 (Upgrade via Chocolatey)
OS: Windows 10 21H1 19043.1055

**Comment by hooke007** [comment]
So why not fullclean? the error message shows the previous files occurs this problem.
https://github.com/stax76/mpv.net/issues/256#issuecomment-850979752
