### ISSUE TITLE
mpv_thumbnail_script will not work with mpv.net

### ISSUE THREAD

**Issue by virendra531** [stax76/mpv.net#262]
https://github.com/marzzzello/mpv_thumbnail_script

**Comment by hooke007** [comment]
cannot reproduce here
![Snipaste_2021-06-06_16-13-16-ty](https://user-images.githubusercontent.com/41094733/120917512-4a83eb00-c6e2-11eb-806e-3f8f44e0d869.jpg)

**Comment by 1024mb** [comment]
If your problem is that no thumbnails are generated then you have to prefer ffmpeg over mpv, I had the same issue and changing that solved it.

**Comment by virendra531** [comment]
> 
> 
> If your problem is that no thumbnails are generated then you have to prefer ffmpeg over mpv, I had the same issue and changing that solved it.

Didn't solve my problem

MY MPV https://mega.nz/file/MOgFwKwK#WSDpy4aR0Jxahi-LT77hXr9U1VTbJbJUwAw-RdceMNk

**Comment by 1024mb** [comment]
> 
> 
> > If your problem is that no thumbnails are generated then you have to prefer ffmpeg over mpv, I had the same issue and changing that solved it.
> 
> Didn't solve my problem
> 
> MY MPV [mega.nz/file/MOgFwKwK#WSDpy4aR0Jxahi-LT77hXr9U1VTbJbJUwAw-RdceMNk](https://mega.nz/file/MOgFwKwK#WSDpy4aR0Jxahi-LT77hXr9U1VTbJbJUwAw-RdceMNk)

The configuration file for the script should be inside the `portable_config` folder in a directory named `script-opts`.

**Comment by hooke007** [comment]
>Didn't solve my problem

You didn't set the files at the correct place. https://mpv.io/manual/master/#files-on-windows
when using `portable_config`, itself is the only config directory.

**Comment by virendra531** [comment]
putting both `script-opts` `scripts` folder into `portable_config` and setting `prefer_mpv=no` solved my problem.

**Comment by hooke007** [comment]
Quote the reason there.
https://github.com/marzzzello/mpv_thumbnail_script/issues/2#issuecomment-862305285

**Comment by 1024mb** [comment]
> 
> 
> Quote the reason there.
> [marzzzello/mpv_thumbnail_script#2 (comment)](https://github.com/marzzzello/mpv_thumbnail_script/issues/2#issuecomment-862305285)

In my case mpv has always been in PATH and it didn't worked.

**Comment by hooke007** [comment]
`prefer_mpv` means call for `mpv.exe` to encoding and generate the thumbnails, if it cannot work, you'd better report to the script author with logs.
