### ISSUE TITLE
Random Composition Exception

### ISSUE THREAD

**Issue by leochras** [stax76/mpv.net#266]
**Describe the bug**
Unclear error message after opening any video or even without opening anything.

**To Reproduce**
1. Open MPV.net
2. See error

**Expected behavior**
No error message

**Screenshots**
![image](https://user-images.githubusercontent.com/16163571/121514059-e0be5680-c9eb-11eb-8e21-5b85ce65f4e4.png)

**Additional context**

**Comment by leochras** [comment]
Is there a way for me to provide log files? I am on Windows 10 Pro 21H1.

**Comment by hooke007** [comment]
https://github.com/stax76/mpv.net/issues/256
fullclean and reinstall.

**Comment by leochras** [comment]
full cleaning all files was the solution
