### ISSUE TITLE
Exception when playing from a named pipe

### ISSUE THREAD

**Issue by Celuni** [stax76/mpv.net#268]
Exception when playing from a named pipe after update from 5.4.8.0
Current version: 5.4.9.0
![Image](https://i.imgur.com/BVM6SDH.png)

**Comment by stax76** [comment]
Sorry, I don't know how to reproduce this because named pipes is not something that I've used often. Please fill out the issue template...

**Comment by Celuni** [comment]
I'm using [Streamlink Twitch GUI](https://github.com/streamlink/streamlink-twitch-gui) which is a GUI that easily handles [Streamlink](https://github.com/streamlink/streamlink) which can created named pipes for video streaming, it can also directly write to stdin which works flawlessly.
The exception from the screenshot comes only when using named pipe option, my guess is that the pipe is empty and thus mpvnet throws.

**Comment by stax76** [comment]
There is a new beta version addressing this issue.
