### ISSUE TITLE
Update checker sometimes fails to parse whatever update information it gets from the server

### ISSUE THREAD

**Issue by kg** [stax76/mpv.net#269]
**Describe the bug**
When I checked for updates in mpv.net it failed with an ArgumentException and it seems to fail every time

**To Reproduce**
1. Right-click mpv.net window
2. Help -> Check For Updates
3. 'ArgumentException

Version string portion was too short or too long.

   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at mpvnet.UpdateCheck.<CheckOnline>d__1.MoveNext() in D:\Projekte\CS\mpv.net\mpv.net\Misc\UpdateCheck.cs:line 35'

**Expected behavior**
A message saying whether or not an update is available

**Screenshots**
![image](https://user-images.githubusercontent.com/198130/122576145-3b683b80-d006-11eb-816a-8312cd45413e.png)

**Additional context**
![image](https://user-images.githubusercontent.com/198130/122576207-4a4eee00-d006-11eb-886f-a6257ef0c3aa.png)
p.s. the about window closing the moment you hit a key makes it difficult to take a screenshot

Thanks for your hard work on the app! Sorry if this is a dupe, I did a search and didn't find any reports, and I don't expect you to fix it just thought you might want to know about it. Can easily just download a new build

**Comment by kg** [comment]
If it helps, installing 5.4.9.0 gives me an update checker that works fine (though I hit a different error which I'll file separately)

**Comment by hooke007** [comment]
duplicate https://github.com/stax76/mpv.net/issues/257#issuecomment-850974096
