### ISSUE TITLE
Can't choose mpv.net as default for Video and Audio playback on Windows 10

### ISSUE THREAD

**Issue by leochras** [stax76/mpv.net#275]
**Describe the bug**
In Windows Settings, when trying to set mpv.net as a default app, it doesn't show up

**To Reproduce**
1. Go to Settings --> Apps --> Default Apps
2. Click on "Videoplayer" or "Audioplayer"

**Expected behavior**
There should at least be an option in the installer to make it default.

**Screenshots**
![image](https://user-images.githubusercontent.com/16163571/123078622-71992700-d41b-11eb-8245-99dad4bedf7d.png)

**Additional context**
Windows 10 Pro 10.0.19043 Build 19043
mpv.net 5.4.9.0

**Comment by stax76** [comment]
mpv and mpv.net is a nerd player, it means you have to study the docs thoroughly, it requires deep technical understanding.

It should work if you open the setup dialog and register file extensions from there.

There are a couple of obstacles on purpose!

https://github.com/stax76/mpv.net/blob/master/docs/Manual.md

**Comment by leochras** [comment]
Guess it's not for me then.
Thanks anyways

**Comment by stax76** [comment]
You can try VLC and MPC-BE or MPC-HC, these are the most popular choices, PotPlayer is also popular.
