### ISSUE TITLE
Cannot force default display to open in

### ISSUE THREAD

**Issue by DReaper** [stax76/mpv.net#28]
I am running a dual monitor and mpv.net will always default to opening in the second display, no matter the value I put under Config > Screen. I inputted 0, 1, 2 and it will always open in the second monitor.

When I go full screen after moving the video to the primary display, and revert back to windowed, it moves the player back to the second display.

Vanilla mpv does not have this issue.

**Comment by stax76** [comment]
I'm sorry to hear that, I thought my implementation is solid.

Did you restart mpv.net?

Are you on Win 10? I'm on Win 10 1903.

My setup is first/primary PC and second/secondary TV, TV turned on only when I use it.

My mpv(.net) setting is screen=1, that is my TV, second/secondary

**Comment by DReaper** [comment]
I am on Windows 7. Mpv was restarted and Windows was restarted in case. As I mentioned, I tried different values for screen = x and it kept opening in the second display.

**Comment by stax76** [comment]
I'll investigate it but cannot promise much as I believe it's a Windows incompatibility.

**Comment by DReaper** [comment]
Thank you. I just find it weird that it is not an issue in vanilla MPV though.

**Comment by stax76** [comment]
I've uploaded a build here:

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/f/s!ArwKS_ZUR01gySQIE1QCL2i9F_uR

in the config dialog you will find a new setting 'debug-mode', if you enable this and restart mpv.net, it will create a debug log file on your desktop, please post the content.

**Comment by DReaper** [comment]
Screen[Bounds={X=2560,Y=0,Width=1920,Height=1080} WorkingArea={X=2560,Y=0,Width=1920,Height=1080} Primary=False DeviceName=\\.\DISPLAY1
Screen[Bounds={X=0,Y=0,Width=2560,Height=1440} WorkingArea={X=0,Y=0,Width=2560,Height=1392} Primary=True DeviceName=\\.\DISPLAY2
screen index a: 1
screen index b: 1

Player opened on the second display, I dragged it over to my primary, went fullscreen and back to windowed, where it went back to the second display.

**Comment by stax76** [comment]
I hope it's fine in [4.3.1](https://github.com/stax76/mpv.net/releases).

**Comment by DReaper** [comment]
Issue is resolved! What caused the bug?

**Comment by stax76** [comment]
There was a piece of code that was meant to ensure the window is in screen bounds, this had a bug because I made the wrong assumption that in the array of screens that the .net api provides, the first screen is always on the left side.
