### ISSUE TITLE
Allow the volume to go beyond 130%

### ISSUE THREAD

**Issue by Torvin** [stax76/mpv.net#282]
It would be nice to be able to increase the volume level beyond 130% or at least to allow the maximum volume level be configurable. Some videos are very quiet and 130% is just not enough.

The volume level is currently displayed with a "progress bar"-kind of indicator along with the number in the top-left corner. I guess we don't have to update the "progress bar" when the volume goes beyond 130% - this is the approach that VLC takes: you can increase the volume up to 200% but the indicator stays at 125%.

**Comment by hooke007** [comment]
add this option in your mpv.conf `--volume-max=<number>`

**Comment by Torvin** [comment]
Thank you! couldn't find it for some reason
