### ISSUE TITLE
Window size shortcuts (keyboard) not working

### ISSUE THREAD

**Issue by KeLLeYLeK** [stax76/mpv.net#283]
View > Window Size > Enlarge Alt (+) + / Shring Alt (+) - not working. Select this commands with mouse also not working.

**Comment by stax76** [comment]
You can recreate or manually update input.conf

```
 Alt++   script-message mpv.net scale-window 1.2     #menu: View > Zoom > Enlarge
 Alt+-   script-message mpv.net scale-window 0.8     #menu: View > Zoom > Shrink
```

https://github.com/stax76/mpv.net/blob/master/src/Resources/input.conf.txt#L137

**Comment by KeLLeYLeK** [comment]
Thanks for kind reply and this beautiful application.
