### ISSUE TITLE
Use of batch file to start mpvnet.exe

### ISSUE THREAD

**Issue by Trex187** [stax76/mpv.net#285]
Hello,

I'm attempting to have qbittorent start mpvnet.exe and play ten seconds of a sound file and then close as an alarm when all downloads are finished.  Mpv will start and play the correct file but it won't start at the time marker I set and it won't end either.  Instead it will play every file in the folder.  Am I using the right commands? Any help is appreciated.  Here is what I have in the batch file:
start "C:\Program Files\mpv.net\mpvnet.exe" "C:\Utilities\media\media\audio\ringtones\20_Simple_Beep_3.ogg" --no-resume-playback --start=00:10 --end=00:20

**Comment by hooke007** [comment]
I don't think mpv's options can work with `start`
```
"C:\Program Files\mpv.net\mpvnet.exe" "C:\Utilities\media\media\audio\ringtones\20_Simple_Beep_3.ogg" --no-resume-playback --start=00:10 --end=00:20
```

**Comment by Trex187** [comment]
> resume

Ok.  I removed start.  Now mpv will play the audi at the time marker and stop playing that file after 10 seconds but it will still jump to the next sound file in the directory and keep doing that until it reaches the end.   Any way to have it just play that one file and end itself?

**Comment by hooke007** [comment]
--keep-open=always

**Comment by Trex187** [comment]
Ok, that works.  Thank you.

**Comment by stax76** [comment]
Or you can prevent folder load on the command line:

`mpvnet --auto-load-folder=no`

Automatically closing after playback is currently not supported because `keep-open` isn't completely implemented, but will be supported in the next release:

`mpvnet --keep-open=no`
