### ISSUE TITLE
Missing licence

### ISSUE THREAD

**Issue by dsoronda** [stax76/mpv.net#287]
What is code license of MPV.NET ?
It would be nice to mention it in README file or licence.txt file.

Thanks.

**Comment by stax76** [comment]
The current version is MIT licensed.

The next version will be GPL v2, however.

I've just added a License.txt file to the code.

**Comment by dsoronda** [comment]
Thanks for quick replay. My next question is : what is last MIT licensed version ?

**Comment by stax76** [comment]
mpv.net was MIT licensed before, it's my preferred license.

The reason why I recently changed the license of mpv.net to GPL is mpv and ffmpeg are also GPL licensed.

Licenses is something I have little interest, however. I hope everything license related is clear now.

**Comment by dsoronda** [comment]
The reason I ask is : I'm planning to write cross platform GUI for MPV in C# and ETO Forms so I'm more interested in MIT license than GPL so I fork project and reset to latest MIT version.
