### ISSUE TITLE
Launching mpv.net produces an error every time it is launched. Does not seem to prevent video playback.

### ISSUE THREAD

**Issue by Rowsinator** [stax76/mpv.net#288]
**Describe the bug**
When opening any video file in MPV.net it produces this error. The video loads and plays just fine, and as long as the player is open, it won't display the error when a new video is opened, but this happens every time the program launches.

![image](https://user-images.githubusercontent.com/15205162/126879703-4363b2a0-4a61-48fa-a373-13da98cbd2c5.png)

**To Reproduce**
1. Open any video file in MPV.net
or
2. Open the program itself. 

**Expected behavior**
Launching the program should not produce an error.

**Additional context**
This seems to have happened out of the blue as I have made no changes to my system (No windows upgrades, etc). Re-installing the program did not fix my issue.

**Comment by hooke007** [comment]
There is no folder `Extensions` in mpvnet(v.5490).
duplicate https://github.com/stax76/mpv.net/issues/256
