### ISSUE TITLE
Feature Request: hover over progress bar to forward/backwards 10 sec using scroll wheel (like VLC)

### ISSUE THREAD

**Issue by 4hench** [stax76/mpv.net#29]

**Comment by stax76** [comment]
I agree it makes sense, many other apps use similar logic but I'm not sure I have control over it.

You can request it in the mpv tracker, meanwhile you can add following to your input.conf (next release has that included).

 Ctrl+Wheel_Up   no-osd seek  7
 Ctrl+Wheel_Down no-osd seek -7
