### ISSUE TITLE
Option for `no-keepaspect-window`

### ISSUE THREAD

**Issue by soredake** [stax76/mpv.net#291]
**Is your feature request related to a problem? Please describe.**
Would be nice to have gui option for this.

**Describe the solution you'd like**
Having option for this.

**Describe alternatives you've considered**

**Additional context**
Why this might be useful to some people (me included) is described here https://github.com/stax76/mpv.net/issues/123#issuecomment-824406792

**Comment by stax76** [comment]
`keepaspect-window` was implemented in mpv.net v5.4.9.1 Beta, are you maybe using an older version?

**Comment by hooke007** [comment]
I think his mean is ... add the option in the editor rather than write manually in the conf file

**Comment by stax76** [comment]
Sorry missed it. I can add it to the conf editor.

**Comment by soredake** [comment]
Thanks for adding this option! Now i can resize window how i want, but after going to fullscreen and out window size resets to video aspect ratio.

**Comment by stax76** [comment]
> Now i can resize window how i want, but after going to fullscreen and out window size resets to video aspect ratio.

This will be fixed in the next release.

**Comment by soredake** [comment]
> 
> 
> > Now i can resize window how i want, but after going to fullscreen and out window size resets to video aspect ratio.
> 
> This will be fixed in the next release.

Behavior change in latest beta, but it still unpins from corner after leaving fullscreen
https://user-images.githubusercontent.com/5204968/130430951-06c51d20-a80a-4362-bc93-b5d7fba95c35.mp4

**Comment by stax76** [comment]
Did you use Window snapping?

I will take a look this week.

**Comment by soredake** [comment]
> Did you use Window snapping?

Yes, that's was i meant by "pin".

**Comment by fhtdtdj** [comment]
Hi stax. No-keepaspect-window is also a feature I wanted, so thanks for implementing it!
I'm on  mpv.net 5.4.9.8 Beta, and when it's enabled, it not only resets size after toggling out of full screen, but also seems to cancel out remember-window-position:yes and/or start-size:always; the window doesn't remember size and resets to a different size on next starts. Using manual resizing, not automated snapping.

**Comment by stax76** [comment]
@soredake

Please try v5.4.9.9 Beta.


@fhtdtdj

Please try v5.4.9.9 Beta with autofit-larger=100


I hope it works and does not break anything else, Window features are very complex.

**Comment by soredake** [comment]
Changing item in playlist resets window size.

**Comment by stax76** [comment]
It happens when pinned, I'll investigate it.

**Comment by stax76** [comment]
It should work in v5.5.0.1 when using `start-size=always` combined with `keepaspect-window=no`.

Furthermore, `View > Zoom > Enlarge/Shrink` was fixed to support `start-size=always` combined with `keepaspect-window=no`.

**Comment by soredake** [comment]
@stax76 snapping is broken again in 5.5.0.3 and 5.5.0.4.

**Comment by stax76** [comment]
@soredake You have to enable `start-size=session`.

In the future the following will be supported too:

https://github.com/mpv-player/mpv/pull/9360

**Comment by soredake** [comment]
@stax76 thanks!
