### ISSUE TITLE
Shader in "gpu-api=vulkan" does't work

### ISSUE THREAD

**Issue by virendra531** [stax76/mpv.net#292]
Shader in "gpu-api=opengl" does work
i am using this
https://github.com/bloc97/Anime4K/blob/master/GLSL_Instructions.md

**Comment by hooke007** [comment]
I don't understand. it usually has no relationship with frontend.
Make sure no same bug in mpv, if exist too, report to mpv... maybe should report to a4k.

![Snipaste_2021-07-28_03-13-09](https://user-images.githubusercontent.com/41094733/127214271-2f41a5f7-968e-4274-84e2-5cf1991231fb.jpg)
No issue here.
