### ISSUE TITLE
Show playlist options does not work

### ISSUE THREAD

**Issue by vishaluchil** [stax76/mpv.net#293]
**Describe the bug**
The show playlist option does not work, either with the right-click menu or the shortcut.

**Steps to reproduce the behavior:**
1. Go to Right-Click>View>Show Playlist / Press F8
2. No output observed.

**Expected behavior**
A playlist with all files in folder shown with current playing file highlighted/ All files shown in a created playlist

**Additional context**
It is worth noting that I'm on a **Windows 11 insider build**, so it could be something with Windows 11. But also keep in mind that all other view options are working

**Comment by stax76** [comment]
Which mpv.net version do you use? There was a playlist related change in mpv.net v5.4.9.1 Beta.

**Comment by vishaluchil** [comment]
I'm using version 5.4.9.0

![image](https://user-images.githubusercontent.com/50170066/127357402-d4a4951a-6267-4fa2-8115-dedfecbb514a.png)

**Comment by formlessdao** [comment]
I can confirm it does not show the playlist. 
Where can the beta version you mentioned be downloaded?

**Comment by hooke007** [comment]
https://github.com/stax76/mpv.net#download

**Comment by stax76** [comment]
The new playlist UI is command palette based using these commands:

```
F8   script-message mpv.net show-playlist #menu: View > Show Playlist
F1   script-message mpv.net show-command-palette #menu: Command Palette
```

I've also a Win 11 partition, but so far I'm not using it a lot because I'm a little afraid the final version will need a fresh installation, causing me to lose a lot of configuration.

**Comment by formlessdao** [comment]
> 
> 
> The new playlist UI is command palette based using these commands:
> 
> ```
> F8   script-message mpv.net show-playlist          #menu: View > Show Playlist
> F1   script-message mpv.net show-command-palette   #menu: Command Palette
> ```
> 
> I've also a Win 11 partition, but so far I'm not using it a lot because I'm a little afraid the final version will need a fresh installation, causing me to lose a lot of configuration.

where is that beta version you mentioned above?

**Comment by hooke007** [comment]
> where is that beta version you mentioned above?

I've told you...check the link

**Comment by vishaluchil** [comment]
I've tried the beta version as well as a complete uninstall and reinstall. Still no sign of playlist being viewed

**Comment by hooke007** [comment]
> I downgraded to version **5.4.8.0** and it works perfectly. So, anyone facing this issue should do the same and wait for an update where this issue is fixed.

You gave me the inspiration.
A possible cause is that old version's mpvne config in `%appdata%`

**Comment by stax76** [comment]
Maybe it's an input.conf compatibility issue, an occasional exercise. Users have to either delete input.conf so mpv.net generates a new input.conf. Another way is updating input.conf manually, this is the recommended way but requires a little experience.

**Comment by 1024mb** [comment]
> Maybe it's an input.conf compatibility issue, an occasional exercise. Users have to either delete input.conf so mpv.net generates a new input.conf. Another way is updating input.conf manually, this is the recommended way but requires a little experience.

Can you tell me what should we change in the input.conf file? I'm using 6.0.3.0 and View-Show playlist does nothing.

**Comment by stax76** [comment]
The next release will be backward compatible to this key binding.
