### ISSUE TITLE
strange window position after `ver_5.4.9.1`

### ISSUE THREAD

**Issue by hooke007** [stax76/mpv.net#294]
**Describe the bug**
This bug exist in the 5492 I compiled and 5491 you provided in the onedrive. (release 5490 is OK)
Every time I start the mpvnet, the window position will change a little.
I used the default config.

**To Reproduce**
1. start the mpvnet
2. watch the position & exit
3. repeat the actions above

**Expected behavior**
window position won't change at the next start-up.

**Actual behavior**
The windows seems it could move from top-left to middle, about 10 times in one cycle.

Also, the function —— remember the window postion —— seems not work any more

**Comment by stax76** [comment]
I've committed a fix. If it's not working, I need enough details to be able to reproduce:

-Windows version
-Position of taskbar (usually bottom, I use left)
-For every active monitor resolution and DPI
-content of mpvnet.conf

**Comment by hooke007** [comment]
https://github.com/stax76/mpv.net/commit/e9b6988a6915fafcbccf85d26d0b92c4b548f720 Fixed. And remember-position also works.
