### ISSUE TITLE
How to decrease display frame rate to reduce CPU/GPU usage ?

### ISSUE THREAD

**Issue by pubpy2015** [stax76/mpv.net#295]
Hi,

I am using your application to play rtsp stream from camera. It work fine.
But on my PC, CPU/GPU usage too high, can I decrease display frame rate to reduce CPU/GPU usage ?
(Ex: Frame Rate of camera is 25 fps but I want only display at 10 fps for lower CPU/GPU)

**Comment by hooke007** [comment]
mpv is designed for high quality rendering, I'm afraid it difficult to satisfy this demand.
`vf=<float>` may not help, convert to 30fps at runtime may cost more usage.
And have you tried hwdec?
Anyway, you can have a try.

**Comment by pubpy2015** [comment]
Thank you very much.
vf=fps=<float> worked.

with my camera, 2448x2048, 50 fps if setting fps = 10 => GPU usage reduce from 22% to 6%.

**Comment by stax76** [comment]
Two settings I needed to play UHD 60 fps with my GT 1030:

d3d11va-zero-copy = yes
hdr-compute-peak = no
