### ISSUE TITLE
Unable to load DLL 'mpv-1.dll'

### ISSUE THREAD

**Issue by DiracSpace** [stax76/mpv.net#296]
I recently formatted and installed Windows again, I've applied all available uploads before installing any personal use software. These issues occurred when I tried installing MPV on the recent release build. I already installed .NET Runtime 6.0 and have .NET Framework 4.8 installed. What else could it be?

![mpvnotfound](https://user-images.githubusercontent.com/49464343/127756495-318b5ab5-d023-4a05-b14d-c3879e84a2ab.PNG)
![mpvissue](https://user-images.githubusercontent.com/49464343/127756496-a8fa3d9a-ce4c-408d-bca8-a4967f95811c.PNG)

**Comment by DiracSpace** [comment]
I've searched in the files and the DLL is right there
![files](https://user-images.githubusercontent.com/49464343/127756539-204199a1-15f3-4464-825b-7a76ef383af2.PNG)

**Comment by stax76** [comment]
> I recently formatted and installed Windows again

Why did you do this? I'm curious about your level of expertise.

How exactly did you start mpv.net, from the start menu, powershell terminal or somehow else?

Might there be multiple mpv.net installations? In doubt, search with Everything.NET.

You can try to redownload and reinstall mpv.net because it might be file corruption.

If it doesn't work, you can try the portable download.

**Comment by DiracSpace** [comment]
> Why did you do this? I'm curious about your level of expertise.

Well, I reinstall Windows every now and then when my setup has files/software I'm not required to use anymore. 

I downloaded the install file, executed it multiple times but it all indicated something else was the issue, since I have not found a solution, I've decided the portable version might do

**Comment by stax76** [comment]
I verified the setup works correctly, so it's an issue on your side.

You are not using a 32-Bit OS?

Maybe have a look in the Event Viewer of Windows.

**Comment by DiracSpace** [comment]
> Maybe have a look in the Event Viewer of Windows.

Yeah, I'm going to give that a look. If I find something I'll post it, thanks

**Comment by sebma** [comment]
@stax76 I have the same pb. and here is the SHA256 signature of the installer I downloaded from github : 

 Get-FileHash -algo SHA256 .\mpv.net-5.4.9.0-setup.exe

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          D83A992146A67977D510342063A275A6AF866350760AF2CB0B6447B53EA48299       D:\Users\sebastien\mpv.net-5.4.9.0-setup.exe

Can you please give the SHA256 signature of your binary to check if my installer is fine ?

**Comment by DiracSpace** [comment]
I have the same SHA256 signature from a file currently downloaded

```powershell
PS C:\Users\jsonr\Downloads> Get-FileHash -algo SHA256 .\mpv.net-5.4.9.0-setup.exe

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          D83A992146A67977D510342063A275A6AF866350760AF2CB0B6447B53EA48299       C:\Users\jsonr\Downloads\mpv....

```

**Comment by stax76** [comment]
Again, is this a 32-Bit OS?

I'm not having a 'mpv.net-5.4.9.0-setup.exe' file locally.

Please try the last beta version using a x64 OS.

**Comment by sebma** [comment]
@stax76 Nope. It's a 64 bit OS. As of today, the latest release on your mpv project is `5.4.9.0`. There is no beta release, it's pointing to  : https://github.com/stax76/mpv.net/releases/latest

**Comment by stax76** [comment]
Beta releases are on OneDrive and DropBox because that is very easy to automate (scripting via powershell, it's only a local file copy).

https://github.com/stax76/mpv.net#download

https://github.com/stax76/mpv.net/blob/master/docs/Manual.md#download

**Comment by sebma** [comment]
@stax76 Thanks :+1: I don't have the Win10 PC anymore at my disposal. But as soon as I the remote access to that PC. I'll try and install this beta release.

**Comment by sebma** [comment]
@stax76 I had forgotten to mention I had installed [mpv with chocolatey](https://community.chocolatey.org/packages/mpvnet.install) : 

```pwsh
PS C:\> sudo cinst mpvnet.install
Chocolatey v0.11.3
Installing the following packages:
mpvnet.install
By installing, you accept licenses for the packages.
Progress: Downloading mpvnet.install 5.4.9.0... 100%

mpvnet.install v5.4.9.0 [Approved]
mpvnet.install package files install completed. Performing other installation steps.
Downloading mpvnet.install 64 bit
  from 'https://github.com/stax76/mpv.net/releases/download/5.4.9.0/mpv.net-5.4.9.0-setup.exe'
Progress: 100% - Completed download of C:\Users\sebastien\AppData\Local\Temp\chocolatey\mpvnet.install\5.
4.9.0\mpv.net-5.4.9.0-setup.exe (23.02 MB).
Download of mpv.net-5.4.9.0-setup.exe (23.02 MB) completed.
Hashes match.
Installing mpvnet.install...
mpvnet.install has been installed.
  mpvnet.install can be automatically uninstalled.
 The install of mpvnet.install was successful.
  Software installed to 'C:\Program Files\mpv.net\'

Chocolatey installed 1/1 packages.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
```

Maybe there is something wrong with : https://github.com/C4illin/Choco-Packages/tree/master/mpvnet.install
