### ISSUE TITLE
Single Instance = EXCELLENT, but QUEUE mode not as it should be

### ISSUE THREAD

**Issue by 44vince44** [stax76/mpv.net#30]
First, thank you very much for implementing the single instance mode, which I have been waiting for a long time, and now will allow me get rid of WMP forever :-)

However, I tried the Queue mode, and the files are queued ok, but at the end of the current list, which happens to be the full alphabetic list of files of the folder of the first file opened.
Does that make sense? I think that in QUEUE mode, when you open your first file (before appending), it should only create a playlist with that file only, not the whole folder!

Thanks again for the great work

**Comment by stax76** [comment]
Thanks for the positive feedback, next release will work as requested.

Furthermore:

The playlist is never cleared whenever the control key is down but files and URLs are appended instead.

**Comment by 44vince44** [comment]
Stax, can we also have the possibility, I mean just only one way, to open one single file as a playlist (I think the drag and drop used to to work like that some versions ago). While of course keeping all other ways to open the folder as it is now.

**Comment by stax76** [comment]
I want to avoid feature creep and cognitive overload but I can easily write it for you as script.

**Comment by 44vince44** [comment]
That would be very kind of you !!!!!!

**Comment by stax76** [comment]
I found out it can be done straight forward without script in the next release.

You will be able to use this in input.conf:

script-message mpv.net open-files no-folder

**Comment by 44vince44** [comment]
Ah, that's a good solution (and simple!). Thanks !

**Comment by stax76** [comment]
You're welcome. The new release is out.
