### ISSUE TITLE
Allow Full Windows Explorer When Opening DVD/BD/Folder

### ISSUE THREAD

**Issue by DReaper** [stax76/mpv.net#301]
**Is your feature request related to a problem? Please describe.**
When you Open > Open Files, a full Windows Explorer windows appears that lets you select from your shortcuts or type in a folder directory. When you Open > Open DVD/Blu-Ray Drive/Folder, only a simplified Browse for Folder appears, and you have to manually click through folders and drives to where you want. This is tedious when the ISO or folder is deep in a drive.

**Describe the solution you'd like**
Have same functionality between Open > Open Files and Open > Open DVD/Blu-Ray Drive/Folder.

**Comment by stax76** [comment]
Supported in the last beta, so can be closed.
