### ISSUE TITLE
frequent pop-up window when clearing some key bindings

### ISSUE THREAD

**Issue by hooke007** [stax76/mpv.net#302]
**Describe the bug**
Maybe not a bug. Just sth about experience.

**To Reproduce**
1. open input editor
2. clear multiple keys
3. See the window

**Expected behavior**
No message would show

**Screenshots**
![Snipaste_2021-08-09_22-48-15](https://user-images.githubusercontent.com/41094733/128726459-591f8933-29ba-4399-97db-511be7ca4bb8.jpg)

**Additional context**
However, it doesn't affect the result I want. I did clear all the keys I selected.

**Comment by stax76** [comment]
I've removed the message.

**Comment by hooke007** [comment]
Removing may not be a perfect solution. It could remind users had set the dup hotkeys

**Comment by stax76** [comment]
That is OK for me.
