### ISSUE TITLE
How to use `MBTN_RIGHT` in the osc button?

### ISSUE THREAD

**Issue by hooke007** [stax76/mpv.net#304]
In mpv.net `MBTN_RIGHT` is used for context menu, but the some original OSC buttons can be clicked by `MBTN_RIGHT` (which have the different functions) in mpv.
How could I use both of them in mpv.net

**Comment by stax76** [comment]
Which right buttons have a different meaning in the OSC?

It's something that would need fixing in mpv.net. But before fixing this, I plan to replace the context menu implementation in order to get rounded corners.

**Comment by hooke007** [comment]
many buttons (list below).
https://mpv.io/manual/master/#using-the-osc

**Comment by stax76** [comment]
I never knew this and will fix it.

**Comment by stax76** [comment]
I couldn't get it perfect unfortunately, after every click one or two seconds must be waited.

It's committed, along with a major UI rework, please let me know if something needs fixing.

**Comment by hooke007** [comment]
>after every click one or two seconds must be waited.

LGTM. A little bit diff here, just 0.5s or less for me.

And in a short test, the new context menu works well.

**Comment by hooke007** [comment]
The new context menu disappear much slower than before, especially when open the file and exit the program.

**Comment by stax76** [comment]
I'll try to find a solution.

**Comment by hooke007** [comment]
Thanks, it works well.
