### ISSUE TITLE
thxs so much for yr prompt reply!

### ISSUE THREAD

**Issue by p060477** [stax76/mpv.net#306]
thxs so much for yr prompt reply!
so sorry....
consider also an italian trad in future..as for ex:
mpv-easy player which is also based on mpv,the you called elite/nerdy...,
but has also the ita lang included...
;)

_Originally posted by @p060477 in https://github.com/stax76/mpv.net/issues/305#issuecomment-898548681_

**Comment by hooke007** [comment]
He said mpv is nerdy. mpv-easy player is the front-end. mpv ≠ mpv-easy player

**Comment by p060477** [comment]
> 
> 
> He said mpv is nerdy. mpv-easy player is the front-end. mpv ≠ mpv-easy player

...as mpv.net....so....2+2= 4.....
