### ISSUE TITLE
support for `input-ipc-server` option

### ISSUE THREAD

**Issue by soredake** [stax76/mpv.net#308]
**Is your feature request related to a problem? Please describe.**
Right now i'm trying to setup this thing https://github.com/iamkroot/trakt-scrobbler/wiki/Players-Setup, but setting `input-ipc-server` in mpv.conf does nothing.

**Describe the solution you'd like**
Having support for this option.

**Describe alternatives you've considered**

**Additional context**
mpv.net version is `5.4.9.2 Beta`

**Comment by hooke007** [comment]
I use the ipc for svp manager. It works perfectly. So I think it is not the problem of supporting. Maybe sth wrong with the IPC Path.

**Comment by soredake** [comment]
@hooke007 can you please show me example how to set it? I've tried `input-ipc-server=\\.\pipe\tmp\mpv-socket` `trakts config set players.mpv.ipc_path \\.\pipe\tmp\mpv-socket` but trakts does not see mpv.net instance running.

**Comment by hooke007** [comment]
I didn't know about trakt-scrobbler. For svp, the option should be set `input-ipc-server=mpvpipe`

**Comment by soredake** [comment]
Trakts can see mpv with `input-ipc-server="\\.\pipe\mpvsocket"`, but not mpv.net, dunno where problem is, in mpv.net or trakts if it can work fine with regular mpv.

**Comment by soredake** [comment]
I've found my problem, i need to put `input-ipc-server` before `[protocol.https]` block or mpv.net will ignore it.

**Comment by stax76** [comment]
You can get help for this here:

https://www.reddit.com/r/mpv

**Comment by rollingmoai** [comment]
> > I've found my problem, i need to put `input-ipc-server` before `[protocol.https]` block or mpv.net will ignore it.
> 
> I don't have the [protocol.https] block and trakts is still not working.

Same here. @soredake Can I see your `mpv.conf`?



> You can get help for this here:
> 
> [reddit.com/r/mpv](https://www.reddit.com/r/mpv)

I don't think that can help as mpv just works fine, so this is an mpv.net specific problem.
