### ISSUE TITLE
as ActiveX Control

### ISSUE THREAD

**Issue by pc8181** [stax76/mpv.net#31]
Hi,
      m newbie here.....
    I am using axwindows media player control for video playback in my forms, may i use this as an activex control to play videos in my form ?... 

Thanks

**Comment by stax76** [comment]
Which language are you using?

To build a dotnet control it needs some dotnet and libmpv experience.

You might also try a project that is totally unrelated to my project:

https://github.com/hudec117/Mpv.NET.lib
