### ISSUE TITLE
[Feature Request] Adapt subtitles position so that when moving mouse OSC doesn't hide/overlap them

### ISSUE THREAD

**Issue by kwstas86** [stax76/mpv.net#311]
It's similar to that Feature Pot Player has, i don't think i need to go into specifics but i will should i be requested to.

**Comment by hooke007** [comment]
In fact, the osc of mpv is one kind of ASS(subtitle), so far none of media players can do the function you mentioned. It sounds like the GUI's job.

**Comment by kwstas86** [comment]
> In fact, the osc of mpv is one kind of ASS(subtitle), so far none of media players can do the function you mentioned. It sounds like the GUI's job.

Oh, so then are you suggesting me to make that request on the official mpv's discussion?

**Comment by hooke007** [comment]
No, I just point out the diff. Also someone once made the request but no more response. https://github.com/mpv-player/mpv/issues/6872

**Comment by kwstas86** [comment]
> No, I just point out the diff. Also someone once made the request but no more response. [mpv-player/mpv#6872](https://github.com/mpv-player/mpv/issues/6872)

I see, well thank you for the clarification.
