### ISSUE TITLE
Opening a specific jpg file will cause mpv.net to crash immediately

### ISSUE THREAD

**Issue by cosmic-latte** [stax76/mpv.net#313]
**Describe the bug**

Opening a specific jpg file will cause mpv.net to crash immediately.
But this picture file is not damaged and can be opened and viewed normally in other software such as original mpv.

**To Reproduce**
1. Just drag the file to the mpv window or right click "open with mpv.net"

**Expected behavior**
Error dialog pops up.

**Screenshots**
<img width="321" alt="2021-08-19 160059" src="https://user-images.githubusercontent.com/4134105/130031152-e1801f29-9af3-41d0-887a-d8679157c432.png">

The file that caused the software to crash:
I am not sure if the uploaded file has been re-encoded by GitHub
![12](https://user-images.githubusercontent.com/4134105/130032889-1ca4c848-c555-4f15-ab47-7317222e692e.jpg)

**Comment by cosmic-latte** [comment]
I have tested, the pictures posted above will also cause a crash.

**Comment by stax76** [comment]
It can be reported upstream:

https://github.com/mpv-player/mpv/issues

**Comment by cosmic-latte** [comment]
The original mpv Windows build can open this file normally without any error, so are you sure this is an upstream problem?

**Comment by stax76** [comment]
Maybe you get the message from mpv.net because mpv.net is a debug build, I generally release debug builds and never release builds for every .NET app, doing this for 19 years. I'm not really understanding what's wrong here, @shinchiro builds are built with GCC, I don't understand why is there a VC++ error.

**Comment by cosmic-latte** [comment]
Thanks for your kind reply.

**Comment by hooke007** [comment]
cannot reproduce here.
![Snipaste_2021-08-22_12-30-34](https://user-images.githubusercontent.com/41094733/130342345-1401df35-cc71-482c-ab03-c12a445cf86a.jpg)
