### ISSUE TITLE
Force subtitle Style

### ISSUE THREAD

**Issue by RaXorX** [stax76/mpv.net#314]
How do I force the subtitle style to be the same?
I tried sub-ass=yes in the config file (mpv.conf) and sub-ass-override=yes too. Neither of those had any effects at all for me. It would be good to include an option for it within the settings itself.

**Comment by hooke007** [comment]
To be specific?

`sub-ass=yes` `sub-ass-override=yes` are the default setting for mpv, so I don't understand why u did that.

**Comment by RaXorX** [comment]
> To be specific?
> 
> `sub-ass=yes` `sub-ass-override=yes` are the default setting for mpv, so I don't understand why u did that.

Hmm, does yes mean that it'll force the subtitles to have the font/color to be what you specify in settings with `sub-font` and `sub-color` or does it mean the opposite? Because I tried with yes and no both and it didn't have any effects at all.

**Comment by hooke007** [comment]
https://mpv.io/manual/master/#options-sub-ass-override
1. If you want to ignore all the tags in ass script, use `strip`

==================

2. And the `sub-ass-override=yes` means it will receive all the options `sub-ass-*` you set. As is mentioned in the manual
```
Apply all the --sub-ass-* style override options. Changing the default for any of these options can lead to incorrect subtitle rendering (default).
```

**Comment by RaXorX** [comment]
My bad really. Turns out the video had pgs subtitles instead of ssa/ass instead. I should have checked prior to opening the issue.
