### ISSUE TITLE
Exception error at startup after the upgrade to 5.4.9

### ISSUE THREAD

**Issue by pitsi** [stax76/mpv.net#316]
**Describe the bug**
An long exception error message appears after the upgrade to 5.4.**9**.0. I was on 5.4.8 until 5 minutes ago and I just found out 5.4.9 was released 3 months ago, so I upgraded to it.
I am mainly a linux user and I rarely log in to my windows installation. And even more rarely, I launch mpv.net to watch something, thus this huge delay.

**To Reproduce**
1. Install or upgrade to 5.4.9.
2. Launch the app from it's shortcut
3. The error in the screenshot appears
4. Mpv works fine though. I mainly use it to watch iptv m3u8 streams.

**Expected behavior**
No error should pop up.

**Screenshots**
![error](https://user-images.githubusercontent.com/5880037/131243029-078ec33a-52cf-4e9d-bd92-01f2f2e69c98.jpg)

**Additional context**
Windows 7 x64, greek locale, updated up to May 2021. In case any vc++ redistributable runtime is needed, I have all of them (2005 to 2022) installed and updated until their August 2021 versions (14.30.30423 for vcredist 2022, the others do not get updates).

**Comment by hooke007** [comment]
dup https://github.com/stax76/mpv.net/issues/256

**Comment by pitsi** [comment]
Is it fixed then? Because the other issue report is closed...
I would close this issue too and use a beta version of the app until the fix reaches stable, but only if it is fixed in betas.

**Comment by hooke007** [comment]
full-clean your files related with 5498 and reinstall 5490

**Comment by pitsi** [comment]
Full clean as in... delete everything about it in registry, program files etc?

**Comment by hooke007** [comment]
files and config in the explorer should be enough

**Comment by pitsi** [comment]
Ok. Is anything stored in %appdata% that needs to be deleted?

**Comment by hooke007** [comment]
mpvnet in appdata should be cleaned, or may have terrible
 effect on the next version's context menu

**Comment by pitsi** [comment]
So I reinstalled 5.4.9 after removing everything from program files and appdata and it is now back to normal.
I hope I won't have to do this again for 5.4.10 or any feature releases...
