### ISSUE TITLE
the pop-up window covered by mpv.net windows when enable ontop 

### ISSUE THREAD

**Issue by zhongfly** [stax76/mpv.net#318]
**Describe the bug**
If I enable ontop and then Show Properties(`script-message mpv.net show-properties`),the pop-up window covered by mpv.net windows so mpv.net windows will become unresponsive.
**To Reproduce**
First case:

0. open mpvnet by double click .exe file or run cmd command `mpvnet`
1. play a video
2. enable ontop(menu: View > On Top > Enable)
3. Show Properties(menu: View > Show Properties),chose any properties and click it.
4. the pop-up window covered by mpv.net windows and mpv.net windows become unresponsive

Second case:

0. open mpvnet by run cmd command `mpvnet --msg-level=all=v`
1. play a video
2. enable ontop(menu: View > On Top > Enable)
3. Show Properties(menu: View > Show Properties),chose any properties and click it.
4. Property is not displayed and _mpv.net windows work fine_

**Expected behavior**
the pop-up window covered mpv.net windows

**Screenshots**

**Additional context**
version:5.4.9.7-portable-beta
my mpv.conf
```json

input-default-bindings = no
input-ar-delay = 500
input-ar-rate = 20
keep-open = yes
keep-open-pause = no
osd-duration = 2000
osd-playing-msg = '${filename}'
script-opts = osc-scalewindowed=1.5,osc-hidetimeout=2000,console-scale=1
screenshot-directory = '~~desktop/'
watch-later-options = start
```

**Comment by hooke007** [comment]
When `ontop` is active, mpv would cover the pop-up window, move away the mpv you'll see it.

**Comment by zhongfly** [comment]
> When `ontop` is active, mpv would cover the pop-up window, move away the mpv you'll see it.

on the first case,mpv.net windows is freeze and can't move/close

**Comment by hooke007** [comment]
It may need a patch to make it disable the `ontop` temporarily as the pop-up window to be active.

**Comment by stax76** [comment]
Fixed in the last beta, so can be closed.
