### ISSUE TITLE
Keyboard layout-sensitive shortcuts

### ISSUE THREAD

**Issue by FrenzyYum** [stax76/mpv.net#319]
When launching the player with English keyboard chosen and changing the keyboard language there shows no issues and all the shortcuts work as expected. However, if you start the player with non-English keyboard layout (Russian uses Cyrillic letters, for instance), shortcuts that are assigned to English letters don't work. Switching back to English layout does not work and the only option is to restart the player with English layout chosen.

The issue here is that the input editor accepts and reads keys as letters (I can assign Russian letters-shortcuts to individual commands and it works) and not as keycodes. I believe the quick workaround, if implementing keycodes would take too much time or not something in priority, is to detect `WM_INPUTLANGCHANGE` since you read keyboard events anyway [here](https://github.com/stax76/mpv.net/blob/master/src/Misc/MainForm.cs#L740) and to load the hotkeys again whenever a switch to English layout is made so no player restart would be needed.

**Comment by hooke007** [comment]
Sounds like https://github.com/mpv-player/mpv/issues/9168#issuecomment-908174144

**Comment by FrenzyYum** [comment]
> 
> 
> Sounds like [mpv-player/mpv#9168 (comment)](https://github.com/mpv-player/mpv/issues/9168#issuecomment-908174144)

That's a different issue, I can change the language in mpv.net window, it just doesn't do anything.

Just checked whether this shortcut bug persists in mpv and it does as well. Fun part is, changing the language via a taskbar switcher does the trick in mpv.

I believe this is what it really sounds like https://github.com/mpv-player/mpv/issues/351. Almost 10 years and no solution implemented though.

**Comment by stax76** [comment]
> Just checked whether this shortcut bug persists in mpv and it does as well.

So it's an upstream problem, mpv.net does not process messages like WM_KEYDOWN, it only forwards the messages to libmpv.

https://github.com/stax76/mpv.net/blob/master/src/Misc/MainForm.cs#L742
