### ISSUE TITLE
Hide Titlebar

### ISSUE THREAD

**Issue by joshuacant** [stax76/mpv.net#32]
Hi, great work so far. One issue I've run into is that `border = no` seems to be ignored in mpv.conf, and any inputs assigned to `cycle border` also don't have any effect.

It's been a few years since I made any .net C# apps, but I think the setting is `this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;` I could be very wrong, though.

Thanks for all your hard work on this.

**Comment by stax76** [comment]
Hi, thanks for the positive feedback. Next release has:

- support for the mpv property 'border' was added to the config editor
  to show/hide the window decoration (titlebar, border). A toggle menu item
  and key binding (b) was added as well ([Default Binding](https://github.com/stax76/mpv.net/blob/master/mpv.net/Resources/inputConf.txt#L135))

FormBorderStyle was fine to implement it.

**Comment by joshuacant** [comment]
That was so fast! Thank you again. I'm looking forward to the next release.
