### ISSUE TITLE
Black bars on vertical video

### ISSUE THREAD

**Issue by ScribbleGhost** [stax76/mpv.net#320]
Is there any way to avoid getting these black bars on the left and right when playing a vertical video?

![51874665](https://user-images.githubusercontent.com/49068170/132989446-30b7aab3-0688-47c7-acee-3a8ae261e18f.png)

MPV.exe and MPC-BE do not produce this as far as I am aware.

**Comment by hooke007** [comment]
https://github.com/stax76/mpv.net/blob/master/docs/Manual.md#--minimum-aspect-ratiofloat

**Comment by ScribbleGhost** [comment]
> your sample cannot touch that limitation

Not sure what you mean by that. Are you suggesting I should set `--minimum-aspect-ratio=` to `0.5` then? Seems to work.

**Comment by hooke007** [comment]
>Not sure what you mean by that. 

Your sample 1080x1920 ---- its aspect=1080/1920＞0.5 . That's why "MPC-BE do not produce this"

**Comment by ScribbleGhost** [comment]
Thanks. Setting `--minimum-aspect-ratio=0.5` seems to do the trick.
