### ISSUE TITLE
mpv setting `pause=yes` don't work

### ISSUE THREAD

**Issue by zhongfly** [stax76/mpv.net#321]
**Describe the bug**
`pause=yes` means start the player in paused state.I add this setting into mpv.conf,but it didn't work.
https://mpv.io/manual/master/#options-pause

**Version**
5.5.0.2-portable-beta

**To Reproduce**
1. add `pause=yes` into mpv.conf
2. open a video with mpvnet

**Expected behavior**
the player in paused state

**Additional context**
my mpv.conf:
```ini
input-default-bindings = no
input-ar-delay = 500
input-ar-rate = 20
keep-open = yes
keep-open-pause = no
osd-duration = 2000
osd-playing-msg = '${filename}'
script-opts = osc-scalewindowed=1.5,osc-hidetimeout=2000,console-scale=1.5
screenshot-directory = '~~desktop/'
watch-later-options = mute
pause = yes
```

**Comment by zhongfly** [comment]
I have tested 5.4.9.0,it work fine

**Comment by hooke007** [comment]
https://github.com/stax76/mpv.net/commit/a935cac7916e2bb66dbc3c98e9684ad4678dce6e

**Comment by stax76** [comment]
mpv.net forces `pause=no` in various places, for instance after file load, currently it's not possible to disable this behavior, but I consider making this an option.

May I ask why you want to use `pause=yes`? It appears to be rather uncommon.

**Comment by zhongfly** [comment]
> mpv.net forces `pause=no` in various places, for instance after file load, currently it's not possible to disable this behavior, but I consider making this an option.
> 
> May I ask why you want to use `pause=yes`? It appears to be rather uncommon.

Open the video and select the subtitle/audio before playing it, or open the video in advance and watch it later.
Maybe it's just my personal habit

**Comment by hooke007** [comment]
For me it's a measure to improve the stability especially using some scripts.

**Comment by stax76** [comment]
The next build has a new `auto-play` option, disabled by default.

**Comment by stax76** [comment]
New Beta is online.
