### ISSUE TITLE
Auto change window size in playing video

### ISSUE THREAD

**Issue by nthtimes** [stax76/mpv.net#326]
I have tried the following:
- set start-size as video
- add "window-scale = 1.0" to mpv.conf

But it won't auto change window size if I open video after start the program.

program version:
mpv.net-5.5.0.2-portable-beta

**Comment by stax76** [comment]
I'm not able to reproduce it.

**Comment by nthtimes** [comment]
I'm sorry I forgot to provide my configuration.

mpvnet.conf
```
# Editor
start-size = video
```
mpv.conf
```
keepaspect-window = no
window-scale = 1.0
```

**Comment by stax76** [comment]
Now I understand what's the issue:

It's by design, `keepaspect-window=no` mostly does the same as `start-size=always`, it keeps the full window size.

I might have to review and change and/or document it.

**Comment by stax76** [comment]
There is a new Beta:

- New option start-size=session to freeze the window size per session.
- Changed keepaspect-window behavior.

I hope it's better and stable.
