### ISSUE TITLE
Automatically open/play recent file.

### ISSUE THREAD

**Issue by ae1337** [stax76/mpv.net#328]
I'm not sure if this is possible via config or not, but such option would be nice.
The way lot of people use such players, to watch tv shows/series, they open first episode from folder, never bother with playlists, and then continue watching it. Player can already automatically detect next episode and jump to it. But then when you close the player, and open it up again, you gotta navigate to recent files every time, to proceed watching where you left. Fastest way I've found in mpv.net is to use Alr+r and then arrow down once to select last recently played file. I would love to be able to automate that sequence, to simulate how popular streaming services offer their tv shows, you can easily get back to where you left, without any additional confirmations or selections.

**Comment by dyphire** [comment]
For now, you can use this script to do it: [SmartHistory](https://github.com/Eisa01/mpv-scripts#smarthistory-script)

**Comment by ae1337** [comment]
I sticked to opening recent files from keyboard, and then just pressing arrow once. 
But I've recently reinstalled os, and installed fresh new version of mpv.net, but I can't seem to find this keybind? There is no recent file option in input editor or am i blind? I want to bring this menu, similar to the one that default F1 brings, but with recently opened files, is that still possible? Right click menu open->recent->list is really annoying to navigate for example using tochpad keyboard while using tv to watch.

**Comment by stax76** [comment]
You can show the recent list in the command palette:

`Alt+r     script-message mpv.net show-recent     #menu: View > Show Recent`

If you press the down key, it will select the first (most recent) file, play it with the enter key.

In the next build, this will auto select the most recent entry at the top, so you only have to confirm with enter.

Also in the next build you can just press space, when the playlist is empty it will play the most recent file, some other players like mpc-be support that too.

But you will have to modify input conf:

`Space     script-message mpv.net play-pause     #menu: Play/Pause`

I try to upload it soon.

**Comment by stax76** [comment]
It's now online:

https://github.com/stax76/mpv.net/releases

**Comment by dyphire** [comment]
> `Space script-message mpv.net play-pause #menu: Play/Pause`

It will also have this issue: https://github.com/stax76/mpv.net/issues/329

**Comment by stax76** [comment]
If it's not tagged with priority-low, it will not be forgotten, but just needs time to catch up after my 4-month hiatus.

**Comment by leftcausedit** [comment]
Reoccur in mpv.net v7+
