### ISSUE TITLE
The autoload function is not working normally

### ISSUE THREAD

**Issue by dyphire** [stax76/mpv.net#329]
**Describe the bug**
When files are recovered not through the menu but through other scripts, other files in the same directory cannot be loaded automatically. For example, this restriction will be triggered when using the script function of [SmartHistory.lua](https://github.com/Eisa01/mpv-scripts#smarthistory-script) or [SmartCopyPaste-II.lua](https://github.com/Eisa01/mpv-scripts#smartcopypaste-ii-script). but the [autoload.lua](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua)  works normally

mpv.net version: 5.5.0.3 Beta

**To Reproduce**
1. Use SmartHistory.lua or SmartCopyPaste-II.lua
2. Use the above script functions
3. Other files in the same directory cannot be loaded automatically

**Expected behavior**
Automatic loading of files in the same directory

**Screenshots**
![Screens](https://cdn.jsdelivr.net/gh/dyphire/PicGo/img/2021/10/02/20211002091649.png)

**Additional context**
When the autoload.lua script is used to load the file, everything works normally

**Comment by stax76** [comment]
I'm not sure if I will change it because this area can affect stability.

Are you now using autoload.lua ?

**Comment by dyphire** [comment]
> I'm not sure if I will change it because this area can affect stability.
> 
> Are you now using autoload.lua ?

Yes, it can fix this issue. But it also replaces the file loading function of mpv.net.

**Comment by dyphire** [comment]
This issue has been fixed after this commit: https://github.com/stax76/mpv.net/commit/6fc546c69c362bebcbc949a3edcb267a9d01ae29
