### ISSUE TITLE
Make mpv.net appear in the permanent OPENWITH LIST on Win10 (solution)

### ISSUE THREAD

**Issue by 44vince44** [stax76/mpv.net#33]
Dear Stax,
In Windows 10, unlike Windows 7, mpv.net will not appear permanently in the open with list (right click), no matter what you do. The solution is an entry in the registry.

![SNAG-0002](https://user-images.githubusercontent.com/17828567/60211629-1baf3a00-9868-11e9-9e0f-705f881d45ab.jpg)

Solution:

[HKEY_CLASSES_ROOT\Local Settings\Software\Microsoft\Windows\Shell\MuiCache]

"C:\\Program Files\\mpv.net\\mpvnet.exe.FriendlyAppName"="mpv.net media player"
"C:\\Program Files\\mpv.net\\mpvnet.exe.ApplicationCompany"="mpv.net Dev Team"

Currently, the last line is missing. Just by adding it (i.e setting the ApplicationCompany), mpv.net will remain permanently in the openwith list.

This is useful for people that do no want mpv to be their main player.

**Comment by stax76** [comment]
Thanks for the tip, I'll add it if I can make it work.

Maybe interesting:

https://github.com/stax76/OpenWithPlusPlus

**Comment by 44vince44** [comment]
> https://github.com/stax76/OpenWithPlusPlus
 Yes i saw that, but when the solution is to add a single silly registry entry ;-)))

**Comment by stax76** [comment]
The problem was the company info was missing in the manifest.

Great find !!! 👍

**Comment by 44vince44** [comment]
It took me some time to find it ;) ... because it was sooo silly!! ;-))))
