### ISSUE TITLE
Can't change theme at all.

### ISSUE THREAD

**Issue by may-son** [stax76/mpv.net#332]
I want to make the bright white color of seek bar and other bottom stuff more grayish (darker), and there is no option in settings for that, and themes configuration doesn't work (I replaced all codes with pure red (#FF0000), and I don't see red anywhere, whereas in theory I will see that all interface just red). What do I need to do? Or wait for a fix?
_(BTW program works great, and color management good, but the configuration menu is very unintuitive)_

**Comment by stax76** [comment]
> It would be cool if OSC colors could be controlled from mpv.conf without osc.lua.

You can request it on the mpv issue tracker:

https://github.com/mpv-player/mpv/issues
