### ISSUE TITLE
[feature request] support the property `snap-window`

### ISSUE THREAD

**Issue by dyphire** [stax76/mpv.net#334]
**Is your feature request related to a problem? Please describe.**
mpv.net can't snap the player window to screen edges when move window

**Describe the solution you'd like**
To support the  property `snap-window`

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by Mattwmaster58** [comment]
I'm assuming you are referring to this command line flag: https://mpv.io/manual/stable/#options-snap-window?

**Comment by dyphire** [comment]
> I'm assuming you are referring to this command line flag: https://mpv.io/manual/stable/#options-snap-window?

yes,it is

**Comment by stax76** [comment]
Wasn't completely easy.
