### ISSUE TITLE
mpvnet lagging/crashing itself and windows as a whole.

### ISSUE THREAD

**Issue by BhaturaGuy** [stax76/mpv.net#335]
OS: Windows 10
mpvnet version: 5.4.9.0 (latest)

I am on a laptop. mpvnet most of the times crashes/lags making it unable to play the file, playing only one id inside the container (for eg. Either only audio, or just video with a white filter over it making it translucent), sometimes it plays the file just fine but takes around 5-8 minutes to load the file where it constantly shows "not responding" until the file the file is played. Whenever it does that kind of behavior ram reaches usage keeps on increasing till the point where the whole windows won't respond.

**Steps to reproduce the behavior:**
1. Set mpvnet as the default player for videos or any playable format.
2. Simply play the _file_ (it doesn't matter what type of file as long as it is playable by mpv).

**Expected behavior** 
File should've played as it should like in any media player. And sometimes it does. But, _sometimes_ only.

**Screenshots**
![Screenshot (291)](https://user-images.githubusercontent.com/93109835/139675585-4a5bb2fd-d2bb-4845-9fb4-32714483e6b8.png)
As you can see here mpvnet went somewhat white and RAM usage increased drastically to the point where even the windows wasn't responding.

**Additional context**
Sometimes it plays it fine but takes forever to load as compared to the original mpv. I've test the _Steps to reproduce the behavior:_ for around 3 months on original mpv but not once I faced this issue. It has happened to different types of files like :- flac, mp3, mp4, mkv, ts, by this I'm only assuming it happens to all the playable formats by mpvnet. Today I did the same _Steps to reproduce the behavior:_ and it happened again.

**Logs**
[logs.txt](https://github.com/stax76/mpv.net/files/7453484/logs.txt)
 Here's the logs to the recent time it happened.

**config folder**
[mpv.net.zip](https://github.com/stax76/mpv.net/files/7453511/mpv.net.zip)

Don't know if it would be of any use but here's the mpv.net folder located at C:\Users\BHATURA\AppData\Roaming

**Comment by stax76** [comment]
I believe it's caused by the OSD or OSC because it happens with audio files too, and you have configured many OSD and OSC options, a mpv bug I would guess.

**Comment by BhaturaGuy** [comment]
> a mpv bug I would guess.

Update: I tried the 5.5.0.4 Beta (2021-11-05) which uses shinchiro's mpv 2021-10-31 as a base this happened again but not in the mpv which I've using and updating since September, I would guess it has something to with mpv.net only.

**Comment by BhaturaGuy** [comment]
> 

Not a mpv bug per se. I have been using mpv since last year January, but never faced the issue even once. It has something to with my osd/ocs settings with mpvnet only for sure. Also the problem still exists on 
v5.7.0.0.

**Comment by stax76** [comment]
It's possible that a native/unmanaged library has a memory management bug that stays unnoticed in a native application and surfaces only in a managed application, I know this by experience.

**Comment by BhaturaGuy** [comment]
Today I found out that some settings in scipts-opt/osc.conf were causing the problems, issue is now resolved.
