### ISSUE TITLE
Where can I get `mpvnet.com` for x86?

### ISSUE THREAD

**Issue by zhongfly** [stax76/mpv.net#337]
As manual said:
> mpvnet.exe is platform agnostic, users that need x86 have to replace 3 native tools:
> mpv-1.dll
> MediaInfo.dll
> mpvnet.com

So I want to kown where can I get `mpvnet.com` for x86.

**Comment by stax76** [comment]
You can use it from an old release:

https://github.com/stax76/mpv.net/releases/tag/5.4.8.0
