### ISSUE TITLE
Remember size and position of window

### ISSUE THREAD

**Issue by fikrillah** [stax76/mpv.net#338]
Hi, thanks for bringing mpv on windows.

Anyway, it annoys me when i exit fullscreen mode or opening another video, the size and possition of mpv window changes. I'm get used to how celluloid works on linux (or any other video player really), when i exit fullscreen or opening differnet file, the window possition and size stays the same.

I always tile my file explorer window where multiple videos are listed  to the left, and my video player to the right of the screen. This bug destroys that workflow.

**Comment by hooke007** [comment]
https://github.com/stax76/mpv.net/blob/master/docs/Manual.md#--start-sizevalue

**Comment by bamper45** [comment]
> [https://github.com/stax76/mpv.net/blob/master/docs/Manual.md#--start-sizevalue ](https://github.com/stax76/mpv.net/blob/master/docs/Manual.md#--start-sizevalue)

what commands should be entered in config?
I need not to change the width and height

**Comment by hooke007** [comment]
> mpv.net specific options can be found in the conf editor searching for 'mpv.net'.

Just to find them in the editor.

**Comment by bamper45** [comment]
@hooke007 Where? Which editor? In texting?

**Comment by hooke007** [comment]
Have u checked context menu options?
https://github.com/stax76/mpv.net#config-editor

**Comment by bamper45** [comment]
@hooke007 No, how can I open it?

**Comment by hooke007** [comment]
https://github.com/stax76/mpv.net/blob/master/docs/Manual.md#input-and-context-menu

default by right-click (mouse)

**Comment by bamper45** [comment]
@hooke007 No, it does not work

**Comment by hooke007** [comment]
If you mean you cannot open editor, you should open another issue.

**Comment by bamper45** [comment]
@hooke007 Thanks, but this program is nonsense

**Comment by stax76** [comment]
There are some obstacles on purpose, not everybody can make it.
