### ISSUE TITLE
Feature Request: Open current file in filemanager

### ISSUE THREAD

**Issue by SLowrAM** [stax76/mpv.net#34]
I'd like a hotkey assignable action (i.e. F) to open the currently opened file in Explorer (i.e. Process.Start("Explorer.exe", "/select, \"" + sFilename + "\"");).

**Comment by stax76** [comment]
I'm not sure if I understand you correctly, maybe have a look at the file 'Late Binding.vb' in the staxrip source code.

There are many mpv.net scripts/plugins that show you how to run your code via key. Examples can be found via the wiki.

What's your language of choice?

**Comment by 44vince44** [comment]
Thank you for this helpful script, it works perfectly and is very useful !

**Comment by stax76** [comment]
It can be done directly in input.conf:

`ctrl+e run explorer /select, ${path}`

https://github.com/mpv-player/mpv/issues/6560
