### ISSUE TITLE
Register a handler for the ytdl:// protocol

### ISSUE THREAD

**Issue by Daktyl198** [stax76/mpv.net#341]
MPV supports loading URLs via the ytdl:// protocol and I've been utilizing that support for a while with a modified version of [this Firefox extension](https://addons.mozilla.org/en-US/firefox/addon/ff2mpv/), which bypasses the requirement for a native host application on your machine by simply converting the current URL (or the right-clicked URL) into a ytdl:// link and "opening" it. The system detects MPV as an application capable of opening such a link, and passes it right along.

I've already checked and ytdl:// works with mpv.net, so I'd appreciate it if you included it in your list of supported protocol handlers when being installed in Windows so that I may continue to use this addon with your application.

**Comment by hooke007** [comment]
Or sth like `mpvnet://` ?

https://github.com/SilverEzhik/mpv-msix#mpv-uri-scheme

**Comment by Daktyl198** [comment]
Except ytdl:// already has a handler in MPV, and wouldn’t require any extra work on the dev’s part except telling Windows that it can handle the protocol.

Implementing a new protocol handler would take some work.

**Comment by stax76** [comment]
I'm working on bringing mpv.net to the MS Store, it will be free and support auto updates. For the store package setup it was very easy to register the protocol, I've added it and successfully tested it.

For the portable release, it's a bit complicated. I might do this work sometime later, description is here:

https://stackoverflow.com/questions/80650/how-do-i-register-a-custom-url-protocol-in-windows

I'll write a message here when the store release is available, it will be available in the second store release, the first release is currently in review process.

**Comment by stax76** [comment]
It should be fixed in the last beta:

https://github.com/stax76/mpv.net/releases
