### ISSUE TITLE
the preset `script-opts` options will restrict users that could modify those ones only by mpv.conf

### ISSUE THREAD

**Issue by hooke007** [stax76/mpv.net#342]
**Describe the bug**
As the title said, it make users have to modify related options of the script in mpv.conf

**To Reproduce**

create the osc.conf in the folder `<config folder>/script-opts/`
edit it and save `scalewindowed=0.5`
run mpvnet

**Expected behavior**
smaller osc

**Screenshots**
N/A

**Additional context**
N/A

**Comment by stax76** [comment]
This will be fixed in the next commit.

**Comment by stax76** [comment]
I had forgotten the issue and reintroduced it, sorry about that.
