### ISSUE TITLE
Increase cache size via the editor

### ISSUE THREAD

**Issue by ManOnSaturn** [stax76/mpv.net#344]
On some lower-end PCs, high-bitrate files may force the player to pause/stutter. In my case, it's always the h265 files, or more rarely(since i have less of them), 4K ones.

Increasing the cache size can help some users to enjoy of heavy video files.

The solution may therefore be to add an option to increase it. As a rule of thumb, 1% of RAM size could be taken, or 80MiB.

So, the options could be something like:
Increase cache size
- No. _(Only 1 second is cached)_

- Yes. _(1% of system's RAM)_

- Extreme use. _(200MiB)_

The options that i verified to work when used togheter, are:
cache=yes
demuxer-max-bytes = 200000KiB

An alternative could be to dynamically pick the cache size, but it's probably harder to implement and adds overhead to the player.

**Comment by stax76** [comment]
I don't add many new options to the editor because the design of the editor has a performance problem. There are also usability issues. It needs a redesign, but it might not happen.

**Comment by ManOnSaturn** [comment]
There are no caveats to this, like implementing smaller sub-menus?

I'd like to help with the redesign, since the idea of being limited forever by performance issues is not ideal and will lead to the death of the project. Are there any directions? Can we open a ticket about it?

**Comment by stax76** [comment]
One of the main problems is that there can be too many controls, one idea is not showing any controls unless the search field has at least 2 or 3 characters, it's probably easy to do, so I can try that first.

**Comment by stax76** [comment]
The performance is still OK, so I added both options and add more on request.
