### ISSUE TITLE
Could not load type 'mpvnet.Core'

### ISSUE THREAD

**Issue by racrbmr** [stax76/mpv.net#346]
**Describe the bug**
After upgrade to version 5.4.9.0 everytime i open file it always display error. The error itself can be look at a picture that i sent.

**To Reproduce**
1. Open any media file
2. Error pop up displayed

**Expected behavior**
no pop up error every time open a file

**Screenshots**
![mpvnet_ak81zusjHu](https://user-images.githubusercontent.com/56998497/142790585-dd71a49f-e1d6-43cd-9c26-87e9575efc8d.png)

**Additional context**
It occur when upgrade to mpv.net version 5.4.9.0

**Comment by hooke007** [comment]
dup
https://github.com/stax76/mpv.net/issues/256
