### ISSUE TITLE
Feature Request: Assign hotkeys from scripts/addons

### ISSUE THREAD

**Issue by SLowrAM** [stax76/mpv.net#35]
I'm not to keen on having to edit conf for an addon (prefer functionality self contained in script or addon).  
For a couple scripts or addons I'd like to create I want them to get fired when a keydown event is triggered.  For such it would be useful to be able to assign hotkeys for the script (and if that hotkey is used in program, the script hotkey would win).  
Another possibility would be exposing keydown event where addon could take advantage of it and if so desired pass the action back to base.
Last thought on how to go about what I'm after may require me better understanding how to add to and trigger events and assign hotkeys to the built in contextmenu.  Perhaps a new csharp script or addon example showing how to do this for a new menu entry and assigning it's hotkey and how to track it's firing as I don't see context menu itemclicked as option in the addon api (may just not know where to look).

**Comment by stax76** [comment]
You could use JavaScript or Lua and then use this:

https://mpv.io/manual/master/#lua-scripting-mp-add-forced-key-binding(-)

Personally I don't like the idea to split key bindings to different locations.

I cannot tell you on top of my hat if you can do that with dotnet and what it would take to implement in mpv.net, I guess it's possible, you can call JavaScript from dotnet and vice versa via:

<https://mpv.io/manual/master/#command-interface-script-message>

<https://github.com/stax76/mpv.net/blob/master/mpv.net/mpv/mp.cs#L44>

Maybe I'll make some experiments.

You have full access to the mainform via dotnet so you can hook up to key events or what is more advanced to install message filters or hooks, all this is possible but not a great idea of course.

It took me months to understand libmpv, it's brilliant but takes time, start be studying the wiki.

<https://github.com/stax76/mpv.net/wiki/Scripting>

<https://github.com/stax76/mpv.net/wiki/Addons>

I'm not really good at writing a lot of help so you really have to study my code and take your time.

**Comment by stax76** [comment]
I couldn't find a way to add a mpv key binding from dotnet, I don't think it can be done with libmpv.

Following would work but it's a horrible idea!

https://docs.microsoft.com/de-de/dotnet/api/system.windows.forms.application.addmessagefilter?view=netframework-4.8

Use script-message in input.conf and the ClientMessage event to receive the message.

**Comment by stax76** [comment]
I don't think it's possible to add a key binding with libmpv.

It might be possible to generate and run JavaScript code
and then comunicate between JavaScript and dotnet
via script-message command and client-message event,
that is very complicated, I'll ask the mpv developers
if there is a easier way.

You could use JavaScript or Lua and then use this:

<https://mpv.io/manual/master/#lua-scripting-[,flags]])>

<https://mpv.io/manual/master/#lua-scripting-mp-add-forced-key-binding(-)>

Following would work but it's a horrible idea!

https://docs.microsoft.com/de-de/dotnet/api/system.windows.forms.application.addmessagefilter?view=netframework-4.8

For dotnet you can use the script-message command in input.conf
and the ClientMessage event to receive the message,
it is used in the RatingAddon.

<https://github.com/stax76/mpv.net/wiki/Addons>

There is also a PowerShell and Python script example using the ClientMessage event.

<https://github.com/stax76/mpv.net/wiki/Scripting>

**Comment by stax76** [comment]
A mpv developer gave me the clue to use this command:

https://mpv.io/manual/master/#command-interface-define-section

I try to write sample code you can use.

**Comment by stax76** [comment]
This is script code, not addon code:

```C#
using System.Reflection;

using mpvnet;

class Script
{
    public Script()
    {
        string content = "ctrl+ö script-message warp-antrieb-aktivieren";
        string sectionName = Assembly.GetExecutingAssembly().GetName().Name;
        mp.commandv("define-section", sectionName, content, "force");
        mp.commandv("enable-section", sectionName);
        mp.ClientMessage += ClientMessage;
    }

    void ClientMessage(string[] args)
    {
        if (args.Length != 1) return;

        switch (args[0])
        {
            case "warp-antrieb-aktivieren":
                Msg.Show("läuft");
                break;
        }
    }
}
```

**Comment by stax76** [comment]
Hi, here is sample code that adds a key binding:

https://github.com/stax76/mpv.net/wiki/Scripting#adding-a-key-binding

**Comment by SLowrAM** [comment]
That is great, thank you.  Allowed me to get my f (show file in explorer), and my w (move to watched), and soon probably my del (delete file) working.
`using System;
using System.IO;
using System.Reflection;
using System.Windows.Forms;

using mpvnet;

class Script
{
    // constructor for initialization work
    public Script()
    {
        //ask to move currently playing file to watched
        string content = "w script-message move-to-watched";
        string sectionName = Assembly.GetExecutingAssembly().GetName().Name;
        mp.commandv("define-section", sectionName, content, "force");
        mp.commandv("enable-section", sectionName);
        
        mp.ClientMessage += ClientMessage;
    }

    void ClientMessage(string[] args)
    {
        switch (args[0])
        {
            case "move-to-watched":
            		Watched(mp.get_property_string("path"));
            		break;
        }
    }
    
    void Watched(string psFilename)
    {
        if (MessageBox.Show("Move " + System.IO.Path.GetFileName(psFilename) + "?", "Watched", MessageBoxButtons.YesNo) == DialogResult.Yes)
        {
            try
            {
                string sPathW = System.IO.Path.GetDirectoryName(psFilename) + "\\w\\";
                try
                {
                    if (!Directory.Exists(sPathW))
                    {
                        Directory.CreateDirectory(sPathW);
                    }
                }
                catch { }
                System.IO.File.Move(psFilename, sPathW + System.IO.Path.GetFileName(psFilename));
            }
            catch (Exception exMove)
            {
                //Debug.WriteLine(exMove.Message);
            }
        }
    }
}`
I didn't have any luck combining them into 1 script, probably just as well to separate them anyhow.  Also wasn't sure what that Msg.Show you used was, perhaps I could use it for my yes/no dialog in above script if I knew it's syntax vs referencing windows.forms.
