### ISSUE TITLE
could not normally detect the left button up event under certain situation

### ISSUE THREAD

**Issue by monologconnor** [stax76/mpv.net#350]
**Describe the bug**
I have import a script of osc which works well on the original mpv project
The script is in [https://github.com/maoiscat/mpv-osc-morden](url)

However I found that under mpv.net, the seekbar could not normally detect the mouse button up event normally, but the original mpv could, which results that the dragging on the seekbar would not work normally.

![image](https://user-images.githubusercontent.com/38450642/143742974-f116a294-6b25-48d9-80cc-991219f5fd0c.png)

I have add a line here to make the player display every mouse event, then I found that only mpv.net could not capture the mouse button up event, while the mouse move and mouse button down event are normally detected.

Later I realize that if I disable the default configuration line with `script-opts = osc-scalewindowed=1.25,osc-hidetimeout=500,console-scale=1.25,osc-scalefullscreen=0.8` in mpv.conf, the seekbar will work like normal

Then I tried to add the same line in the configuration file of the original mpv, the seekbar still works. The only explanation I could make  is that some part of source code in mpv.net is ignoring the collection of mouse button up event when the `osc-scalewindowed` in the configuration is modified.

**To Reproduce**
1.  Install the script in [https://github.com/maoiscat/mpv-osc-morden](url)
2.  Add line `script-opts = osc-scalewindowed=1.25,osc-hidetimeout=500,console-scale=1.25,osc-scalefullscreen=0.8` in mpv.conf
3.  Open any video file and try click and dragging the seekbar under window mode (fullscreen will work like normal)
4.  The seeking action will not stop like normal no matter where you moved the mouse.

**Expected behavior**
While installing the same script and same configuration lines in original mpv, the seeking bar will work like normal in both window mode and fullscreen mode.

**Screenshots**

**Additional context**

Thanks for development

**Comment by hooke007** [comment]
there is a limit area for osc button

**Comment by monologconnor** [comment]
> there is a limit area for osc button dup #195

Oh okay, thanks!

I'm closing this one due to the duplication
