### ISSUE TITLE
mpv.net just broke - System.IvalidOperationException

### ISSUE THREAD

**Issue by yaroslav-semeniuk** [stax76/mpv.net#351]
For some reason, every time I launch the player now, it shows me this error (System.IvalidOperationException). I did nothing, it's just broken now.

![Screenshot](https://snipboard.io/Eb0xgw.jpg)

Also some weird `D:\Projekte\...`

**Comment by yaroslav-semeniuk** [comment]
`settings.xml` was corrupted. Deleted and launched the app - now working.

**Comment by hooke007** [comment]
`D:\Projekte\...`

Not weird. stax76 built it from this location
