### ISSUE TITLE
libmpv dll have been renamed mpv-2.dll

### ISSUE THREAD

**Issue by zhongfly** [stax76/mpv.net#356]
After https://github.com/mpv-player/mpv/commit/f9fd50c6546f2fa510251267d6423d3f342ca115 , the mpv-1.dll have been renamed mpv-2.dll.
Although I can manually rename the new DLL file to mpv-1.dll, but I still hope mpv.net to use mpv-2.dll directly.

Shinchiro didn't update yet,but you can try my [build]( https://github.com/zhongfly/mpv-winbuild/releases/tag/2021-12-16 ).It use the same toolchain as shinchiro's.

_update:Shinchiro have released new version now_

**Comment by stax76** [comment]
Thanks to @zhongfly and @hooke007, it's fixed in the next build.
