### ISSUE TITLE
Discord Rich Presence

### ISSUE THREAD

**Issue by HxxThSwggr** [stax76/mpv.net#360]
Make discord show a status when you are playing something in mpv.

> Playing **mpv.net**
> The Room
> 30:01 elapsed

Or anything like that. Customizable like the osd-playing-msg would be even better.

I don't have a clue how hard it is to do and it's a small stupid thing, but I thought it would be cool.

**Comment by BhaturaGuy** [comment]
There are multiple scripts on github for that:
https://github.com/tnychn/mpv-discord
https://github.com/noaione/mpv-discordRPC
https://github.com/cniw/mpv-discordRPC

**Comment by emhelmark** [comment]
I can't make these multiple scripts to work.
