### ISSUE TITLE
[feature] supporting HEVC (x265) codec

### ISSUE THREAD

**Issue by kkdd** [stax76/mpv.net#361]
Hello,
Could you support HEVC (x265) codec in mpv.net?

**Comment by rapdodge** [comment]
I can playback it smoothly with mpv-net
![image](https://user-images.githubusercontent.com/33513626/150492226-2690f60e-d8d0-433b-a1f9-28af63e8cf4e.png)

**Comment by hooke007** [comment]
x265 is an encoder.
Not sure what you want.
