### ISSUE TITLE
Cycle pause with rightclick

### ISSUE THREAD

**Issue by Topsii** [stax76/mpv.net#362]
I installed mpv.net via the app store today.

You can cycle pause with space.
I want to additionally be able to cycle pause with right click.
Currently right click is used to open the context menu. So I would have to change that, e.g. to Ctrl + Rightclick or something else.
How can I do that?
 
My problems are:
I cannot bind that keybinding to rightclick.
I cannot change the keybinding for the context menu.

**Comment by stax76** [comment]
This scenario is unsupported, right-click will always show the menu.

It might be possible to change this, but the use case is too special, and because of that I don't want to spend time for it.
