### ISSUE TITLE
How to automatically load subtitle for another language?

### ISSUE THREAD

**Issue by merakian2** [stax76/mpv.net#363]
I am trying to set it to auto-load Chinese subtitles in "slan" under settings. The default is English and I have tried using "Chinese", "zh-cn", "cn", "zhs", etc. None of them works and mpv.net is still loading English subtitles.

**Comment by hooke007** [comment]
https://github.com/hooke007/MPV_lazy/blob/df79f0b70d8bd1e1a44c2763af234f1ca06a25d6/portable_config/mpv.conf#L247-L248
