### ISSUE TITLE
Cannot enable hqdn3d by default. "vf=hqdn3d", "vf=lavfi=hqdn3d" and "vf=lavfi-hqdn3d"... not working on mpv.conf

### ISSUE THREAD

**Issue by ThomasEricB** [stax76/mpv.net#365]
I've been trying to enable the denoise video filter hqdn3d by default, however even though it's listed in VF filters I cannot enable hqdn3d.  **(Source from some of the commands: https://emby.media/community/index.php?/topic/77607-solved-shuffle-problems-w-external-player-tweaking-ets-native-player-enabling-svp-in-native-player/page/2/)**

**To Reproduce**
1. Adding any of the following on mpv.conf (not at once!): 
```vf=hqdn3d 
vf=hqdn3d:luma_spatial=20.0:chroma_spatial=20.0:chroma_tmp=0.01:luma_tmp=0.01
vf=lavfi=hqdn3d 
vf=lavfi-hqdn3d
vf=lavfi-hqdn3d:luma_spatial=5.0:chroma_spatial=5.0:chroma_tmp=1.75:luma_tmp=1.75
vf=lavfi=graph=lavfi-hqdn3d
vf=lavfi=graph=hqdn3d
vf-add=lavfi=graph=[lavfi-hqdn3d]
vf-add=lavfi=graph="lavfi-hqdn3d" 
vf-add=lavfi=graph="hqdn3d" 
vf-add=@hqdn3d:lavfi=graph="lavfi-hqdn3d" 
vf=pp=[hqdn3d=luma_spatial=5.0:chroma_spatial=5.0:chroma_tmp=1.75:luma_tmp=1.75]
vf-add=[hqdn3d=luma_spatial=5.0:chroma_spatial=5.0:chroma_tmp=1.75:luma_tmp=1.75]
lavfi-complex="hqdn3d:luma_spatial=5.0:chroma_spatial=5.0:chroma_tmp=1.75:luma_tmp=1.75"
vf-append=lavfi='lavfi-hqdn3d:luma_spatial=5.0:chroma_spatial=5.0:chroma_tmp=1.75:luma_tmp=1.75'
[and much more...]

And variations using [], "", ''...
```

2. No filters applied/ Nothing referenced on console in most cases

**Expected behavior**
The denoise filter should be working, as it's listed on --vf=help command:

```
Available libavfilter filters:
 hqdn3d           Apply a High Quality 3D Denoiser.
```

Current mpv.conf at https://github.com/ThomasEricB/Mpv.Net-HQ-Config/blob/main/mpv.conf

**Comment by hooke007** [comment]
Test by default config and it works well here.
![Snipaste_2022-01-31_04-45-43](https://user-images.githubusercontent.com/41094733/151740331-22050915-57bc-4d5f-ab17-c16d8c3624de.jpg)

**Comment by ThomasEricB** [comment]
> Test by default config and it works well here.

Well it's not working with my .conf file here for some reason... That's the whole point... Besides, what command did you use in your mpv.conf? 

![mpvnet_qLflykw6CC](https://user-images.githubusercontent.com/9662095/151741098-013e59a2-e08d-47d0-b4b8-945ffa43519e.png)

**Comment by ThomasEricB** [comment]
I've been enabling it with the Cycle Denoise.lua, because this is not working, thus why I am opening this issue... 
![mpvnet_qLflykw6CC](https://user-images.githubusercontent.com/9662095/151741332-3c9daa4a-2ac6-43d0-9790-d891d684b413.png)

**Comment by hooke007** [comment]
just a simple `vf=hqdn3d`

Usually it wouldn't be related with a frontend, because mpvnet is not a mpv's fork, and no source codes was modified about filters.
I assume it would share the same behaviour with mpv, you'd better check the the error in your conf or report to mpv if it do necessary.

**Comment by ThomasEricB** [comment]
> just a simple `vf=hqdn3d`

First, I don't think that's using lavfi's hqdn3d, but besides, the issue here is that something in my mpv.conf or vapoursynth or my script setup is not allowing the video filter to apply...

**Comment by hooke007** [comment]
I'm not interested in arguing the usage of vf.

Anyway, no bugs here in mpvnet.

**Comment by ThomasEricB** [comment]
> Anyway, no bugs here in mpvnet.

How do you know that? Have you tried my mpv.conf?

**Comment by hooke007** [comment]
> because mpvnet is not a mpv's fork, and no source codes was modified about filters.

> you'd better check the the error in your conf or report to mpv if it do necessary.
