### ISSUE TITLE
how to play RTSP stream on this windows version?

### ISSUE THREAD

**Issue by G2G2G2G** [stax76/mpv.net#367]
On linux you can run:
mpv 'rtsp://user:pass@192.168.0.44:554/s0'

which works fine, for example.
This doesn't seem to work with the "u" hotkey or the "open url from file or path" thing

NVM it works on command prompt for some reason, but not int he URL thing..

**Comment by G2G2G2G** [comment]
actually I think this is a bug then, so I'll leave this open. Close it if you want?

**Comment by stax76** [comment]
The next beta registers the protocol.

**Comment by stax76** [comment]
It should be fixed in the last beta:

https://github.com/stax76/mpv.net/releases
