### ISSUE TITLE
SRT Stream Protocol Support

### ISSUE THREAD

**Issue by fmohican** [stax76/mpv.net#369]
Hello
Would be great if we he have native SRT support.

SRT is low-latency streaming protocol developed by _SRT Alliance_. The founding members of the alliance are [Haivision](https://en.wikipedia.org/wiki/Haivision) and [Wowza](https://en.wikipedia.org/wiki/Wowza_Streaming_Engine)

SRT is UDP based protocol witch is supported native by FFPlay ([FFMPEG)](https://ffmpeg.org/ffmpeg-protocols.html#srt)

Thanks you.

**Comment by zhongfly** [comment]
mpv already supports it, maybe it's just that mpv.net doesn't support this link format,like https://github.com/stax76/mpv.net/issues/367

**Comment by stax76** [comment]
The next beta registers the protocol.

**Comment by fmohican** [comment]
nice thanks!

sâm., 5 mar. 2022, 04:55 stax76 ***@***.***> a scris:

**Comment by stax76** [comment]
It should be fixed in the last beta:

https://github.com/stax76/mpv.net/releases

**Comment by fmohican** [comment]
thanks I will try out asap.

sâm., 5 mar. 2022, 16:34 stax76 ***@***.***> a scris:
