### ISSUE TITLE
Autofit empty value behavior. Autofit-larger implementation needed.

### ISSUE THREAD

**Issue by derude50** [stax76/mpv.net#37]
Current behavior: An empty autofit value defaults to a window size of 50% of the monitor size. No option available for the window to automatically open at the video's native resolution, and no option to prevent the native resolution window option from extending past the monitor's edges.

Expected behavior: If no value is set in autofit, MPV.net should automatically size the window to the video's native resolution size. Autofit-larger or similar implementation is also required to prevent the native resolution window size from extending past the monitor's edge (if the video's native resolution is larger than the monitor's resolution). Must take into account borders being on or off.

**Comment by stax76** [comment]
Thanks for the feedback. To be honest I'm not exited to implement this, is it likely that I still try to implement it, yes it is.

**Comment by stax76** [comment]
I've added a new setting called remember-height:

mpv.net specific setting to remember the window height.

If it's disabled then the video's native resolution is used.

**Comment by stax76** [comment]
The new release is out.
