### ISSUE TITLE
Context Menu: Group commands with multiple keys into one cell

### ISSUE THREAD

**Issue by microraptor** [stax76/mpv.net#372]
Thank you for packaging mpv up so nicely and adding all the user friendly features!

It would be a good addition to group key bindings together, if the command and context menu string are exactly the same.

For example these are the default volume options:

```
+           add volume  2          #menu: Volume > Up
-           add volume -2          #menu: Volume > Down
0           add volume  2          #menu: Volume > Up
9           add volume -2          #menu: Volume > Down
```

Which are displayed in the volume menu like this:

```
Up      + 
Down    -
Up      0 
Down    9
```

Grouping them like this would make things cleaner:

```
Up    +,0
Down  -,9
```

**Comment by hooke007** [comment]
It's mpv's limitation.

**Comment by microraptor** [comment]
I am not entirely sure what you mean. I would not change the input.conf syntax in any way. When mpv.net notices, that there are two lines with the exact same command and the exact same menu name comment, but with a different key, then it groups the key in the same menu item, instead of making two like in the example above.

For this it should be checked if the command string matches exactly and is not just similar. As far as I know, key bindings are always over riden if the same key is used twice. So it is never mapped to multiple commands.

**Comment by hooke007** [comment]
that is what I said 
> or just simply group keys by the same comments.

**Comment by microraptor** [comment]
Sorry about that, now I understand. Personally, I think grouping should only happen, if the command string (which contains one or multiple commands) matches exactly. Even a no-osd prefix should stop commands grouping together.

**Comment by stax76** [comment]
It would be a small improvement, but too small justifying spending the time to build it.

Maybe request it on the mpv tracker:

key1|key2|key3 cmd1;cmd2

**Comment by microraptor** [comment]
That is understandable, it would be only a visual improvement. Not sure, if the mpv feature  would be an improvement though. The multiline syntax to achieve the same thing already exists and might be less complicated.

**Comment by stax76** [comment]
Supported in the next release.
