### ISSUE TITLE
“Setup...” unresponsible in 5.6.1.0 beta

### ISSUE THREAD

**Issue by nkh0472** [stax76/mpv.net#377]
**To Reproduce**
1. Go to main interface
2. Right click
3. Go to 'Tools'
4. Click on 'Setup...'
5. Nothing happened

**Expected behavior**
Open the 'Setup' windows to registry it as the default media player.

**Additional context**
Version 5.6.1.0 beta. (Earlier released version is normal until this beta version.)
Using `mpvnet.com` to show command line output during above steps, and here is the full output:
```
[mpv.net] unknown mpvnet.conf property: update-check
[input] No key binding found for key 'MBTN_LEFT'.
[mpv.net] No command 'show-setup-dialog' found.
```

**Comment by nkh0472** [comment]
PS: The dll library `MediaInfo.dll` can be updated to version 21.9.0.0.

**Comment by stax76** [comment]
> Please be aware that once input.conf exists, mpv.net cannot update it, this means the menu becomes outdated when mpv.net is updated with new or changed default menu items. The only way to get an up-to-date menu is either resetting the menu by deleting input.conf or updating it by manually editing input.conf.

I thought very hard about this issue lately, and did not find a way to improve the situation.

https://github.com/stax76/mpv.net/blob/master/docs/Manual.md#input-and-context-menu

**Comment by dyphire** [comment]
Because behavior has changed, see: https://github.com/stax76/mpv.net/commit/4efe85aad7bf72d7d1a1adda889c11a1af9d5d71. 
You should use the new file of input.conf.

**Comment by nkh0472** [comment]
> > Please be aware that once input.conf exists, mpv.net cannot update it, this means the menu becomes outdated when mpv.net is updated with new or changed default menu items. The only way to get an up-to-date menu is either resetting the menu by deleting input.conf or updating it by manually editing input.conf.
> 
> I thought very hard about this issue lately, and did not find a way to improve the situation.


Such a breaking change should put a notice on the release note. And maybe a notification message should be popup when detecting an older version conf file.

**Comment by nkh0472** [comment]
When making such an incompatible update, I recommend you raise the major version number of the software, as we usually see in the [semantic versioning](https://semver.org/).

**Comment by stax76** [comment]
It's always a little painful to release something and then find out it has issues, so I uploaded it again with applied fixes.

5.6.2.0 Beta (2022-03-05)

- Fix script-opts files being ignored, removed options are:
  script-opts = osc-scalewindowed=1.5,osc-hidetimeout=2000,console-scale=1.5
- Update MediaInfo to version 21.9.0.0 and
  write version and date in About dialog.
- Provide setup options in command palette to ensure backward
  compatibility with previous input.conf definitions.

https://github.com/stax76/mpv.net/releases
