### ISSUE TITLE
Playlist Feature

### ISSUE THREAD

**Issue by zettimetti** [stax76/mpv.net#378]
This template is meant for usage questions of mpv.net.
Hello.

Do the playlist feature work similar to other players or in another way?

**Comment by stax76** [comment]
There isn't a UI for the playlist, at least not built-in, except for the command palette, which only allows to select which entry to play.

Some creative ways exist to achieve various playlist related task, for instance there is a script that allows to delete the file that is currently playing:

https://github.com/stax76/mpv.net/blob/master/src/Scripts/Lua/delete-current-file.lua

I recommend to search 'playlist' in the manual:

https://github.com/stax76/mpv.net/blob/master/docs/Manual.md

And google 'mpv playlist script'.

**Comment by zettimetti** [comment]
Right i will look into it.

**Comment by zettimetti** [comment]
Change process-instance from single to queue also remap playlist-prev and playlist-next is what i needed.

Many thanks.
