### ISSUE TITLE
Behaviour when opening (multiple) files from windows explorer

### ISSUE THREAD

**Issue by 44vince44** [stax76/mpv.net#38]
Hi Stax,
After playing a lot with mpv.net, I really find it totally fulfilling (and don't miss at all the older players I used before ;-), and I guess I would have two last requests if possible:

_Request 1: multiselection from explorer_

Actual behavior:
When selecting 1 file and press enter or double click, mpv.net opens and sets folder as playlist
When selecting multiple files and press enter, mpv.net opens and sets folder as playlist 

Wished behavior (if possible):
When selecting 1 file and press enter or double click, mpv.net opens and sets folder as playlist <-OK!
When selecting multiple files and press enter, mpv.net opens and sets **selected files** as playlist

_Request 2: folder sorting_
Shouldn't be explected that if mpv.net is started from a folder of media that is sorted in a certain way (by name, by size, by date etc), then the playlist is set as the folder with the same sorting order?
   

And again, thanks for the great work!!

**Comment by stax76** [comment]
> When selecting 1 file and press enter or double click, mpv.net opens and sets folder as playlist <-OK!
> When selecting multiple files and press enter, mpv.net opens and sets selected files as playlist

I don't know how to do that because to my knowledge explorer will always start a new process for every file and working around that is likely gonna be very hard. I might have suggested this before, use 'Open with++'.

> Shouldn't be explected that if mpv.net is started from a folder of media that is sorted in a certain way (by name, by size, by date etc), then the playlist is set as the folder with the same sorting order?

I've coded an image viewer that supports this and it works reliable but there is no clean way to achieve this, I can share the code or maybe on a good day write a script.

**Comment by 44vince44** [comment]
> I don't know how to do that because to my knowledge explorer will always start a new process for every file and working around that is likely gonna be very hard. I might have suggested this before, use 'Open with++'.

If Open with ++ can handle the program that is launched directly with enter or double click, I'll go for it immediately. Does it do so?

**Comment by stax76** [comment]
Open with++ supports only the context menu.

I rewrote a bunch of code today hoping for a miracle that I can make your request work, the miracle did not happen. :-)

Problem is the order is mixed, I don't have control over this, explorer creates for every file a new process, that happens in parallel...

To my knowledge it's not possible to tell explorer that all files should be passed to a single process.

If you use Open with++ only one process is created and your order is exactly like in explorer and the active file is the one under the mouse cursor.
