### ISSUE TITLE
Would it be possible to include a MediaInfo option in mpv.net's context menu (à la MPC-HC) to lookup file metadata?

### ISSUE THREAD

**Issue by NomaanMalick** [stax76/mpv.net#383]
I was wondering whether it would be possible to include a MediaInfo option in mpv.net's context menu (à la MPC-HC) to lookup file metadata?
![MediaArea net_MediaInfo - C__Users_Nomaan_Videos_Yoshinori Kanada (金田伊功) - 70th birthday Sakuga MAD mp4 3_10_2022 12_56_55 AM (2)](https://user-images.githubusercontent.com/46681247/157517585-98bcb3ce-c6bd-4616-b1a2-85a33cdb82ef.png)

**Comment by stax76** [comment]
No problem.

MediaInfo in my opinion isn't a great GUI, I suggest this instead:

https://github.com/stax76/MediaInfo.NET

MediaInfo is integrated:

https://github.com/stax76/mpv.net/blob/master/src/Resources/input.conf.txt#L127

It can be customized with an input command and property expansion:

`ctrl+m run D:\MediaInfo.NET\MediaInfoNET.exe "${path}" #menu: Tools > Open file with MediaInfo.NET`

The run input command:

https://mpv.io/manual/master/#command-interface-[-]]]

**Comment by NomaanMalick** [comment]
> No problem.
> 
> MediaInfo in my opinion isn't a great GUI, I suggest this instead:
> 
> https://github.com/stax76/MediaInfo.NET
> 
> MediaInfo is integrated:
> 
> https://github.com/stax76/mpv.net/blob/master/src/Resources/input.conf.txt#L127
> 
> It can be customized with an input command and property expansion:
> 
> `ctrl+m run D:\MediaInfo.NET\MediaInfoNET.exe "${path}" #menu: Tools > Open file with MediaInfo.NET`
> 
> The run input command:
> 
> [https://mpv.io/manual/master/#command-interface-[-]]]](https://mpv.io/manual/master/#command-interface-%5B-%5D%5D%5D)

Sorry, I am new to this. I don't understand what to do with `ctrl+m run D:\MediaInfo.NET\MediaInfoNET.exe "${path}" #menu: Tools > Open file with MediaInfo.NET`. Do I put it in the config file?

**Comment by stax76** [comment]
You put it in the input.conf file.

**Comment by NomaanMalick** [comment]
I don't seem to have a input.conf file in my mpv folder. Should I create it manually?

![mpv net-5 7 0 0 3_25_2022 12_05_08 AM](https://user-images.githubusercontent.com/46681247/159986842-cf6e6aab-96dd-4aa1-8817-91a99672224e.png)

**Comment by stax76** [comment]
You can open the folder in the menu at:

Settings > Open Config Folder

Please take a look in the manual:

https://github.com/stax76/mpv.net/blob/master/docs/Manual.md#input-and-context-menu

**Comment by NomaanMalick** [comment]
> You can open the folder in the menu at:
> 
> Settings > Open Config Folder
> 
> Please take a look in the manual:
> 
> https://github.com/stax76/mpv.net/blob/master/docs/Manual.md#input-and-context-menu

Thank you very much!

![input conf - WordPad 3_25_2022 10_51_01 AM](https://user-images.githubusercontent.com/46681247/160059653-4937b250-99fc-4c07-9a3e-5a49d8a53aee.png)

**Comment by NomaanMalick** [comment]
It doesn't seem to work.

https://user-images.githubusercontent.com/46681247/160069988-befb9c12-c976-43f1-aed1-57337fa414fe.mp4

**Comment by stax76** [comment]
Yes, MediaInfo works only with files. For streams, you can get media info by using the built-in Statistics script. To find the key binding, press F1 to show the command palette, search for 'stat', in the command palette on the right sight you can see the key binding, it should be **t** or **T**.

**Comment by NomaanMalick** [comment]
Thank you very much for your help!

**Comment by NomaanMalick** [comment]
This is probably a noob question to ask but in `ctrl+m run D:\MediaInfo.NET\MediaInfoNET.exe "${path}" #menu: Tools > Open file with MediaInfo.NET`, did I need to change `D:\MediaInfo.NET\MediaInfoNET.exe` to the location of MediaInfot.NET on my PC and add that location to PATH to get it to work with mpv.net? Sorry to bother you again.
https://user-images.githubusercontent.com/46681247/161421355-8a7e4243-ed28-4ee4-90c6-8c79b6fd3edb.mp4

**Comment by stax76** [comment]
In case of problems, it can help to start mpv.net from a terminal and check if it prints errors. When it's a full path you don't have to add it to PATH, when it's not working you can try to use forward instead of backward slashes, that is usually supported by Windows and can avoid problems with C escape sequences, or try double backslashes to escape the single backslashes, and enclose everything with single or double quotes, it's often trial and error to find correct string and path rules.

**Comment by NomaanMalick** [comment]
> In case of problems, it can help to start mpv.net from a terminal and check if it prints errors. When it's a full path you don't have to add it to PATH, when it's not working you can try to use forward instead of backward slashes, that is usually supported by Windows and can avoid problems with C escape sequences, or try double backslashes to escape the single backslashes, and enclose everything with single or double quotes, it's often trial and error to find correct string and path rules.

Thank you! I got it to work. 

BTW, is it not possible to open two separate windows of mpv.net simultaneously?

**Comment by stax76** [comment]
> is it not possible to open two separate windows of mpv.net simultaneously?

There is a setting `process-instance` for that.

**Comment by NomaanMalick** [comment]
Thank you very much!
