### ISSUE TITLE
Error dialog pops up when playing zip file

### ISSUE THREAD

**Issue by Yaya55** [stax76/mpv.net#385]
**Describe the bug**
When you drag-and-drop a zip file containing a video file into the mpv.net window I get an error dialog that says, "The path contains invalid characters."
If you start mpv.net from the command line, the following message is output to the console.

[mpv.net] System.ArgumentException: パスに無効な文字が含まれています。
   場所 System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   場所 System.IO.Path.GetExtension(String path)
   場所 PathStringExtension.Ext(String instance) 場所 D:\Projects\CS\mpv.net\src\Misc\ExtensionMethods.cs:行 77
   場所 mpvnet.CorePlayer.EventLoop() 場所 D:\Projects\CS\mpv.net\src\Misc\CorePlayer.cs:行 472

**To Reproduce**
1. Start mpv.net.
2. Drag and drop the zip file containing the video into the mpv.net window.

test.zip
  +--- video.mp4

**Expected behavior**
Play the video in the zip file without popping up an error dialog.

**Screenshots**
![mpv_error](https://user-images.githubusercontent.com/32816463/157910545-ad5ad9d8-e264-4779-8d98-79095add927e.jpg)

**Additional context**
The original MPV does not have this problem.

**Comment by stax76** [comment]
Thanks for the bug report, it will be fixed in the next release.

**Comment by Yaya55** [comment]
I have confirmed that it is fixed in v5.8.0.0. Thank you very much.
