### ISSUE TITLE
mpv.net does not respect auto-play setting

### ISSUE THREAD

**Issue by noelforte** [stax76/mpv.net#389]
**Describe the bug**
mpv.net includes an `auto-play` setting that is set to "no" by default, yet when opening any video or audio file the player will always start auto-playing the opened file

**To Reproduce**
1. Open mpv.net
2. Open config editor
3. Ensure "auto-play" is set to no
4. Open a video or audio file

**Expected behavior**
mpv.net pauses playback on opening the file, ensuring that the setting is respected

**Actual behavior**
mpv.net starts playback automatically, no matter what auto-play is set to

**Additional context**
mpv.net is version 5.7.0.0
OS is Windows 10 21H2, Build 19044.1586

**Comment by hooke007** [comment]
> when opening any video or audio file the player will always start auto-playing the opened file

It's mpv's default behaviour.

**Comment by noelforte** [comment]
@hooke007 Got it, thanks for the info!
