### ISSUE TITLE
small error in changelist (about multiselect)

### ISSUE THREAD

**Issue by 44vince44** [stax76/mpv.net#39]
Dear Stax, the feature you added in 4.6:
"when multiple files are selected in Windows File Explorer and enter is
pressed, the files are opened as selected, the order is random though
because Explorer starts multiple mpv.net processes concurrently"

it's not with Enter, but Ctrl+Enter,  right ?
Thanks for all the nice improvements, as usual :-)

**Comment by stax76** [comment]
Hi, it's enter, I hope it works.

**Comment by 44vince44** [comment]
Enter is not working, but Ctrl+Enter is working, lol!!!

**Comment by stax76** [comment]
It's working on my machine! There is not much I can do.

**Comment by 44vince44** [comment]
no need to do anything: Ctrl+enter is working here and is fine for me :))))
