### ISSUE TITLE
Automatically resize the mpv.net window to the resolution of the playing video.

### ISSUE THREAD

**Issue by NomaanMalick** [stax76/mpv.net#391]
**Is your feature request related to a problem? Please describe.**
When I play video files with the mpv.net media player, the window remains in the default zoom level. So, I have to manually change the zoom level to 100 percent to have the player window fit the video resolution. 

Default window size:
![2022-03-23 13_34_11-Greenshot](https://user-images.githubusercontent.com/46681247/159651904-b19fbebf-80ca-42cf-960d-3b82fff27810.png)

Zoom: 100 percent
![2022-03-23 13_34_54-Greenshot](https://user-images.githubusercontent.com/46681247/159651992-070699bd-162a-42bf-b2c4-fa598b1c6a9b.png)

**Describe the solution you'd like**
I would like the mpv.net player to automatically adjust the window scale to the resolution of the video.

**Comment by KaranKad** [comment]
If you want mpv.net to open in maximized mode by default add `window-maximized=yes` to your mpv.conf file.

**Comment by NomaanMalick** [comment]
> https://github.com/stax76/mpv.net/blob/master/docs/Manual.md#--start-sizevalue So `video` didn't work for you?

Like this:
![mpvnet exe config - Notepad 3_24_2022 11_35_58 AM](https://user-images.githubusercontent.com/46681247/159852916-a1224f9a-0ffe-4ebf-b82d-be63ecf6066b.png)

It doesn't seem to be working though.

**Comment by NomaanMalick** [comment]
Thank you very much, both of you.

**Comment by lyturn** [comment]
‘Window size is set to video resolution'  Is it set up like this? start-size=video

**Comment by stax76** [comment]
I think yes, but goes in mpvnet.conf and not mpv.conf because the feature is mpv.net specific, better use the search feature in the conf editor.

**Comment by hooke007** [comment]
what's your `autofit` values?

**Comment by lyturn** [comment]
autofit=100%, still not working.

**Comment by hooke007** [comment]
what's your autofit-larger and displayres?

**Comment by lyturn** [comment]
Mine is 1440x900.

**Comment by stax76** [comment]
Some things are only partly or differently implemented, which is only documented in the conf editor.

**Comment by hooke007** [comment]
900 height means you cannot avoid 1080p video's resizing.

**Comment by stax76** [comment]
Please provide a better description and if necessary post screenshots or a screen capture.
