### ISSUE TITLE
mpv.net doesn't display subtitles.

### ISSUE THREAD

**Issue by NomaanMalick** [stax76/mpv.net#392]
**Describe the bug**
I just streamed [this file](https://s4.gamesdrive.net/0:/The.Bad.Kids.2020.WEB-DL.1080p.H265.AAC-DanNi/The.Bad.Kids.2020.E01.WEB-DL.1080p.H265.AAC-DanNi.mkv) with mpv.net and for some reason, the player displays none of the included subtitles tracks.

**To Reproduce**
1. Open [this URL](https://s4.gamesdrive.net/0:/The.Bad.Kids.2020.WEB-DL.1080p.H265.AAC-DanNi/The.Bad.Kids.2020.E01.WEB-DL.1080p.H265.AAC-DanNi.mkv) with mpv.net.
2. Check the included subtitle tracks.
3. Select one of them.
4. See that the player doesn't display any of them.

**Expected behavior**
I expected the player to display the selected subtitle track.

**Screenshots**

![The Bad Kids 2020 E01 WEB-DL 1080p H265 AAC-DanNi mkv - mpv net 3_23_2022 12_58_04 PM](https://user-images.githubusercontent.com/46681247/159774981-d6122f2d-696d-419c-abd4-3b120258b191.png)

![The Bad Kids 2020 E01 WEB-DL 1080p H265 AAC-DanNi mkv - mpv net 3_23_2022 12_58_07 PM](https://user-images.githubusercontent.com/46681247/159774998-09ca0039-473a-49b5-9ae3-f6a524856c35.png)

![The Bad Kids 2020 E01 WEB-DL 1080p H265 AAC-DanNi mkv - mpv net 3_23_2022 12_58_13 PM](https://user-images.githubusercontent.com/46681247/159775008-de8493ee-b046-486f-8c1e-be87c4cfd39f.png)

![The Bad Kids 2020 E01 WEB-DL 1080p H265 AAC-DanNi mkv - mpv net 3_23_2022 12_58_15 PM](https://user-images.githubusercontent.com/46681247/159775018-7a8fa9ad-f3ed-423e-9eef-e749c5d8052e.png)

**Comment by stax76** [comment]
I can reproduce it with a mpv build compiled today, it's either an upstream mpv issue or there is something wrong with the stream.

**Comment by hooke007** [comment]
It's weird that these WEBVTT subtitle files are ended with `.webvtt` , which leads that mpv could not recongnize. Renaming to `.vtt` fixed the problem. I am not sure how mpv handle vtt sub, but it looks like the video-repacker made the mistake.

**Comment by dyphire** [comment]
> It's weird that these WEBVTT subtitle files are ended with `.webvtt` , which leads that mpv could not recongnize. Renaming to `.vtt` fixed the problem. I am not sure how mpv handle vtt sub, but it looks like the video-repacker made the mistake.

Looks like an extension error. https://en.wikipedia.org/wiki/WebVTT

**Comment by NomaanMalick** [comment]
> > It's weird that these WEBVTT subtitle files are ended with `.webvtt` , which leads that mpv could not recongnize. Renaming to `.vtt` fixed the problem. I am not sure how mpv handle vtt sub, but it looks like the video-repacker made the mistake.
> 
> Looks like an extension error. https://en.wikipedia.org/wiki/WebVTT
> 
> And I also found that only MPC-HC can correctly recognize the subtitle format and display it, which can not be done by other players.

That's a shame because MPC-HC keeps displaying the following error message whenever I try to use it for streaming.
https://user-images.githubusercontent.com/46681247/146397962-b48511db-3642-49a4-a74f-c9711bcd8a14.png

**Comment by hooke007** [comment]
> That's a shame because MPC-HC keeps displaying the following error message whenever I try to use it for streaming.

Then you should report it to the [correct tracker](https://github.com/clsid2/mpc-hc/issues) , not here.

**Comment by NomaanMalick** [comment]
> > That's a shame because MPC-HC keeps displaying the following error message whenever I try to use it for streaming.
> 
> Then you should report it to the [correct tracker](https://github.com/clsid2/mpc-hc/issues) , not here.

I already did that three or four months back, but couldn't find a solution. Here is the [thread](https://github.com/clsid2/mpc-hc/issues/1451).
