### ISSUE TITLE
MPV.net doesn't recognize the press of the media play/pause if the window is not in focus.

### ISSUE THREAD

**Issue by Tosh0kan** [stax76/mpv.net#393]
**Describe the bug**
If the MPV.net window is in focus, the media keys work fine, but if anything else is in focus instead, it doesn't work.

**To Reproduce**
1. Open a movie file on MPV.net.
2. Move it to your side monitor and/or focus another window that isn't it
3. Press the multimedia key "Play/Pause"
4. The MPV.net player does nothing.

**Expected behavior**
Press the play/pause button with MPV.net open but with another window on focus

**Comment by BhaturaGuy** [comment]
it's a mpv issue. Though this might help you: https://github.com/x0wllaar/MPV-SMTC

**Comment by Tosh0kan** [comment]
Didn't work.

**Comment by Tosh0kan** [comment]
Worked. Thank you.

**Comment by stax76** [comment]
I don't have experience with SMTC, it's something I want to investigate when I have time.

There is, however, general support for global keys in mpv.net, the configuration for it uses the file `global-input.conf`.

Besides that, another useful tool is AutoHotkey, which I use myself, not for media keys, but for global keys in general.
