### ISSUE TITLE
Right click pause / remap context menu

### ISSUE THREAD

**Issue by jak3-taylor** [stax76/mpv.net#396]
Someone brought up this topic before in a closed issue - https://github.com/stax76/mpv.net/issues/362

It was said that right click pause is too special of a use case, but isn't right click pause the default in the original mpv that this great work is based on?

https://mpv.io/manual/master/#mouse-control
>Right click
>    Toggle pause on/off.

I'd love the ability to remap the context menu to MBTN_Mid, if it was ever possible.

Thank you.

**Comment by stax76** [comment]
It's supported in the next build.
