### ISSUE TITLE
Keyboard layout breaks hotkeys

### ISSUE THREAD

**Issue by A-tG** [stax76/mpv.net#398]
version 5.7.0.0 from MS Store
Windows 10 21H1

If mpv is launched while non-English keyboard layout is active (Russian layout in my case) it will not respond to keys (like a, z, ~), even after switching to English layout. Only restart helps.

**Comment by stax76** [comment]
Do you know an open source application not having this problem? If so, I can look in the source code for a solution, or maybe it's currently not possible doing something better.

**Comment by A-tG** [comment]
To be clear if it **launched first** with English active layout, it works just fine with Russian layout too.
A few opens source projects that seems dont have problems with layout: 
https://github.com/JasonStein/Notepads
https://github.com/files-community/Files
and cpp 
https://github.com/KDE/krita

**Comment by stax76** [comment]
I looked and didn't find any special keyboard code in Files and Notepads, both are likely UWP based, which could make a difference.

However, I switched the keyboard language using ALT+SHIFT and also using WIN+SPACE while mpv.net is active, and mpv.net reacted to the change. This is Windows 11. Unless another developer helps, I really don't know what to do here.

**Comment by A-tG** [comment]
Once again it's not about switching keyboard language, it' about program being launched with specific language:

Not ok:
1. Russian keyboard language is selected (or probably any Cyrillic language)
2. mpvnet is launched
3. I press ` to open console (or any other letter key: a, i) - nothing happens
4. I switch keyboard language to English with any method (win + space, alt + shift, or by clicking the icon in taskbar)
5. repeat 3 - nothing happens
6. I have to exit the program

ok:
1. English keyboard language is selected
2. mpvnet is launched
3. I press ` - console is opened, every key is working
4. I switch keyboard language to Russian
5. repeat 3 - everything is working

Something breaking at program start

**Comment by stax76** [comment]
I can now reproduce it, but haven't yet found a solution.

**Comment by stax76** [comment]
Difficult issue it seems, it might take a while until I find a solution.

**Comment by stax76** [comment]
Unfortunately, I cannot find the reason, so I have to ask mpv developers.

**Comment by A-tG** [comment]
If it helps when I launch mpvnet from command line, I see 
```
[input] No key binding found for key 'ё'.
```
when I press ` ('ё' in Russian layout) so its like getting stuck with with Russian layout if launched with it.
I'll also check if MPV have same problem.

**Comment by stax76** [comment]
I've already checked that, mpv is not having this issue.

**Comment by stax76** [comment]
I made a support request on the mpv tracker, waiting for help now.

**Comment by stax76** [comment]
It's finally making progress.

**Comment by stax76** [comment]
Finally, fixed.

**Comment by stax76** [comment]
Find a hotfix to download here:
[mpvnet-hotfix.zip](https://github.com/stax76/mpv.net/files/8456350/mpvnet-hotfix.zip)

**Comment by A-tG** [comment]
Seems working. Though it would be nice to have ability to handle hotkeys (as English layout) regardless of current layout, if it even possible to implement.

**Comment by stax76** [comment]
I don't know if there is an easy way, only changing the layout, for instance with [ActivateKeyboardLayout](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-activatekeyboardlayout).

There is a property [input-bindings](https://mpv.io/manual/master/#command-interface-input-bindings) which can get you all bindings in JSON format. That could be analyzed and used to generate additional bindings with non-western characters, for that there is an input command [keybind](https://mpv.io/manual/master/#command-interface-keybind-%3Cname%3E-%3Ccommand%3E).

Relevant code is here:

https://github.com/stax76/mpv.net/blob/master/src/WPF/LearnWindow.xaml.cs

Another way might be installing a keyboard hook, see [Win32 keyboard hooks](https://docs.microsoft.com/en-us/windows/win32/winmsg/about-hooks).

**Comment by stax76** [comment]
I can try if it's possible to enforce a particular layout, if yes provide an option.

**Comment by stax76** [comment]
I tried the Win32 function ActivateKeyboardLayout, and it changed the system layout and not only the process layout, that means there might not be an easy way to achieve your goal, it can only be done with a lot of work I guess.

Maybe ask somewhere like stackoverflow if you want to be sure, maybe somebody with experience in this area finds the question and answers it.
