### ISSUE TITLE
can't change MBTN_LEFT_DBL function

### ISSUE THREAD

**Issue by fireattack** [stax76/mpv.net#40]
I tried to either remove or change it to other function:

![image](https://user-images.githubusercontent.com/4130991/60799426-bf39fd80-a138-11e9-94af-da3a380219c4.png)

Didn't work either way.

**Comment by stax76** [comment]
Hi, thanks for the feedback, please try a new test build:

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/f/s!ArwKS_ZUR01gySQIE1QCL2i9F_uR

**Comment by stax76** [comment]
I'm closing this issue now because the new release fixes the problem.

https://github.com/stax76/mpv.net/releases

**Comment by fireattack** [comment]
Thanks
