### ISSUE TITLE
How can I support HTTPS streaming video

### ISSUE THREAD

**Issue by sudongg** [stax76/mpv.net#401]
I try to play a HTTPS streaming video, the player is not responding, the video can be played in Chrome.
Maybe it's because mpv doesn't have ssl support?

**Comment by zhongfly** [comment]
It is recommended that you give specific examples and provide detailed logs rather than vague descriptions.
For video sites such as youtube, mpv or mpv.net needs to rely on youtube-dl/yt-dlp to provide parsing, I suggest you read the manual：

> For internet streaming from YouTube and similar sites, yt-dlp must be copied into the mpv.net folder or the user environment variable PATH must be edited to include the yt-dlp folder.

**Comment by sudongg** [comment]
It's a proxy problem. The player doesn't seem to automatically enable the proxy. How to enable it?

**Comment by zhongfly** [comment]
If you want to set proxy for yt-dl,you can add this line to your mpv.conf
```
ytdl-raw-options-append=proxy=http://127.0.0.1:3128
```

**Comment by sudongg** [comment]
It's not yt-dl, it's a normal video, I enable it by adding http-proxy=proxy, but I prefer to automatically detect the proxy and set it

**Comment by zhongfly** [comment]
> It's not yt-dl, it's a normal video, I enable it by adding http-proxy=proxy, but I prefer to automatically detect the proxy and set it

Maybe you can write a lua script to this, https://mpv.io/manual/master/#lua-scripting

**Comment by zhongfly** [comment]
```lua
local mp = require 'mp'

local function pwshexec(command)
    local args = {
        "powershell", "-NoProfile", "-Command"
    }
    table.insert(args,command)

    mp.msg.debug("Running: " .. table.concat(args, " "))

    local ret = mp.command_native({name = "subprocess",
                                   args = args,
                                   playback_only = false,
                                   capture_stdout = true,
                                   capture_stderr = true})
    if ret.killed_by_us or (ret.status ~= 0) then
        return nil
    elseif ret.stdout then
        return ret.stdout
    else
        return nil
    end
end

local function get_proxy()
    local AutoConfigURL = pwshexec([=[(Get-ItemProperty -Path 'Registry::HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings').AutoConfigURL]=])
    mp.msg.debug(AutoConfigURL)
    if AutoConfigURL~="" then
        return AutoConfigURL
    else
        local ProxyEnable = pwshexec([=[(Get-ItemProperty -Path 'Registry::HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings').ProxyEnable]=])
        mp.msg.debug(ProxyEnable)
        if ProxyEnable and ProxyEnable ~= "0" then
            local ProxyServer = pwshexec([=[(Get-ItemProperty -Path 'Registry::HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings').ProxyServer]=])
            mp.msg.debug(ProxyServer)
            return ProxyServer
        end
    end
end

if mp.get_property("http-proxy") then
    local proxy = get_proxy()
    if proxy and proxy~="" then
        mp.set_property("http-proxy",proxy)
        mp.msg.info("Auto set http-proxy:" .. mp.get_property("http-proxy"))
    end
end
```

**Comment by sudongg** [comment]
Thanks, I still hope this feature can be integrated into the player. Not all users know it's a proxy problem.
 When the user's browser can play but the player cannot play, it will be considered as a problem of the player.

**Comment by zhongfly** [comment]
> Thanks, I still hope this feature can be integrated into the player. Not all users know it's a proxy problem. When the user's browser can play but the player cannot play, it will be considered as a problem of the player.

In my opinion, mpv prefers users to add those functions that are not too difficult but not built into the player through scripts.

**Comment by sudongg** [comment]
The popular player mpc and pot on the market will automatically select the correct proxy.
The reason I use mpv.net instead of mpv is because mpv.net is easier to use than mpv.
I believe most of the users who use this player (mpv.net) are regular users rather than player enthusiasts.
When other player can play and mpv.net can't, they just feel that the player doesn't support switching to another player instead of wanting to solve it with a script.

**Comment by stax76** [comment]
I've updated the project description now with this:

> Like mpv, mpv.net targets exclusively power users, there are currently no developers interested in supporting regular users, because this would require a vast amount of work for beginner-friendly features and would generate a large amount of user request.

I'm not happy with the situation, there is just no easy way to fix it. I hope this is acceptable, otherwise I can try to explain it more thoroughly in a dedicated thread.

**Comment by stax76** [comment]
Changed it now to:

> Like mpv, mpv.net is designed for power users, for regular users there is a
> [mpv.net-next](https://github.com/mpv-net-player/mpv.net-next)
> project under construction.

I work on this occasionally, did some research today.

**Comment by sudongg** [comment]
This is good news, but if you want multiple platforms, you may need to change the UI framework. There are not many options, and Avalonia may be the only one.

**Comment by stax76** [comment]
It's now properly documented:

https://github.com/stax76/mpv.net/blob/master/docs/Manual.md#installation

**Comment by ucvyv** [comment]
find the mpv.net folder in the Roaming folder and creat a txt and rename it as "mpv.conf", then write down the "http-proxy=" and "https-proxy=" and it is done.
