### ISSUE TITLE
Fluent/Rounded playback bar

### ISSUE THREAD

**Issue by agentmerlot1412** [stax76/mpv.net#402]
![image](https://user-images.githubusercontent.com/58659715/162487663-420cac4e-5cbb-4ea2-a557-6077be4b0071.png)

This is what the playback bar current looks like. In order to fit with updated Windows 11 guidelines, it would be better to make this a floating bar with rounded corners. (or at least as a togglable option)

**Comment by stax76** [comment]
I don't have plans working in this area, there are alternative OSC scripts, like this:

https://github.com/maoiscat/mpv-osc-morden

**Comment by agentmerlot1412** [comment]
> I don't have plans working in this area, there are alternative OSC scripts, like this:
> 
> https://github.com/maoiscat/mpv-osc-morden

Do you know any other script? This one has the pause/play button bugged

**Comment by stax76** [comment]
Maybe create a bug report.

There is also:

https://github.com/darsain/uosc

https://github.com/torque/mpv-progressbar

I don't think there are more.

Full list of mpv scripts here:

https://github.com/mpv-player/mpv/wiki/User-Scripts

**Comment by agentmerlot1412** [comment]
I looked around and found this fork of the previous one, stuff works on it except a minor issue which I posted on the repo
https://github.com/cyl0/MordenX

Perfect solution, thanks
