### ISSUE TITLE
How to use portable/venv python variant with mpv.net for python scripts?

### ISSUE THREAD

**Issue by RaXorX** [stax76/mpv.net#407]
As the title suggests I want to use a virtual environment or a portable/local instance of python instead of the global environment (system-wide) python.
This is to keep the python modules necessary for the script separate from the global python.

**Comment by hooke007** [comment]
There is no such options in mpv/mpvnet.

**Comment by stax76** [comment]
What exists is vapoursynth support.

https://mpv.io/manual/master/#video-filters-vapoursynth

With the info contained in the following issue, I was able to make it work:

https://github.com/stax76/mpv.net/issues/374

If somebody could write a beginner-friendly tutorial, it would be helpful for users that don't have a programming background.

Using Python to extend mpv would be a welcome features to many users, I think one reason nobody created such a script host is that Lua is very popular among mpv users, Lua is generally considered to be a decent language, which I can confirm.

**Comment by hooke007** [comment]
> I think one reason nobody created such a script host is that Lua is very popular among mpv users, Lua is generally considered to be a decent language, which I can confirm.

They never supported python script. https://github.com/mpv-player/mpv/issues/8755
Also I could not found any python related in the source code. mpv seems only to active vapoursynth. And then VS tried to find the python in your environment.

**Comment by RaXorX** [comment]
My bad. I forgot to mention what script it is. It is the subselect script from https://github.com/zenyd/mpv-scripts
It is indeed a lua script too but has a python script alongside (subliminal is a python module which that script uses)
To make use of that I have to install those modules in the system python otherwise I can't use that script.
