### ISSUE TITLE
Magnet support

### ISSUE THREAD

**Issue by SonaliBendre** [stax76/mpv.net#408]

**Comment by BhaturaGuy** [comment]
Brain damage

**Comment by SonaliBendre** [comment]
I mean mpv.net load magnet link  when pressed 'u'

**Comment by stax76** [comment]
In the latest version, I think it's `ctrl+v`.

**Comment by hooke007** [comment]
No native support in mpv core. Some [3rd party scripts](https://github.com/noctuid/mpv-webtorrent-hook) work on this part.

**Comment by SonaliBendre** [comment]
@hooke007 its works in Windows. I use 3 torrent scripts on mpv.net and they work perfectly but using `mpvnet.com` is pain

**Comment by SonaliBendre** [comment]
@stax76 besides loading url from clipboard, can you add a box for writing URL ?

**Comment by stax76** [comment]
> can you add a box for writing URL

I'm not convinced that would have many users. Most people use `process-instance=single`, with that you can type it in the terminal `mpvnet <url>`. I might add it when somebody creates a new issue, if I have time someday.
