### ISSUE TITLE
Sleep mode not working on 5.7.0.0 

### ISSUE THREAD

**Issue by ll811** [stax76/mpv.net#409]
**Describe the bug**
Computer will not go to sleep after finishing last file in playlist because of an audio stream that stays active when the last file in a playlist has finished playing

**To Reproduce**
1. Start player
2. Select any file and let it finish playing
3. You'll now see a black screen when its finished (As opposed to the mpvnet home screen you see on 5.4.9.0 when the last file has finished playing) 
4. powercfg -requests will now show an audio driver still active

**Expected behavior**
No interference with audio driver and for the computer to go to sleep after mpvnet has finished playing the last file. 

**Screenshots**
![powercfg 1](https://user-images.githubusercontent.com/54498049/163671124-06bbe53f-93ac-4bfc-9530-c91d3d4db8e4.png)

**Additional context**
In the screenshot I have used the powercfg -request for both the latest and previous version, previous version is on top, latest bottom. Screenshot includes running the command while a file is playing and when the playlist has finished. I've tested it on two different audio connections, one using my usb sound card, one using NVIDIA's High Definition Driver, result is the same on both.

**Comment by stax76** [comment]
Here is a fix:

[mpvnet.zip](https://github.com/stax76/mpv.net/files/8610673/mpvnet.zip)
