### ISSUE TITLE
When pressing the KP8 key to Cycle/Next through available subtitles the player hangs for a long time before responding again.

### ISSUE THREAD

**Issue by welovfree** [stax76/mpv.net#41]
mpv.net Version 4.5.0.0
Windows 10 Version 1903 (OS Build 18362.175)

**Comment by stax76** [comment]
Does that happen in mpv as well? What is your GPU and what are your settings?

**Comment by welovfree** [comment]
mpv didn't open the link for me, I'm streaming not locally player the file.

> What is your GPU and what are your settings?
How can look for this?

**Comment by stax76** [comment]
Can you share the link?

**Comment by welovfree** [comment]
http://mega.co.nz/#N!nvYSDAJI!2KgOJIIDJoqh12y-7S6Vd_uCa6miA1-ucrdCxdDn1sw=###n=3uAhFQia

**Comment by welovfree** [comment]
It's a generated link by MegaDownloader from a MEGA folder, I think it's not gonna be working even if I share it.

**Comment by stax76** [comment]
mpv will ask the system for youtube-dl and to make the system find youtube-dl you have to:

put youtube-dl in mpv folder
put youtube-dl in system folder
put youtube-dl folder in user PATH environment variable, that's what expert users do

it's a mpv or youtube-dl problem.

**Comment by welovfree** [comment]
I already have that setup, it's only that link others work fine.

**Comment by stax76** [comment]
If it's not working in mpv then there is nothing I can do, please create an issue on the mpv tracker.
