### ISSUE TITLE
Take a screenshot without subtitle

### ISSUE THREAD

**Issue by Minh-AnhHuynh** [stax76/mpv.net#410]
Currently, mpv.net doesn't support taking a screenshot without subtitle unlike mpv in the documentation.
It would be cool if you could implement this.

**Comment by hooke007** [comment]
input.conf
`F1 screenshot video`

**Comment by Minh-AnhHuynh** [comment]
Thank you, after struggling a little bit I managed to get mpv.net doing it right.

For future reference :
On the async screenshot line, just write :

`[Name of the shortcut] async screenshot video`

Thanks, despite checking the documentation multiple times on the screenshot part, I didn't see another part concerning CLI arguments.
