### ISSUE TITLE
'show config editor' can‘t be opened.

### ISSUE THREAD

**Issue by lyturn** [stax76/mpv.net#411]
System.ArgumentOutOfRangeException: length cannot be less than 0

**Comment by stax76** [comment]
Please use the last release v5.8.0.0:

https://github.com/stax76/mpv.net/releases

If necessary, delete the file:

C:\Users\jondoe\AppData\Roaming\mpv.net\input.conf

https://github.com/stax76/mpv.net/blob/master/src/Resources/input.conf.txt#L141
