### ISSUE TITLE
Freeze while openning file

### ISSUE THREAD

**Issue by A-tG** [stax76/mpv.net#412]
version 5.7.0.0 from MicrosoftStore
CPU Ryzen7 5800x
GPU nvidia gtx1660
Windows 10 Pro 21H1 19043.1526

If osd-scale-by-window = no in mpv.conf there is freeze for a few seconds when file is opened (mpvnet is not running, opening file triggers mpvnet launch). Only happens with vo gpu (Default). Happens with video and audio files. Also no freezing when mpvnet is already running.

And there is small visual artifact while program is frozen ![image](https://user-images.githubusercontent.com/19589064/166123946-27e11367-59b9-422c-a19a-6c2488307b96.png)

**Comment by stax76** [comment]
I can reproduce it, but this type of issue is difficult to debug. The manual about this option says:

> Whether to scale the OSD with the window size (default: yes). If this is disabled, --osd-font-size and other OSD options that use scaled pixels are always in actual pixels. The effect is that changing the window size won't change the OSD font size.

But this doesn't seem to work even in mpv, because when I change the mpv window size, the OSD size changes, or maybe I don't understand this option correctly.

**Comment by stax76** [comment]
I remember now an implementation detail, in the conf editor you can do:

Screen > start-threshold = 0

This seems to fix the issue, it only has a visual glitch flashing the original OSC logo, which hopefully I can fix some day as this problem occurs in various scenarios.

**Comment by A-tG** [comment]
start-threshold = 0 helps.

Regarding osd-scale-by-window option: as far as I know OSD size changes with window size if shown while window resized, but if you wait until it disappear, resize window, then show OSD again - it will be displayed in correct size according to the option.

**Comment by stax76** [comment]
For the logo issue, it's necessary to modify the original OSC, which is an embedded Lua script. It means making a mpv feature request or submitting a pull request, I plan taking action in this regard.

**Comment by adavier** [comment]
> Screen > start-threshold = 0

I would like to add that this fixed vo=gpu-next completely locking up when opening from explorer / as an argument.
(I was also getting the freeze mentioned above on vo=gpu, but didn't notice until switching)
