### ISSUE TITLE
Bug starting mpv.net

### ISSUE THREAD

**Issue by Neo-XP** [stax76/mpv.net#413]
**Describe the bug**
Randomly, mpv.net opens two windows instead of one at start, one from mpv.net and another from mpv.

**To Reproduce**
1. Double click on mpvnet.exe to open it
2. Close it if it opens only one window
3. Repeat until it opens two windows

It happens approximately about one in 10-15 times for me, but it seems totally random.

**Expected behavior**
To only open one window every time.

**Screenshots**
When it works: ![ok](https://user-images.githubusercontent.com/96846493/166514413-2b7548c6-1795-4c01-9345-73b8b02b78e9.png)

When there is a bug:
![bug](https://user-images.githubusercontent.com/96846493/166514564-f61eee78-f2f9-45d4-8420-e829abd48469.png)

**Additional context**
OS is Windows 10 Pro 20H2
No config file created at all, tested with v5.7.0.0 and v5.8.0.0 by just extracting it to a new folder and starting it.

Do you have any idea what to check for to fix this issue?

**Comment by stax76** [comment]
Yes, I know which code area is responsible.

**Comment by stax76** [comment]
Please try this test build:

[mpvnet.zip](https://github.com/stax76/mpv.net/files/8618635/mpvnet.zip)

**Comment by Neo-XP** [comment]
It is unfortunately also still happening with this test build.

**Comment by Neo-XP** [comment]
Nothing worked, deleting the content of C:\Users\jondoe\AppData\Roaming\mpv.net between every start or launching mpv,net with --config=no. I stopped almost every process running in the background too, but nothing helped.

By pure coincidence, a Windows update about .NET Framework popped. I did it, restarted the computer and now it is working perfectly, no double windows after starting it more than 100 times with the test build. I can try with v5.7.0.0 and v5.8.0.0 too if necessary.

It is this update if somebody encounter the same issue: https://support.microsoft.com/en-us/topic/april-12-2022-kb5012117-cumulative-update-for-net-framework-3-5-and-4-8-for-windows-10-version-20h2-windows-server-version-20h2-windows-10-version-21h1-and-windows-10-version-21h2-7214b844-c002-49e4-9962-773e964ff737

Thank you!

**Comment by stax76** [comment]
Good to hear that it works now, I hope it's not coming back.

**Comment by stax76** [comment]
@Neo-XP 

Did your system run many days without reboot? If yes, then it's not yet solved.

**Comment by Neo-XP** [comment]
@stax76 Yes, many many weeks without rebooting usually.
