### ISSUE TITLE
`--idle` doesn't work for mpvnet

### ISSUE THREAD

**Issue by hooke007** [stax76/mpv.net#414]
Original title: Confused with the new option

https://github.com/stax76/mpv.net/commit/28f9df1cee7c032bf8afb4b44d015bfd762493f7

Here tested with 5800, if `keep-open` was set to `no` correctly (by input/console), mpvnet would terminate itself when end at the last frame of the video, and so dose mpv. Why adding another option `keep-open-exit` ?

**Comment by hooke007** [comment]
https://github.com/stax76/mpv.net/tree/cd2f2aeec815a6f06003652f45630398f48c5d9f

I quickly build from this commit and everything works as expectation.
[mpvnet_cd2f2ae (2).zip](https://github.com/stax76/mpv.net/files/8621060/mpvnet_cd2f2ae.2.zip)

> Using no, mpv would terminate after the last file but mpv.net never terminates automatically.

I cannot reproduce this issue here.

**Comment by hooke007** [comment]
@stax76 

> The option allows closing the last file and keep the player process running, so it's a feature not supported by mpv

No, mpv support it but mpvnet seems not.

In mpv, we use
```
idle=yes
keep-open=no
```

**Comment by stax76** [comment]
I'll investigate it tomorrow.

**Comment by stax76** [comment]
It seems mpv's idle property cannot be used for our purpose, mpv does not allow it. Using libmpv the default for idle isn't no, but yes, and it's not possible setting it to no, not from code and also not from conf, it prevents libmpv from initializing, shows an error instead. I can make a support request and improve the docs.

**Comment by stax76** [comment]
Made a request now.
