### ISSUE TITLE
Cannot start properly when `gpu-api=vulkan` is set

### ISSUE THREAD

**Issue by zhongfly** [stax76/mpv.net#415]
**Describe the bug**
Set gpu-api=vulkan in mpv settings, mpvnet cannot start normally.
Error message: Error opening/initializing the VO window

**To Reproduce**
1. set `gpu-api=vulkan` in mpv.conf
2. open mpv.net

**Expected behavior**
mpvnet start normally

**Screenshots**
mpvnet cannot start normally
Right-clicking does not display the menu, nor does the mpvnet logo appear in the window.
![image](https://user-images.githubusercontent.com/11155705/167285627-d941e527-e267-4c86-bb2f-2128e1093a02.png)

**Additional context**
I tested the new 5.8.0.0 version and master branch( https://github.com/stax76/mpv.net/commit/3b9368230c801e41f1665c5aed46f74fde049a84 ),updated mpv-2.dll to the version compiled on May 7 ( 0.34.0-292-g3458651010 ), and compared it with the mpv.exe compiled at the same time, only mpvnet cannot be started,mpv.exe works fine with `mpv --no-config --gpu-api=vulkan video.mkv`.

origin: https://github.com/stax76/mpv.net/discussions/382#discussioncomment-2707168

**Comment by stax76** [comment]
I've uploaded a new beta release which hopefully fixes it.

There is still a cosmetic issue, it shows the original logo, I plan to fix it later.

**Comment by zhongfly** [comment]
After testing, the new version has fixed this bug
