### ISSUE TITLE
MPV.NET won't start when gpu-api is set to Vulkan 

### ISSUE THREAD

**Issue by psychobacter** [stax76/mpv.net#416]
Setting gpu-api = vulkan in MPV settings, mpv.net won't start normally. No window is displayed. The app just fails to open
Error message: **Error opening/initializing the VO window**

**Expected behaviour**
mpv.net starts normally

 The last version which works correctly is **[5.4.9.0]**

**Comment by zhongfly** [comment]
I have already opened a related issue #415 , no need to open another
