### ISSUE TITLE
Version 5.7.0.0

### ISSUE THREAD

**Issue by Xyrexus** [stax76/mpv.net#417]
Just installed MPV.net 5.7.0.0, edited Play/Pause in the Input editor to mouse button left, but clicking the left mouse button on the video does nothing.

**Comment by zhongfly** [comment]
It is recommended that you first try to reproduce the bug in the latest version 5.9.0.0 https://github.com/stax76/mpv.net/releases/tag/v5.9.0.0-beta

**Comment by Xyrexus** [comment]
Ah, I forgot there was an input.conf, changed it in there and also changed MBTN_Left Ignore to MBTN_Mid Ignore, seems to have fixed it. It just didn't work when using the actual right-click menu in the player.
