### ISSUE TITLE
Chapters in MKV files result in a useless button in the track selector

### ISSUE THREAD

**Issue by shirt-dev** [stax76/mpv.net#421]
**Describe the bug**
Chapters in MKV files result in a useless button in the track selector. When you click on it, it crashes the player.

**To Reproduce**
1. Open a MKV file with chapters in it
2. Open the tracks menu
3. At the bottom, of the list, there will be an "E:" listing.
4. Click on the "E:"
5. Player crashes

**Expected behavior**
The chapters should ideally not be displayed at all in the menu

**Screenshots**
![image](https://user-images.githubusercontent.com/2660574/169376255-6df522ab-ac5a-46b2-86ee-81c7b37e32d3.png)
![image](https://user-images.githubusercontent.com/2660574/169376339-e23b9377-06ee-4893-a675-cc8594ac2816.png)

**Comment by stax76** [comment]
I think I saw this often too but didn't really bother me, E stands here for a Matroska feature called edition, see here:

https://mpv.io/manual/master/#options-edition

mpv.net generally supports the edition feature, I still have sample files for testing. I can investigate it, but it will take time.

**Comment by shirt-dev** [comment]
Ah that makes sense. If you need additional sample files, I would be happy to provide them.

It looks as though it has an error setting the edition in this instance, causing a crash.

**Comment by hooke007** [comment]
edition is not chapter.
For some movies which have two endings, the bdripper could encode them into one MKV file via the function 'edition', that allow you to choose to watch which ending as you like.

**Comment by hooke007** [comment]
However, it looks like that mediainfo did read the edition tag even though there is no edition at all in your video?

**Comment by stax76** [comment]
mpv.net uses not mediainfo but mpv to read the edition. In the next release, it shows 'Edition 0' and prints an error on the console when it is clicked, the error is returned by mpv.

**Comment by eladkarako** [comment]
solved for me by updating some dlls https://github.com/stax76/mpv.net/issues/450#issuecomment-1168110988
