### ISSUE TITLE
'script-opts = osc-vidscale=no' and/or 'osd-scale-by-window = no' can delay startup up to 7 sec

### ISSUE THREAD

**Issue by User-3090** [stax76/mpv.net#422]
**Describe the bug**

script-opts = osc-vidscale=no

and/or

osd-scale-by-window = no

can delay startup of up to 7-10 seconds when launched with a file to play as argument. For some reason it does not happen every time. For me roughly every second launch. Cannot reproduce in vanilla MPV.

**Comment by stax76** [comment]
mpv.net waits getting the video size from mpv, before showing the Window, which does not happen with these settings.

There is a conf option `Screen > start-threshold` in the conf editor, which you can set to 0 to disable the waiting.

It has the downside that the window might resize and the original osc logo is visible, the logo issue will soon be fixed.

I hope that solves it.

More info:

https://github.com/stax76/mpv.net/issues/412

https://github.com/mpv-player/mpv/issues/10201

**Comment by User-3090** [comment]
cool, that fixes it! thanks!

**Comment by stax76** [comment]
You are very welcome.

I realized now it can be easily detected, so I made it automatic.
