### ISSUE TITLE
Improve recent file records for urls.

### ISSUE THREAD

**Issue by dyphire** [stax76/mpv.net#424]
At present, only the path is recorded in the recent record, but it is not friendly to url protocols such as http/rtmp(including bd:// and dvd://).
![image](https://user-images.githubusercontent.com/61936050/169709313-0993d66a-3293-4573-bcfd-ad3fa9c143a9.png)
For urls, the media-title should be displayed in the recent record if possible.
In order to achieve this function, we can try to record the path and media-title in the recent record at the same time, but only display the media-title for urls protocols.

**Comment by dyphire** [comment]
Please refer to [recent.lua](https://github.com/hacel/recent/blob/master/recent.lua) , [SimpleHistory.lua](https://github.com/Eisa01/mpv-scripts/blob/master/scripts/SimpleHistory.lua)

**Comment by stax76** [comment]
I don't know if it can be supported for BD, for YouTube etc. it will be supported in the next release.

**Comment by dyphire** [comment]
> I don't know if it can be supported for BD, for YouTube etc. it will be supported in the next release.

After testing, the http protocol can process and record normally. When inputting bd:// and dvd:// protocols from the console, the playback record will not be saved when the mpvnet process ends.
![image](https://user-images.githubusercontent.com/61936050/170482894-2f5f7b97-b65c-40f9-9de7-bb30573d8962.png)
