### ISSUE TITLE
Track-list changes after file loaded will not be reflected in the track menu.

### ISSUE THREAD

**Issue by dyphire** [stax76/mpv.net#426]
Try to load the external audio or external subtitle manually when after the file is loaded, and will find that the corresponding external track information will not appear in the track menu.

mpv.net version: build with https://github.com/stax76/mpv.net/commit/7e834cea6df1a7acf6a3a1c1fe90c9cfdf4cc397 .

screenshot
![image](https://user-images.githubusercontent.com/61936050/170510123-7cb3f72f-329e-47bb-9ec7-9deb581e39f3.png)

**Comment by stax76** [comment]
I'll take a look, thanks for reporting it.

**Comment by stax76** [comment]
I hope it's stable because it's a critical threading related code area.

**Comment by dyphire** [comment]
> I hope it's stable because it's a critical threading related code area.

Unfortunately, the latest commit leads to a new bug, and the external track is repeated now.
![](https://cdn.jsdelivr.net/gh/dyphire/PicGo/img/2022/05/27/20220527214836.png)

**Comment by stax76** [comment]
There was apparently already code dealing with external files, just didn't work in your use case. I hope it's now fine.

**Comment by dyphire** [comment]
> There was apparently already code dealing with external files, just didn't work in your use case. I hope it's now fine.

Unfortunately, the new commit does not fix the problem of duplicate external tracks

**Comment by dyphire** [comment]
> There was apparently already code dealing with external files, just didn't work in your use case. I hope it's now fine.

My mistake. There was a problem with the compilation just now. This problem has been fixed.
