### ISSUE TITLE
Installers for new versions (newer than 5.4.9.0)

### ISSUE THREAD

**Issue by pitsi** [stax76/mpv.net#429]
I use mpv.net 5.4.9.0 on my windows system, where I installed it from the provided setup executable, but that is already 1 year old. All the new versions since then are only provided in zips, for portability I assume, so why are there no installers anymore?

**Comment by stax76** [comment]
Supported are portable, ms store and winget (which uses the store).

**Comment by pitsi** [comment]
Well, ms store is something I will never use, winget is a w10 and w11 only app/feature, so portable is the only way for me to use mov.net from now on. Thank you for the clarification.
