### ISSUE TITLE
Can't assign scroll left/right from mouse wheel buttons

### ISSUE THREAD

**Issue by omperus** [stax76/mpv.net#43]
I tried to assign my scroll left/right middle wheel buttons (logitech g502, you press the wheel sideways) to the jump 7 sec feature, but it won't recognize my input (its like im not pressing anything at all) is there a fix for this? Thanks.

![image](https://user-images.githubusercontent.com/4312673/61146293-15e46600-a4b0-11e9-95d3-6b9fb86b0eab.png)

**Comment by stax76** [comment]
I'll add support for your buttons and upload a test build.

Meanwhile, you can edit the input.conf file manually.

To find out the name of your buttons run this command line:

mpvnet --input-test

This will start mpv.net in input test mode.

https://mpv.io/manual/master/#options-input-test

**Comment by omperus** [comment]
![image](https://user-images.githubusercontent.com/4312673/61150541-0ff38280-a4ba-11e9-82d2-cdae611ff0f2.png)


Like this? Sorry im not very technical.
Nothing happens when i press the scroll wheel sideways, but it does show me what other buttons do.

**Comment by stax76** [comment]
> Nothing happens when i press the scroll wheel sideways

Then it's not supported by mpv, there is not much we can do except donating a mouse to a mpv developer.

**Comment by stax76** [comment]
If you look here:

https://github.com/stax76/mpv.net/wiki/mpv-input-keys

you can see:

WHEEL_LEFT
WHEEL_RIGHT

I cannot tell you why it is not working for you, maybe it is only supported on Linux and MacOS.

**Comment by stax76** [comment]
Next release supports:

- in the learn window of the input editor support was added for
  mouse left, mouse left double, mouse mid, mouse forward, mouse back

Only mpv developers can help with mouse left/right wheel (WHEEL_LEFT / WHEEL_RIGHT).

**Comment by omperus** [comment]
> 
> 
> Next release supports:
> 
>     * in the learn window of the input editor support was added for
>       mouse left, mouse left double, mouse mid, mouse forward, mouse back
> 
> 
> Only mpv developers can help with mouse left/right wheel (WHEEL_LEFT / WHEEL_RIGHT).

Oh, thanks.
Next version of mpv.net will have the support or are there are other updates before next mpv update?

**Comment by stax76** [comment]
For the left and right button of your scroll wheel you have to contact the mpv support if the input test don't react to these buttons, I cannot help with this as it's a mpv problem.

Find the mpv support here:

https://mpv.io/bug-reports/

New mpv.net release:

https://github.com/stax76/mpv.net/releases
