### ISSUE TITLE
F3 doesn't open media search

### ISSUE THREAD

**Issue by Doc-4** [stax76/mpv.net#430]
**Describe the bug**
Neither context menu options under F1 or elsewhere, or pressing F3 directly opens search. If I'm mistaken on how this is supposed to work, please correct me.

**To Reproduce**
Press F3

**Expected behavior**
Some kind of media search opens

**Screenshots**
N/A

**Additional context**
mpv.net-5.7.0.0

**Comment by zhongfly** [comment]
https://github.com/stax76/mpv.net/blob/master/docs/Manual.md#input-and-context-menu

**Comment by hooke007** [comment]
media search is a function which was deleted for a long time.
You have to manually total-clean your config files if updating from an ancient version.

**Comment by Doc-4** [comment]
I see, that makes sense.
