### ISSUE TITLE
`gpu-api = vulkan` doesn't work when there's a #comment in the same line

### ISSUE THREAD

**Issue by versedwildcat** [stax76/mpv.net#435]
**Describe the bug**
This is such an absurd bug. Vulkan doesn't work, if there's a comment appended after `gpu-api`
Affects latest [v5.9.0.0-beta](https://github.com/stax76/mpv.net/releases/tag/v5.9.0.0-beta)

**To Reproduce**
1. Have a clean MPV.net installation
2. Add `gpu-api = vulkan` to mpv.conf
 2.1 All is working at this point. Files open as normal
3. Now, append a comment to `gpu-api = vulkan` like `gpu-api = vulkan #not the planet` 
4. MPV.net no longer functions, windows open but remain black

**Expected behavior**
Comments should work normally. This issue only applies to mpv.net 
Latest upsteam from shinchiro works normally with comments appended

**Screenshots**
<details>
  <summary>With Comment</summary>

![with-comment](https://user-images.githubusercontent.com/96885152/172028042-62716295-6d17-4644-9e63-efcb881b7a6a.png)
</details>

<details>
  <summary>Without Comment</summary>

![without-comment](https://user-images.githubusercontent.com/96885152/172028045-6e8f3d52-fe8a-4a29-a5ed-76efc8d5097f.png)
</details>

**Additional context**
Here's the log of `mpvnet "C:\Users\User\Documents\Storage\MPV Testing\Test 1\HEVC Main10 - jellyfish-10-mbps-hd-hevc-10bit.mkv"` when there's a comment appended
```powershell
mpvnet "C:\Users\User\Documents\Storage\MPV Testing\Test 1\HEVC Main10 - jellyfish-10-mbps-hd-hevc-10bit.mkv"
Error opening/initializing the VO window.
 (+) Video --vid=1 (*) (hevc 1920x1080 29.970fps)
VO: [gpu] 1920x1080 yuv420p10
Could not initialize video chain.
Video: no video
HEVC Main10 - jellyfish-10-mbps-hd-hevc-10bit.mkv
```
And here's the verbose log: https://pastebin.com/WFPYp6Z7

Lastly, I should mention, that if the MPV window is opened without any file, drag'n'drop works normally, regardless of there being a comment or not after `gpu-api=vulkan`

**Comment by versedwildcat** [comment]
Another weird, but probably related bug
if you extend your mpv.conf file with the `include` option, and the included file contains 'gpu-api=vulkan', the same issue arises. Black screen, and this lovely log
```
Error opening/initializing the VO window.
 (+) Video --vid=1 (*) (hevc 1920x1080 29.970fps)
VO: [gpu] 1920x1080 yuv420p10
Could not initialize video chain.
```

To Reproduce:
* Create a file in your config directory. For instance, `video.conf`
* Write `gpu-api = vulkan` to the new file
* Include the new file in mpv.conf with `include = ~~/video.conf`

**Comment by stax76** [comment]
It'll be fixed in the next release, thanks for taking the time making a detailed bug report.

**Comment by sillus81** [comment]
Not sure I can add this into this bug - same issue with gpu-api = vulkan.
On windows 11 (latest stable mpv.net (5.7.0.0) - when you use gpu-api = vulkan, the keyboard short cuts not working. Change it to gpu-api- opengl working no issues. It will be totally black screen without the centre mpv.net icon and the 'drag and drop files here' dialogue disappears.

**Comment by stax76** [comment]
A bug report assumes you are using the last beta version.
