### ISSUE TITLE
Figure out in Lua if running MPV.net or MPV

### ISSUE THREAD

**Issue by couleurm** [stax76/mpv.net#436]
I'm making a Lua script that launches a CLI program, are there some kind of environment-variable that I could retrieve so I can make my script behave differently if the script is used with MPV.net?

**Comment by stax76** [comment]
In the next release, there is an env variable. If you need it, I can upload an executable tomorrow.

name: mpv_client
value: mpvnet

**Comment by couleurm** [comment]
There is no rush, but this would be greatly appreciated in a future release, thank you for the fast response!

**Comment by stax76** [comment]
I thought some time about it and decided to use instead:

MPVNET_VERSION
6.0.0.0

The version parts are all single digits.

**Comment by couleurm** [comment]
Will it be useable this way?
```lua
local isMPVnet = mp.get_property_number("MPVNET_VERSION") ~= nil
```

**Comment by stax76** [comment]
Lua has a functionality for environment variables:

os.getenv

https://www.lua.org/manual/5.1/manual.html#pdf-os.getenv
