### ISSUE TITLE
Can the UI be themed?

### ISSUE THREAD

**Issue by RaXorX** [stax76/mpv.net#438]
This template is meant for usage questions of mpv.net.
In previous versions (I have been using the mpv 5.4.8.0 for a while. And my dark theme was just a modified version of https://github.com/stax76/mpv.net/blob/master/src/Resources/theme.txt

For the dark one I had modified as such

`[dark]

heading     = #3C8CC8
foreground  = #DDDDDD
foreground2 = #AAAAAA
background  = #000000

menu-foreground = #DDDDDD
menu-background = #000000
menu-highlight  = #505050
menu-border     = #FFFFFF
menu-checked    = #5A5A5A`

With this, my old MPV would look as such
![image](https://user-images.githubusercontent.com/44987810/173141364-ef202924-5cce-4984-941f-1d4a36a2b40e.png)

And this is how the current betas look.
![image](https://user-images.githubusercontent.com/44987810/173142106-1feb36a5-0d48-4139-9a54-60efae7eec79.png)
I'm not a fan of gray UIs much and it would be preferable to either get the UI to old (if that's a possibility) or let the new UI be themed too. Unless the theming section for the new UI hasn't been updated in the documentation yet.

**Comment by stax76** [comment]
Did you restart mpv.net?

**Comment by stax76** [comment]
Here are the defaults:

https://github.com/stax76/mpv.net/blob/master/src/Resources/theme.txt

**Comment by stax76** [comment]
There was probably a breaking change when the old menu was replaced with a new menu that has rounded corners.

**Comment by hooke007** [comment]
How to reproduce it? It works well here.
<img src="https://user-images.githubusercontent.com/41094733/173206690-38c866ac-eb5c-4f9c-937c-aa59679a5b29.jpg" width=300>

**Comment by KaranKad** [comment]
![image](https://user-images.githubusercontent.com/71691514/173242953-0aa4c91a-379f-4e7d-8738-5f39d9a50077.png)

I use this theme config
```
[dark]

heading     = #3C8CC8
foreground  = #DDDDDD
foreground2 = #AAAAAA
background  = #323232
highlight   = #404040

menu-foreground = #DDDDDD
menu-background = #000000
menu-highlight  = #505050
```
