### ISSUE TITLE
CLI Argument to set up file associations

### ISSUE THREAD

**Issue by couleurm** [stax76/mpv.net#440]
**Is your feature request related to a problem? Please describe.**
When installing from Scoop, it can be confusing to set mpv.net as your default video player (opening mpv.net on it's own -> right click -> tools -> setup isn't very intuitive)

**Describe the solution you'd like**
Be able to set up file associations directly from the command-line:
```
mpvnet --unregister-file-associations
mpvnet --register video,image,audio
```
If you'd wish to go the extra mile you could see if `mpvnet.exe` is being ran from the version (e.g `apps\mpv.net\5.7.0.0\` folder instead of the non-hardcoded `apps\mpv.net\current` symbolic link and set it instead to prevent file associations to use an older version when Scopp is used to update mpv.net

**Comment by stax76** [comment]
mpv.net itself uses CLI to create the file associations:

mpvnet --register-file-associations video 264 265 asf avc avi avs dav flv h264 h265 hevc m2t m2ts m2v m4v mkv mov mp4 mpeg mpg mpv mts ts vob vpy webm wmv y4m

The first argument to --register-file-associations is the perceived type which can be audio, video or image, the following arguments are the file types.

To unregister:

mpvnet --register-file-associations unreg

Remember that it admin rights.
