### ISSUE TITLE
Make Chapters First Class Citizens

### ISSUE THREAD

**Issue by User-3090** [stax76/mpv.net#442]
I'd like to propose a similar searchable list for chapters as there is available for the playlist (F8).

Why? Modern codecs allow to cram an entire week of conference talks or other educational content into a single 10 GB file. Chapters can be in the hundreds, sometimes OCRed from slide headlines.

MPV/MPV.NET is already the best player for language learning. Let's make it the best player for conference recordings, talks and other dense educational content as well!

**Comment by stax76** [comment]
This will be supported in the next release.

**Comment by User-3090** [comment]
Thanks man! Highly appreciated!

**Comment by User-3090** [comment]
Sorry man, only now got around to really try it. It's perfect! Thank you so much for making this a reality. It really makes a difference for me and people I interact with!
