### ISSUE TITLE
auto-load-folder not working

### ISSUE THREAD

**Issue by ll811** [stax76/mpv.net#452]
**Describe the bug**
Autoplay near doubles the amount of files in your playlist and either plays files in random order or repeats itself.
**To Reproduce**
1. Go into any folder with several video files ie (S01E01, S01E02, etc) 
2. Click on any file, preferrably one that isn't the very first in the folder
3. Skip to next file
4. Player will jump back to the 1st file in the folder and double the amount of files in the playlist
5. If the bug does not occur for you on step 4 repeat steps 2 and 3, you may have to do this anywhere from 5-20 times before it happens

**Expected behavior**
For the autoplay to play the files in order and for the playlist to have the correct amount of files.

**Screenshot**
![playlist](https://user-images.githubusercontent.com/54498049/176997186-5b2a15a8-b06d-4a55-9dd6-b1c00dcdd6ac.jpg)
Playlist is supposed to be 8 files total, as you can see it has counted it as 15.

**Additional context**
Weirdly enough this does not seem to happen every time, so you may have to exit the player and try again a few times to replicate the bug. Reason I say preferrably not the first is just that it is easier to spot when the bug occurs this way because it jumps back to the first file in the folder, it still happens when you start from the first. I wish it was easier to reproduce because you may have to try at this 5-20 times before the bug even appears, and when it does you'll notice the playlist gets broken, sometimes files are in order and just repeated twice, sometimes they're in a random order. I cleared my mpv.net config folder to ensure this wasn't some compatability issue with past settings I had used for older versions, and the bug still persists. I have gone back and tested 5.7.0.0 and this bug does not occur on that version, or 5.8.0.0

**Comment by stax76** [comment]
Do you maybe have a file 'autoload.lua' in your scripts directory?

**Comment by stax76** [comment]
Hotfix that makes [auto-load-folder](https://github.com/stax76/mpv.net/blob/master/docs/Manual.md#--auto-load-folderyesno) more robust:

[mpvnet.zip](https://github.com/stax76/mpv.net/files/9033048/mpvnet.zip)

**Comment by ll811** [comment]
> Do you maybe have a file 'autoload.lua' in your scripts directory?

I have nothing that the mpv.net-v6.0.2.0.zip doesn't come with, just that version unzipped into a folder. Originally I used my config settings from 5.8.0.0 but tried without them running default settings and the bug was still there. Were you able to reproduce it?

**Comment by stax76** [comment]
mpv has an [autoload.lua](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua) script which more or less does the same as the [auto-load-folder](https://github.com/stax76/mpv.net/blob/master/docs/Manual.md#--auto-load-folderyesno) feature of mpv.net, please ensure that this script is not in your scripts folder here:

C:\Users\JonDoe\AppData\Roaming\mpv.net\scripts

> Were you able to reproduce it?

I did not try because it's very unlikely reproducible for me. I or somebody else would have noticed long before. Very likely happens only with a certain folder size or something like that, it needs a certain timing.

Just be sure you are not using [autoload.lua](https://github.com/mpv-player/mpv/blob/master/TOOLS/lua/autoload.lua) and try the hotfix, it's very likely that the hotfix fixes this.

**Comment by ll811** [comment]
> 

I did some testing and from what I can tell this hotfix has fixed it. 
>C:\Users\JonDoe\AppData\Roaming\mpv.net\scripts

I should also say that I have no such folder and no such folder is created when setting up 5.7.0.0. When clearing the mpv.net roaming folder 6.0.2.0 does create a script-opts folder with console.conf and osc.conf in it. 
Given the changes to this roaming folder going from versions, should I delete this roaming map every time I update mpv? 
Is there a convenient way for me to save my inputs and settings without it messing with newer versions of the player whenever I update? For example, Right Click > Settings right now has an extra option for Setup now, this just disappears if I put my old input.conf into the roaming folder.

**Comment by stax76** [comment]
> Given the changes to this roaming folder going from versions, should I delete this roaming map every time I update mpv?

There were breaking changes in the past, now ensuring backward compatibility with existing settings has high priority, so you should keep and backup the settings.

Whenever I add new menu items, users with existing input.conf don't get the new items, it's a known issue that can't easily be fixed, it's described here:

https://github.com/stax76/mpv.net/blob/master/docs/Manual.md#input-and-context-menu

A fix would create complexity and possibly create new problems, so I hesitate to fix it.

I do however list changes to input.conf in the changelog, so users can update it manually.

**Comment by ll811** [comment]
> 

Alright good to know. Thanks for the help and the quick hotfix that you provided!

**Comment by ll811** [comment]
Sorry to do this here by the way, but I don't wanna start another issue for this in case it is just a change I somehow missed. But is the text supposed to be gone from the home screen on the latest version? The "Drop files or URLs to play here."
![mpvnet](https://user-images.githubusercontent.com/54498049/177009638-2f97a6e1-fd32-497d-93b4-dc9629abe974.jpg)

**Comment by stax76** [comment]
That is intended, yes.
