### ISSUE TITLE
MS Store

### ISSUE THREAD

**Issue by IIIPeAceIII** [stax76/mpv.net#455]
Outdated version is on microsoft store. Please update it.
![Untitled](https://user-images.githubusercontent.com/90670189/177118510-594986a4-7ae2-4cf8-a7df-48aa38647d92.png)

**Comment by stax76** [comment]
I've submitted a new version yesterday, if everything goes well, it should arrive soon.

**Comment by IIIPeAceIII** [comment]
Thanks, it's available now.
