### ISSUE TITLE
Caching with backward seeking is not optimized

### ISSUE THREAD

**Issue by hsn10** [stax76/mpv.net#458]
**Describe the bug**
When seeking backward more cache is reloaded then it needs to be. Probably related to LRU caching method which is not optimal for dealing with streams.

**To Reproduce**

Steps to reproduce the behaviour:

Test file is 
_/ipfs/QmaWQgBv77QEPRgxzx3KrW3Y5oyzpbgGTpWdi9xh1PTRHS_ its 178MB mp3 1h14m16s
audio file from dead world radio episode 27 -> https://pin.ski/3pXsqht or https://crustwebsites.net/ipfs/Qmcp5Tu1Zg6sHj8JncRzXYFosMhuTtVn2f9WiUEzEHAJmP?filename=027

You need to access it through some IPFS gateway to stream it URL would be like
https://crustwebsites.net/ipfs/QmaWQ... or https://gw.crustapps.net/ipfs/QmaWQg...
some gateways like more overloaded like cloudflare cf-ipfs.com/ipfs/... and they will not deliver file, several retries are needed. 

Probably streaming any other mp3 with similar size can be used for test.

1. we play the file from start and it will download and cache 43minutes. Indicated by line. Cache size reported on console to be 150M.
1. Then we click and play at time 35 minutes. Cache will shift and will be from 16m to 1h14m. So far so good.
1. Then we click on 6 minute. Correct optimal behaviour will be to cache 10 minutes from 6m to 16m and free last 10 minutes because we already have rest downloaded.
1.  This is not what is happening. It will load data at 6 minutes and moving forward and remove oldest blocks from cache which are at 16 minute. This will create moving hole and after we reach 16th minute when loading cache moving forward we would need to load data that were previously freed,

**Comment by stax76** [comment]
You can get support for this here:

https://www.reddit.com/r/mpv

If that don't help, then you can go here:

https://github.com/mpv-player/mpv/issues
