### ISSUE TITLE
Is there any place to set the encoding of editor_conf.txt?

### ISSUE THREAD

**Issue by vvyoko** [stax76/mpv.net#461]
I'm trying to compile the Chinese version
However, when modifying `Resources\editor_conf.txt`, it will display garbled code

Is this a coding problem or something else?
If it is encoded is there any way to set its encoding?
I searched and it doesn't seem like the encoding is set anywhere?
`Resources.resx`  `<?xml version="1.0" encoding="utf-8"?>`?

Maybe not the encoding but something else?

Garbled as shown in the figure

![123](https://user-images.githubusercontent.com/2145741/178126933-da3206c9-2101-4d45-a889-348609bf049f.jpg)

**Comment by hooke007** [comment]
https://github.com/hooke007/mpv.net_CM/blob/1ac61d395000e6290fb4e9eeb371a73d9ac7cb0f/src/Properties/Resources.resx#L122

**Comment by hooke007** [comment]
> 可能当时有什么考虑没修改吧.

因为英文在中文里一目了然，所以特意没汉化
