### ISSUE TITLE
I lost the right click context menu

### ISSUE THREAD

**Issue by Akhilesh-T** [stax76/mpv.net#463]
I am new to mpv.net and started using it yesterday. I have configured it as much as I can using configuration files. But in the process, I somehow lost the context menu. I have assigned `cycle pause` to the right click. I am using Windows 10 with the latest mpv.net version.

**Comment by stax76** [comment]
It is documented here:

https://github.com/stax76/mpv.net/blob/master/docs/Manual.md#input-and-context-menu

You can get help here:

https://www.reddit.com/r/mpv/

In input.conf you need this:

`MBTN_Right script-message-to mpvnet show-menu`

https://github.com/stax76/mpv.net/blob/master/src/Resources/input.conf.txt#L174

Ensure nothing else is assigned to MBTN_Right after this line.
