### ISSUE TITLE
Client runs at low frames now?

### ISSUE THREAD

**Issue by 4hench** [stax76/mpv.net#466]
Updated to latest version and now when i move around the mouse cursor in the program its like im on 60/30fps /hz

**Comment by stax76** [comment]
You can try if `--config=no` works.

**Comment by 4hench** [comment]
> You can try if the CLI option `--config=no` works better.

sorry but how do i do this?

**Comment by 4hench** [comment]
got it working now but hardware decoding was off as default strange, should be on auto ^^

**Comment by zhongfly** [comment]
> hardware decoding was off as default strange, should be on auto

please read this https://mpv.io/manual/master/#options-hwdec   :
> Hardware decoding is not enabled by default, to keep the out-of-the-box configuration as reliable as possible.
