### ISSUE TITLE
Having single instance on but acts like multi when SHIFT + clicking on the program

### ISSUE THREAD

**Issue by 4hench** [stax76/mpv.net#467]
i remeber i could do this with mpc-hc

**Comment by stax76** [comment]
It will be supported in the next release, two notes:

1. Shift will block [auto-load-folder](https://github.com/stax76/mpv.net/blob/master/docs/Manual.md#--auto-load-folderyesno). If you need multiple files, you need to load them with something like Drag & Drop.

2. Using Shift in File Explorer, enables multi-select, so if you want to use File Explorer, you have to select your wanted file first before you invoke it with click or enter.

**Comment by stax76** [comment]
It's online now.
