### ISSUE TITLE
Where is mpv-2.dll?

### ISSUE THREAD

**Issue by devspexx** [stax76/mpv.net#469]
Ran the original project - rebuilt it and selected & built the winForms folder and got an exception DLLNotFound:
Unable to load DLL 'mpv-2.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by zhongfly** [comment]
shinchiro's mpv build: https://sourceforge.net/projects/mpv-player-windows/files/libmpv/
Or my build:https://github.com/zhongfly/mpv-winbuild/releases , mpv-dev-xxxx.7z including mpv-2.dll

**Comment by devspexx** [comment]
Awesome. Thanks!
