### ISSUE TITLE
issue with MBTN Input

### ISSUE THREAD

**Issue by dizzyson** [stax76/mpv.net#47]
I use MBTN back and forward for "playlist-next/prev , not sure if its in error in one of my configs but the player freezes up

**Comment by stax76** [comment]
Which version of the player?

**Comment by dizzyson** [comment]
using mpv.net 4.7.3.0 , once i use either of those buttons the player will keep playing but all the controls are non responsive. In mpv it works just ifne

**Comment by stax76** [comment]
Please try it with 4.7.4.0

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/f/s!ArwKS_ZUR01gySQIE1QCL2i9F_uR

**Comment by dizzyson** [comment]
player moves to the next file but then once i hit one of the MBTN i lose mouse control

**Comment by dizzyson** [comment]
I'm also getting an error message , if i try to assign MBTN on input editor

https://i.imgur.com/2yl5wZN.jpg

**Comment by stax76** [comment]
Maybe I have to get such a device.

When you start like so:

mpvnet --input-test

In the menu at:

Tools > Execute mpv command

when you enter:

mouse 1 1 7 single

move the mouse out of the mpv.net window and confirm with enter

does it also show MBTN_BACK ?

**Comment by dizzyson** [comment]
Yes MBTN back works, i'm still running into once i hit either of the MBTN back or forward , mouse controls don't work anymore

**Comment by stax76** [comment]
I've uploaded another build, if it's still not working then I have to get such a mouse.

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/f/s!ArwKS_ZUR01gySQIE1QCL2i9F_uR

**Comment by dizzyson** [comment]
Yeah still not working , not sure what happening but whenever those are pressed it breaks the player.

**Comment by stax76** [comment]
I'm sorry, I ordered Logitech G203 by Amazon now.

**Comment by dizzyson** [comment]
its all good bro, love the program

**Comment by stax76** [comment]
Please try if it works now.

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/f/s!ArwKS_ZUR01gySQIE1QCL2i9F_uR

**Comment by dizzyson** [comment]
You crazy son of a bitch you did it 👍 👍
