### ISSUE TITLE
Does MPV.NET support the parameter "audio-file" ?

### ISSUE THREAD

**Issue by QS0x01** [stax76/mpv.net#471]
I tried to play web videos by mpv.net through a js script coded for mpv, unfortunately it meet some questions.

For example, the script will run these commands on cmd while playing this video:

https://www.bilibili.com/video/BV1rG411n7qp

`mpv --http-header-fields="referer:https://www.bilibili.com/" "https://cn-hk-eq-bcache-08.bilivideo.com/upgcxcode/41/78/781657841/781657841-1-30102.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1658785671&gen=playurlv2&os=bcache&oi=351257929&trid=0000590e02f1ed0849dd992574aedffc0e2du&mid=390478044&platform=pc&upsig=07527a6e9c984d338aaf84c8c689046e&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&cdnid=68702&bvc=vod&nettype=0&orderid=0,2&agrr=0&bw=150626&logo=80000000" --audio-file="https://cn-hk-eq-bcache-11.bilivideo.com/upgcxcode/41/78/781657841/781657841_nb3-1-30280.m4s?e=ig8euxZM2rNcNbdlhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1658785671&gen=playurlv2&os=bcache&oi=351257929&trid=0000590e02f1ed0849dd992574aedffc0e2du&mid=390478044&platform=pc&upsig=ce0c7dab8c528cefa6c1137f80f29ebe&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&cdnid=68703&bvc=vod&nettype=0&orderid=0,2&agrr=0&bw=40345&logo=80000000"` 

A mpv.net instance would be aroused, but it only played the video stream, while prompted "property not found" error with no audio being hearded. (I just renamed the mpv.net.exe to mpv.exe directly)

**Expected behavior**
Playing the audio with video together just like mpv.

**Screenshots**
![image](https://user-images.githubusercontent.com/59040858/180864754-d021b204-99ea-46f0-83e0-1670635d0bfe.png)

**Additional context**
1. mpv.net version 5.9.0.0
2. Windows version 11 Pro  21H2 22000.778

**Comment by stax76** [comment]
You can use --audio-file**s** instead of --audio-file, next release supports both.

There was a bug causing external tracks not showing in the tracks context menu.

Hotfix:

[mpvnet.zip](https://github.com/stax76/mpv.net/files/9225910/mpvnet.zip)
