### ISSUE TITLE
--no-osd-bar disappears from mpv.conf

### ISSUE THREAD

**Issue by Akhilesh-T** [stax76/mpv.net#472]
**Describe the bug**
The player stops following --no-osd-bar after a few videos because it disappears from the mpv.conf
I don't know what triggers this, but I suspect it conflicts with another input.

**Steps to reproduce the behavior:**
1. Go to mpv.conf and add --no-osd-bar on top
2. Play video
3. Change volume
4. osd bar is visible

**Expected behavior**
osd bar shouldn't be visible

**Additional context**

First few lines of mpv.conf

--no-osd-bar
--cursor-autohide = always
sub-font-size = 36
sub-color = '#FFFFB366'
keep-open = yes
sub-font = 'Lucida Grande'
osd-font = 'Gill Sans MT'
osd-font-size = 15
osd-duration = 400
fullscreen = yes
--volume-max = 200
--osd-border-size = 1
--osd-align-y = bottom
--osd-color = '#FFFFB366'
--osd-margin-x = 5
--osd-margin-y = 5

1. mpv.net version: v6.0.3.0
2. Windows version: 10.0.19044 Build 19044
3. GPU name: Intel(R) HD Graphics

**Comment by stax76** [comment]
If there is an issue, then it's probably caused by mpv and not mpv.net.

Does it work if you use `osd-bar = no` instead?

It's unlikely that mpv or mpv.net change the content of mpv.conf, saving another content.

**Comment by Akhilesh-T** [comment]
Thanks.

I haven't tested it using `osd-bar = no` yet.
Now I have replaced `--no-osd-bar `with `osd-bar = no`. Will let you know if it reoccurs.

**Comment by hooke007** [comment]
https://mpv.io/manual/master/#putting-command-line-options-into-the-configuration-file

Unnecessary to mix syntax in conf file.

**Comment by Akhilesh-T** [comment]
Oh, thanks for the info.
