### ISSUE TITLE
--taskbar-progress doesn't work

### ISSUE THREAD

**Issue by superpoincare** [stax76/mpv.net#473]
**Describe the bug**

Setting `--taskbar-progress=no` in `mpv.conf` doesn't do anything. 

**To Reproduce**

Try the latest beta with `--taskbar-progress=no` in `mpv.conf` and play any video.

**Expected behavior**

No taskbar progress to be seen. 

**Additional context**

1. mpv.net version: 6.0.3.0-beta
2. Windows version: Windows 10 21H2
3. GPU name: Intel HD Graphics

**Comment by stax76** [comment]
It's fixed in the next release, meanwhile you can remove the hyphens, they are not needed in the conf file.
