### ISSUE TITLE
Wikientry -> Programm Switches in the commandline

### ISSUE THREAD

**Issue by blackcrack** [stax76/mpv.net#476]
Hi Stax76,

would nice if we (the Users) have a possible for read the command Swiches 
in the wiki..

i already have try "mpvnet.exe /?" nothing .. 
i have kick on the Wiki here at :  
https://github.com/stax76/mpv.net/wiki  
Nothing on it..

if i have no possible for include in a TotalCommander x86 or on x86_64(so with 64Bit enhancement)
with switches or an other program via "/f ..." file or "/u ..." and maybe with other swiches, do i not need MPV.Net

and a suggestion, make directly x86 and x86_64 zip Packages, installer must not be at beta..
and Win11 in x86 exist also ( want not easy kick my x86 Notebook away if works Win7 and later still on older notebooks )
( the same on Linuxdistros "we neet no more x86 Arch" Fedora and Co.. Bah bullshit ! grrr )
just as info and as feature request..

best
Blacky

**Comment by stax76** [comment]
You can search the command palette (F1) for `prop` (Show Properties, SHIFT+P) or use the [OPTIONS section](https://mpv.io/manual/master/#options) in the mpv manual.

**Comment by blackcrack** [comment]
Hi @stax76 ,
well, in the wiki would be a link to the   
https://mpv.io/manual/master/#options  
  
also well.. because if anyone be here in github,   
is the first way easy the wiki..  

and a x86 .. i hope it is not dropped ...

best
Blacky
