### ISSUE TITLE
Streamlink

### ISSUE THREAD

**Issue by trimechee** [stax76/mpv.net#477]
Hello, it will be great to add support of streamlink just like yt-dlp so our beloved Mpv.net plays even more videoS from streaming sites ! 

https://github.com/streamlink/streamlink

Thank you very much !

**Comment by hooke007** [comment]
> it will be great to add support of streamlink just like yt-dlp

It's mpv's support of yt-dlp not mpvnet.

**Comment by trimechee** [comment]
yes mpv is CLI command line and command line may be  difficult inconfortable tht's why i propose to Mpv.Net to add native support of streamlink so we can use streamlink without command -line and increase network cache and choose video stream quality....

**Comment by stax76** [comment]
You don't have to type out commands in the terminal, but can use input commands, user scripts, external tools etc.

https://mpv.io/manual/master/#command-interface-[-]]]

https://github.com/stax76/awesome-mpv

Feel free to ask if you don't know how to create a comfortable solution, you can also ask on reddit.

https://www.reddit.com/r/mpv

**Comment by stax76** [comment]
Use this:

https://add0n.com/external-application-button.html

Executable Name: D:\Software\CLI\run-hidden.exe

https://github.com/stax76/run-hidden

Arguments: `C:\streamlink.exe --player=C:\mpvnet.exe [HREF] best`

If you define more than one, then use the context menu feature of external-application-button for invocation.

External-Application-Button was suggested to me by a mpv.net user, it's extremely useful, I'm using all the time.

**Comment by trimechee** [comment]
Wouahh ! this is absolutely awesome amazing ! thank you very much for your precious advices and recommandations 🥇
