### ISSUE TITLE
Chocolatey for mpv.net

### ISSUE THREAD

**Issue by bitsper2nd** [stax76/mpv.net#48]
Hi, stax

This is not really an issue with the player itself, but more of a request. If it is not too much trouble, would you be able to also make an mpv.net [chocolatey](https://chocolatey.org/) package as another alternate mean to install your player? Could be really useful for those who prefer to use something akin to package managers (from linux distros) on Windows.  I [edited](https://social.technet.microsoft.com/wiki/contents/articles/35441.creating-a-chocolatey-package-using-powershell.aspx) the OG [mpv](https://github.com/AeliusSaionji/chocopkgs/tree/master/mpv) chocolatey package with the info from the mpv.net project and attached it below. Feel free to check it out, edit the files.  

[mpv.net.4.7.1.zip](https://github.com/stax76/mpv.net/files/3390682/mpv.net.4.7.1.zip)

**Comment by stax76** [comment]
Hi,

I'm always looking for cool ideas. If it's not hard and I like its design, then I'll do it.

Did you know there is a similar tool, I'm not sure if I remember the name, scoop maybe, I think somebody made a mpv.net package for that, that's what I found out when I was googling for mpv.net.

**Comment by bitsper2nd** [comment]
I heard of scoop, but haven't tried it out yet. After quick search, I found the mpv.net [package](https://github.com/lukesampson/scoop-extras/blob/master/bucket/mpv.net.json) you mentioned. Seems convenient and lazy like chocolatey. Thanks!

**Comment by stax76** [comment]
The thing I learned about scoop meanwhile is that it focuses on command line and developer tools. I'll focus on chocolately.

**Comment by bitsper2nd** [comment]
Again. This is not an issue much less related to the request before, but have you thought about changing the on-screen-controller? Since you recently updated the icon. I thought you might be  interested in differentiating the player even more. I got this [osc style](https://github.com/422658476/MPV-EASY-Player/tree/master/mpv-easy-data/osc-style) from rjno1 repo.

![mpvnet-oscmod](https://user-images.githubusercontent.com/22452474/62253237-9cafa300-b3cb-11e9-9f29-174a1c7eb17f.png)

**Comment by stax76** [comment]
I like the default OSC but also can imagine using a customized OSC in the future.

Do you know if using a custom OSC requires a custom mpv build?

**Comment by bitsper2nd** [comment]
Nope. I just put the .lua file in the scripts folder and wrote `osc = no` in the mpv.config file. Here is an english translation of the author's [repo](https://github.com/422658476/MPV-EASY-Player#%E6%95%99%E7%A8%8B%E5%A6%82%E4%BD%95%E5%88%B6%E4%BD%9Cmpv-easy-playermpv-player%E7%9A%84osc%E5%A4%96%E8%A7%82%E6%A0%B7%E5%BC%8F) for more details. 

> See these osc styles on the above picture? Not only can they exist in the mpv-easy player, but the osc of the mpv you use can also be like this.

> The steps are also very simple, just need:

>Download all osc-XXX.lua files from [mpv-easy-data/osc-style]. These lua files are all mpv-easy player original (modified from the official osc.lua), each representing one or more styles.
For example [osc-mpc-be-blue-box-bar-or-knob-20-60.lua], why is this lua file name so long?

>This is because its naming convention is [file name - osc style - progress bar style - osc transparency range - osc transparency range .lua], which means that the file name is

    Osc style = box

    Progress bar style = bar or knob

    Osc transparency = between 20-60

>Will have the best display.
How can I make [osc-mpc-be-blue-box-bar-or-knob-20-60.lua] in the example work?

1. Rename osc-mpc-be-blue-box-bar-or-knob-20-60.lua to osc.lua

2. Copy the renamed osc.lua to the portable-data\scripts folder and overwrite the portable-data\scripts\osc.lua file with the same name. 

3. open the portable-data\lua-settings\osc.conf file, modify it to this

        The top is for the version before mpv 0.28.2 2018-3-30. If you use the version after mpv 2018-3-30, please change the lua-settings to script-opts.

     ```
     Layout=box

     Seekbarstyle=bar

     Boxalpha=45

4. osc style, progress bar style, osc transparency range is corresponding to layout, seekbarstyle, boxalpha these three parameters, change the osc.conf file, re-run mpv you can see the osc style changed.

**Comment by stax76** [comment]
Thanks for the info, I'm always looking for good ideas.

**Comment by bitsper2nd** [comment]
just got this issue in the 5.2 update. Apparently the program does not find the mpvnet.conf file in any location other than c://programs/mpv.net/portable_config.

<img width="461" alt="issue" src="https://user-images.githubusercontent.com/22452474/62573310-29df7580-b86c-11e9-941c-7d6356dd8b17.png">

**Comment by stax76** [comment]
I have to make a bug fix release, it happens because of a race condition.

**Comment by bitsper2nd** [comment]
https://chocolatey.org/packages/mpvnet.install
