### ISSUE TITLE
How to play files in multiple folders

### ISSUE THREAD

**Issue by Yaya55** [stax76/mpv.net#480]
Hello.
I am dragging and dropping multiple folders into the mpv.net window and playing the videos in them in order.
Until v6.0.3.0, this operation was possible.
However, in v6.0.3.1, even if I register multiple folders, only the files in the first folder are registered in the playlist.
I believe this is probably due to the change in "commit: 07809d882fc31a5f414e6bd142aab2d8648a8d90 ".
Is there any way to drag and drop multiple folders to play them as in previous versions?

**Comment by stax76** [comment]
Here is a hotfix:

[mpvnet.zip](https://github.com/stax76/mpv.net/files/9265295/mpvnet.zip)

**Comment by Yaya55** [comment]
Thank you for your quick response.
I have confirmed that the problem has been fixed.
