### ISSUE TITLE
Any Method to Modify OSD Progress Bar from Total Time to Remaining Time?

### ISSUE THREAD

**Issue by QS0x01** [stax76/mpv.net#481]
**Is your feature request related to a problem? Please describe.**
I just wish osd(top) to show remaining time instead of total time in progress bar just like osc(bottom). 

**Describe the solution you'd like**
Maybe user can choose which to show by writting it in the config file. For example: -timetotal=no.

**Additional context**
I do not know whether I should open this issue at mpv or mpv.net. Anyway, thank you very much for your reading.

![Snipaste_2022-08-09_06-56-12](https://user-images.githubusercontent.com/59040858/183529974-4f217cd7-df63-45f1-887e-dd851c8a1238.png)

**Comment by hooke007** [comment]
```
osd-status-msg = "${time-pos} / ${playtime-remaining} (${percent-pos}%)"
```

**Comment by QS0x01** [comment]
> ```
> osd-status-msg = "${time-pos} / ${playtime-remaining} (${percent-pos}%)"
> ```

哈哈哈，谢谢大哥，搞定！
