### ISSUE TITLE
Navigate to previous or next sentence when subtitle exists

### ISSUE THREAD

**Issue by valuex** [stax76/mpv.net#483]
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
When subtitle is loaded for the  current playing video file, the user can navigate to previous or next sentence using shortcut.
Also, it would be better if the user can set ** some buffer time** based on his/her requriement.  
For example, Previous sentence -_0.5s_  means navigate to 0.5s before the beginning of previous sentence. The _0.5s_ can be defined in the user setting file.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by hooke007** [comment]
> When subtitle is loaded for the current playing video file, the user can navigate to previous or next sentence using shortcut.

https://github.com/stax76/mpv.net/blob/22960af78b7e1b7255954d845b3d378330aa449b/src/Resources/input.conf.txt#L221-L222

**Comment by valuex** [comment]
> > When subtitle is loaded for the current playing video file, the user can navigate to previous or next sentence using shortcut.
> 
> https://github.com/stax76/mpv.net/blob/22960af78b7e1b7255954d845b3d378330aa449b/src/Resources/input.conf.txt#L221-L222

That's so good. Thanks very much.
