### ISSUE TITLE
Mpv.net ignores keepaspect argument when resizing with AltSnap/AltDrag

### ISSUE THREAD

**Issue by rp1231** [stax76/mpv.net#485]
**Is your feature request related to a problem? Please describe.**
Mpv ignores keepaspect argument when resizing with AltSnap/AltDrag adding black bars to the side/top when resizing.

**Describe the solution you'd like**
mpv.net should respect the keepaspect argument even when resizing via AltSnap/AltDrag

**Comment by stax76** [comment]
Window features typically involve high complexity, I need a more detailed description to understand what it is about.

**Comment by stax76** [comment]
If I understand correctly, the problem exists with mpv too. The code mpv.net uses to keep the window aspect ratio when resizing originates from mpv, and it's difficult to understand, this might not be easy to fix, it's also very niche. You can also try to request it on the mpv tracker. I tried the AltDrag app, it doesn't work here, which makes it even harder.

**Comment by stax76** [comment]
> The app doesn't work ?

Yes, it didn't work, and I couldn't find out what was wrong.
