### ISSUE TITLE
Allow toggling off the visibility of a window title when moving to the next media in a playlist.

### ISSUE THREAD

**Issue by ScionOfDesign** [stax76/mpv.net#493]
**Is your feature request related to a problem? Please describe.**
I switch between lots of short clips/images often and seeing the title appear at the top every time in the new version is very annoying, and I can't seem to figure out how to turn it off. I looked in the documentation.

**Describe the solution you'd like**
The ability to toggle off the title visibility at the top.

**Describe alternatives you've considered**
Downgrading.

**Comment by hooke007** [comment]
What do your window title mean? `filename` OSD?

append a blank for option `osd-playing-msg`

**Comment by ScionOfDesign** [comment]
That fixed it, thanks!
