### ISSUE TITLE
`input-default-bindings = no` is being removed from mpv.conf

### ISSUE THREAD

**Issue by versedwildcat** [stax76/mpv.net#494]
**Describe the bug**
mpv.net removes `input-default-bindings = no` from mpv.conf

**To Reproduce**
1. Add `input-default-bindings = no` to your mpv.conf
2. Open mpv.net (you don't need to open or interact with the config editor)
3. `input-default-bindings = no` has been removed from mpv.conf, in its place a blank line.

**Expected behavior**
Even if implied by default, I don't think there's any reason for mpv.net to clear that option. 
It's useful for using the same config on vanilla mpv.

**Additional context**
1. mpv.net version: Beta [v6.0.3.1](https://github.com/stax76/mpv.net/releases/tag/v6.0.3.1)
2. Windows version: Windows 10 Pro 21H2

I can't reproduce it every time. Not sure if opening a specific file or playing for a certain duration of time is the reason.

**Comment by hooke007** [comment]
https://github.com/stax76/mpv.net/blob/22960af78b7e1b7255954d845b3d378330aa449b/src/Misc/Player.cs#L253-L257

**Comment by stax76** [comment]
It's done by design, was needed to achieve backward compatibility with old settings. It's however only removed one time, so you can put it back, it will persist then.

**Comment by versedwildcat** [comment]
> It's done by design, was needed to achieve backward compatibility

Fair enough.

>  The problem for me was that I had added `settings.xml` to `.gitignore`, since it contains the watch history.

 Figured it out now, I had added `settings.xml` to `.gitignore`, since it contains the watch history.
 
 Thanks for your time.
