### ISSUE TITLE
how can i make so vertical video starts in full window height?

### ISSUE THREAD

**Issue by 4hench** [stax76/mpv.net#497]
right now i dosent fill entrily as start size

**Comment by tunaflsh** [comment]
Do you want to always start the window in the fullscreen mode?

**Comment by 4hench** [comment]
> 

maxed in windowed mode if possible


right now it starts like this ![1](https://user-images.githubusercontent.com/52123669/192320233-0208fe6a-0a63-408f-a3da-942357b3a706.png)

i want
![2](https://user-images.githubusercontent.com/52123669/192320347-59fd224e-3e71-4167-aba2-0ab6f4c93470.png)

**Comment by tunaflsh** [comment]
It's a setting of mpv. Check https://mpv.io/manual/stable/#options-video-unscaled. Check if you config file contains `video-unscaled=yes` or `no-keepaspect`. Also it looks like your grey part is a part of your video. In this case the options I mentioned above won't work, you can zoom by right-click **Pan & Scan > Inscrease Size** or by using the keybinds.
