### ISSUE TITLE
How to always open a video in 100% video size?

### ISSUE THREAD

**Issue by ScribbleGhost** [stax76/mpv.net#500]
Some type of questions like questions about a problem require filling out an issue template:

**Describe the problem**
When opening a video file, how can I make sure that mpvnet always opens the video in 100% of the video size?
I would preferably also like to have 100% video size when switching from one file to another.

**To Reproduce**

**mpv.conf**

```
start-size = video
remember-window-position = yes
window-scale = 1
autofit-larger = 100%x98%
```

**mpnet.conf**

```
remember-position = yes
window-scale = 1.0
start-size=video
```

In case of an audio or video problem, try to reproduce the problem using mpv instead of mpv.net.
If it can be reproduced with mpv, use the [mpv issue tracker](https://github.com/mpv-player/mpv/issues).

1. Use the provided configs above
2. Open a video (for example an UHD video)
3. Hit `Alt+1` or View -> Zoom -> 100%
4. The mpvnet window will resize to 100%, showing that the video was not set to 100% initially. That is the problem.

**Expected behavior**
I don't get why one should have to do anything specific. If you ask me, mpvnet should play any video at 100% of the video all the time. This should be default. The user should really not have to do anything. The only exception being if the video res exceeds the screen resolution.

**Screenshots**
N/A

**Additional context**
1. mpv.net version: 6.0.3.0
2. Windows version: 10 21H2
3. GPU name: Nvidia GeForce RTX 3090
4. Media info: 22.03.0.0

**Comment by hooke007** [comment]
Were you using HIDPI?
https://github.com/stax76/mpv.net/issues/207

**Comment by 4hench** [comment]
try

autofit = 100
autofit-larger = 100

**Comment by ScribbleGhost** [comment]
Thanks. Yeah, putting that in the **mpv.conf** (not mpvnet.conf) seems to work 😁 Tanks!
