### ISSUE TITLE
M3U8 HLS

### ISSUE THREAD

**Issue by trimechee** [stax76/mpv.net#506]
Hello, ffmpeg seems to have some problem with HLS m3u8 streams, but a tool like "hlsdl" seems to solve these problems, please it will be great if there is support for specific hls streams of some websites by integrating these m3u8 softwares in order to avoid these bugs, thank you so much ! 

C program to download VoD HLS (.m3u8) files

https://github.com/selsta/hlsdl

m3u8 : Python m3u8 Parser for HTTP Live Streaming (HLS) Transmissions :

https://github.com/globocom/m3u8

[.NET] m3u8 downloader Open source command line m3u8/HLS/dash downloader, supports common AES-128-CBC decryption, multi-threading, custom request headers, etc. Supports Simplified Chinese, Traditional Chinese and English. English Supported.

https://github.com/nilaoda/N_m3u8DL-CLI

[.NET7] Cross-Platform stream downloader for DASH/HLS.

https://github.com/nilaoda/N_m3u8DL-RE

and

https://github.com/HeiSir2014/M3U8-Downloader

https://github.com/Spark-NF/hls-downloader

 " HLSDL appears working much better than ffmpeg in these cases.
Hlsdl is public and the source code available.
The stream plays almost immediately and is stable. No errors or buffering.
Using ffmpeg for the download step gives a very long intial delay and is not very stable.
so I assume that the new crypto+hls RAI flows are badly handled by ffmpeg based players now.

 the video is choppy and unable to buffer enough for a fluid vision. Parole has no problem.

FFmpeg is not good for HLS streams, but I watched a lot of various HLS streams without any problems. The main problem is that FFmpeg downloads all streams (many video sizes at once), so you can watch only HLS stream with single video size"

**Comment by hooke007** [comment]
mpvnet doesn't take responsibility for parsing/demuxing/decoding.
