### ISSUE TITLE
Use exclusive mpv.conf in %appdata% to not mess with mpv's config file

### ISSUE THREAD

**Issue by floppyD** [stax76/mpv.net#51]
Every time I launch mpv.net it messes with my standard mpv configs, if you renamed mpv.net's config file or moved it another directory this issue wouldn't happen.
Ex:
mpv.conf before launching mpv.net:
```
#High quality video rendering 
profile=gpu-hq
deband=no

#Do not hide OSC behind taskbar
autofit-larger=88%

#Loop
loop
#loop-playlist

#Interpolation
#video-sync=display-resample
#interpolation=yes
#tscale=box
#tscale-window=sphinx
#tscale-radius=1.0
#tscale-clamp=0.0

#Play external audio
audio-file-auto = fuzzy

#Don't scale OSC
#script-opts = osc-vidscale=no

#Disable OSC for thumbnails
osc=no
```

mpv.conf after launching mpv.net:
```
#video-sync = display-resample
#interpolation = yes
#tscale = box
#tscale-window = sphinx
#tscale-radius = 1.0
#tscale-clamp = 0.0
#script-opts = osc-vidscale=no
profile = gpu-hq
autofit-larger = 88%
audio-file-auto = fuzzy
osc = no
```

**Comment by 44vince44** [comment]
You can move all the config files to a folder that you create inside the program's folder, called "portable_config". This way mpv.net will not read nor modify the files in appdata.
Usually it's: c:\Program Files\mpv.net\portable_config
This way you leave appdata to standard mpv.

**Comment by stax76** [comment]
If you want to use both mpv and mpv.net with separate settings then it might be best to use portable_config for both. I think c:\Program Files\ is write protected, use something else. 

https://github.com/stax76/mpv.net#settings

https://mpv.io/manual/master/#files-on-windows

**Comment by floppyD** [comment]
Sure, but why use the default mpv directory if their config files aren't compatible? Wouldn't be better if mpv.net had it's own directory?

**Comment by 44vince44** [comment]
you can edit the properties of the mpv.net folder in c:\program files\
in security tab, edit permissions and give all permissions to you as a user.
i do this for mpv.net and all the legacy software.

**Comment by floppyD** [comment]
Yes, I know that, but what I'm saying is that the default behavior is weird and you have to do some tinkering to get what you want, you would expect that 2 different programs wouldn't write their settings in the same directory. I made this issue because I got kinda frustrated when I realized that it overwrote my mpv settings on another computer the first time I tried it (it had tons of small settings, I managed to recover with the Windows "Previous Versions" feature btw) so it would be really nice if the developer could at least modify this behavior so this doesn't happen to other people that are migrating from mpv or if they want to run both programs while keeping their settings on appdata.

**Comment by stax76** [comment]
The fact that an extensive mpv config can be messed up by accident is a problem, I can see that. I have to think about possible improvements.

**Comment by floppyD** [comment]
I think you can store mpv.net settings under %appdata%/mpv.net, and when ran for the first time, the program could look for it, and if it doesn't exist but %appdata%/mpv does, you could offer a "migration", that would be basically copying the mpv folder contents to the new mpv.net folder. This way you can cover both current and new users.

**Comment by stax76** [comment]
I rewrote the logic to find the settings folder, first it will check if portable_config exists, if not then it will check the registry, if that don't exist either it will show this:

![Untitled](https://user-images.githubusercontent.com/11410540/61580687-d6072980-ab14-11e9-8ad7-cb798e56555b.png)

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/f/s!ArwKS_ZUR01gySQIE1QCL2i9F_uR

**Comment by stax76** [comment]
New release which addresses this issue is out, thanks for the feedback!
