### ISSUE TITLE
Use Squirrel.Windows for installer and updater

### ISSUE THREAD

**Issue by xaoseric** [stax76/mpv.net#52]
Might be a good idea to look into using [Squirrel.Windows](https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/getting-started/0-overview.md) for the installer and updater so you can install in appdata and release updates easier. 

You also have the ability to release updates with github - https://github.com/Squirrel/Squirrel.Windows/blob/develop/docs/using/github.md

**Comment by stax76** [comment]
Thanks for the suggestion, the project is new to me. It could be a solution for the future.

**Comment by stax76** [comment]
Updater is now done with PowerShell.
