### ISSUE TITLE
Feature Request: Start as a maximized window

### ISSUE THREAD

**Issue by Oggom** [stax76/mpv.net#53]
As previously mentioned here https://github.com/stax76/mpv.net/issues/42#issuecomment-510616268 it would be nice to have the option to always launch mpv.net in a maximized window.

**Comment by stax76** [comment]
Config editor:

Settings > Show Config Editor > Screen > fullscreen > yes

or mpv.conf

`fullscreen = yes`

**Comment by stax76** [comment]
You mean maximized or full screen?

maximized has the title bar visible.

full screen has the title bar hidden.

**Comment by stax76** [comment]
Normally I would write a script for unusual requests. Unfortunately things that appear to be simple often are not. The code involved is complex. I can give you something that works but isn't perfect, making it better is not trivial.

Save at <config folder>\scripts with cs extension.

```
using System;
using System.Windows.Forms;
using System.Threading;
using System.Threading.Tasks;

using mpvnet;

class Script
{
    MainForm Form;

    public Script()
    {
        Form = MainForm.Instance;

        Task.Run(() => {
            Thread.Sleep(500);
            Form.Invoke(new Action(() => Form.WindowState = FormWindowState.Maximized));
        });
    }
}
```

**Comment by Oggom** [comment]
Oh, I've noticed this feature has since been to mpv.net without having to use additional scripts. 
Thanks!
