### ISSUE TITLE
mpv.net is using wrong file association paths

### ISSUE THREAD

**Issue by floppyD** [stax76/mpv.net#55]
It's creating two paths, one in HKLM\SOFTWARE\Clients\Media\mpv and the other in HKLM\SOFTWARE\Clients\Media\mpv.net, which ends up overwriting mpv configs (if installed) and not showing mpv.net in the Default Programs list.

**Comment by stax76** [comment]
Thanks for the report, great find!

It'll be fixed in the next release.

**Comment by stax76** [comment]
It's fixed in 5.0 which I just released. Thanks for the feedback.
