### ISSUE TITLE
Illegal characters in path when playing .rar file

### ISSUE THREAD

**Issue by Hoernchen** [stax76/mpv.net#57]
Playing a rar file with a name of abcd.part01.rar results in a "file path" of abcd.part01.rar|filename.mkv shown at the bottom of the screen and this error message (everything works despite the error message):

ArgumentException

Illegal characters in path.

System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.GetFileName(String path)
   at mpvnet.MainForm.<>c__DisplayClass33_0.<FileLoaded>b__0() in D:\Projekte\CS\mpv.net\mpv.net\WinForms\MainForm.cs:line 370

**Comment by stax76** [comment]
I cannot play a split rar with mkv content in any player, just tried mpc, mpv and potplayer, doesn't work. 

I'm not getting an exception however, mpv.net jumps to the next playable file in the playlist.

Is there any player that can play your file? Do you have a download link?

**Comment by stax76** [comment]
Just tried a rar that is not split. Does not work in any player either. I created it with WinRar, maybe my mkv file is not suitable for streaming, maybe mkv is generally not suitable for streaming.

**Comment by stax76** [comment]
I could now reproduce and fix it. Thanks for the report.

**Comment by Hoernchen** [comment]
Woops, I guess I should have mentioned my (usual, working) setup, it's mpc-hc with the rarfilesource directshow filter which nowadays appears to live at https://github.com/mirror/rarfilesource, playing the usual scene releases which consist of mkv containers in multipart **uncompressed** rar archives. VLC will play that without any issues as well - just like stock mpv, at least if you target the first archive.

**Comment by stax76** [comment]
It should work in 5.0 which I just released. Thanks for the feedback.
