### ISSUE TITLE
mpv.net is not showing under Default Programs

### ISSUE THREAD

**Issue by floppyD** [stax76/mpv.net#58]
I think you are missing some registry keys to make it show on the list, can you take a look at this installation script (included with the shinchiro build of mpv) and see if this is the case?
[mpv-install.bat.txt](https://github.com/stax76/mpv.net/files/3437831/mpv-install.bat.txt)

**Comment by stax76** [comment]
I already used this script. On my Win 10 system mpv.net is available under 'Default apps'.

**Comment by 44vince44** [comment]
FloppyD, you need to open mpv.net, and from the menu DEASSOCIATE ALL types, then REASSOCIATE them (all or at east video)

**Comment by floppyD** [comment]
I tried and no dice. All associating does is showing it under the "Open with" context menu. But anyway, I figured it out, all it's missing is a value under "HKLM\SOFTWARE\RegisteredApplications" called "mpv.net" pointing to "SOFTWARE\Clients\Media\mpv.net\Capabilities". Then it shows under Default Programs on Windows 7.

**Comment by stax76** [comment]
Thanks for pointing out, it should work in the next release.

**Comment by stax76** [comment]
New release is out.
