### ISSUE TITLE
Control MPV.NET via API?

### ISSUE THREAD

**Issue by mysteryx93** [stax76/mpv.net#59]
Is there any feature to control MPV.NET from another .NET application via an API (such as Named Pipes)?

Also I see that FSRCNN upscaling isn't available by default, which would be very useful
https://github.com/igv/FSRCNN-TensorFlow/releases

**Comment by stax76** [comment]
libmpv has built in json rpc using named pipes.

https://mpv.io/manual/master/#json-ipc

https://github.com/stax76/wox-mpv-plugin/blob/master/Main.cs

https://gist.github.com/rossy/3c414a2156f346781f6bd95d40012546

You can also implement any kind of remote mechanism yourself in a C# extension.

For scaling, you have to talk to the mpv people.
