### ISSUE TITLE
Can this software add multilingual support?

### ISSUE THREAD

**Issue by yangyzp** [stax76/mpv.net#61]
I am Chinese, I like this software very much, because I am not good at English, so I have some difficulties in using this software.

I hope this software can support multiple languages. Thank you.

**Comment by stax76** [comment]
I don't have plans to make it multilingual unless it gets requested frequently.

**Comment by bitsper2nd** [comment]
Not the ideal solution you are looking for, but there is another mpv [front-end](https://github.com/422658476/MPV-EASY-Player) made by a Chinese.
