### ISSUE TITLE
Crash on Stop

### ISSUE THREAD

**Issue by mysteryx93** [stax76/mpv.net#62]
In some cases when playback stops, MPV returns null instead of a boolean and it crashes at MpvPlayerHelper.YesNoToBool

You'd have to change it this way:

```
public static bool YesNoToBool(string yesNoString)
{
	switch (yesNoString)
	{
		case "yes":
			return true;
		case "no":
			return false;
		case null:
			return false;
	}
	throw new ArgumentException("Invalid string value for yes/no property.");
}
```

**Comment by stax76** [comment]
Wrong project again, see:

https://github.com/hudec117/Mpv.NET.lib
