### ISSUE TITLE
crash on playing certain videos

### ISSUE THREAD

**Issue by killoid** [stax76/mpv.net#63]
log from windows event viewer:
Faulting application name: mpvnet.exe, version: 5.0.0.0, time stamp: 0x5d3b9135
Faulting module name: igd10iumd64.dll, version: 20.19.15.4404, time stamp: 0x56d8f413
Exception code: 0xc0000005
Fault offset: 0x000000000001c6e8
Faulting process id: 0x1714
Faulting application start time: 0x01d54614bf2ce2b9
Faulting application path: C:\Program Files\mpv.net\mpvnet.exe
Faulting module path: C:\Windows\SYSTEM32\igd10iumd64.dll
Report Id: a62d00c5-fe0c-4a03-8cb4-2c32494fb168
Application: mpvnet.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FFB2CE3B5B5

a sample file link:
https://drive.google.com/file/d/1yWkeOmZNGmbkWYOisK0DOk1rLhYGc0vC/view?usp=sharing

the crash occurring is very random. sometimes toggling subtitles, fullscreen mode or something else. it happens either at start or suddenly in the middle of watching. i am using a laptop running windows 10 pro on core i5-5200u, intel hd graphics 5500 for video playback. graphics card driver is up-to-date.

**Comment by stax76** [comment]
I would guess it's the fault of the gpu driver, you can try if it's reproducible in mpv and if so report it to the mpv tracker.

**Comment by killoid** [comment]
i couldn't reproduce the issue on mpv. every video files as the sample plays fine on it.

**Comment by stax76** [comment]
With NVIDIA GPU it's stable.

Maybe it works with changed settings, for instance gpu-context = angle.

You can report it to the mpv tracker as libmpv bug though they will likely say that it's probably the driver or mpv.net or the OS, you can get a log file log-file = <path>

**Comment by killoid** [comment]
ok thanks for your reply. i will switch to nvidia gpu for now.

**Comment by stax76** [comment]
With this type of problem trying a different gpu-api can help. The default is auto which uses d3d11, other options are opengl and vulkan. vulkan will only work in the next release (higher than mpv.net 5.0).

**Comment by killoid** [comment]
haven't tried vulkan but switching to opengl indeed fixed the issue. thank you for your help. i will close the issue for now.
