### ISSUE TITLE
mpv.net is not responding with mpv config

### ISSUE THREAD

**Issue by blackarcher21** [stax76/mpv.net#64]
my config for mpv.net here, copied some parts from my mpv config (mpv 0.29.1)
https://pastebin.com/uwpz2k5R

not responding if I drop video as soon as window appear, or video starts but not responding once I seek.

mpv.net 5.0.0, Windows 10 64-bit

**Comment by stax76** [comment]
The problem might be gpu-api, are you sure it's a good idea to use this?

Win10 1903
NVIDIA GT 1030
i5-8400

**Comment by stax76** [comment]
I've updated the [Limitations page in the wiki](https://github.com/stax76/mpv.net/wiki/Limitations):

`gpu-api = vulkan` isn't supported, only d3d11 and opengl work.

I hope I can add support for it, probably not easy to do.

**Comment by blackarcher21** [comment]
I just found that audio filter option is where issue from, I deleted this line and mpv.net run fine . Could you check this with filter you know? I think no problem with gpu-api.

**Comment by stax76** [comment]
For me vulkan works only if I set start-threshold=0, this is a mpv.net setting so it must be located in mpvnet.conf and not in mpv.conf. It seems to be mostly stable but not 100%, so far I had one failure.

By default, mpv.net uses start-threshold=1500 which means it waits maximum 1500 milliseconds to get the video resolution from libmpv before it shows the main window, usually it takes 400-800 ms. If you set this to 0 then the main window will be shown instantly but with a default resolution depending on things like the autofit property.

It seems before vulkan is started a window must be present, d3d11 or opengl don't need it.

**Comment by blackarcher21** [comment]
Are you really going to remove vulkan option? Have you test audio filter? I wonder if the filters I use are broken and make mpv.net not responding somehow.

**Comment by stax76** [comment]
I made a request on the mpv tracker and decide after that what to do, probably I will have to implement a workaround. The audio filter worked for me but further tests are needed.

https://github.com/mpv-player/mpv/issues/6833

**Comment by stax76** [comment]
Next release:

- gpu-api vulkan was not working if media files were opened via
  command line (that included Explorer), Vulkan unlike d3d11 and opengl
  requires a window being visible, this is now satisfied with a
  workaround, it's only possible showing a window with default size
  first as defines by autofit. Vulkan has few issues, usually the auto option
  which uses d3d11 is better!

**Comment by stax76** [comment]
New release is out.
