### ISSUE TITLE
Persistent volume option

### ISSUE THREAD

**Issue by derude50** [stax76/mpv.net#65]
One important feature left to implement that most other media players have is persistent volume. This means that the current volume is saved when the program is closed and restored when the program again, no matter what file is being opened. Currently it only remembers the volume if it's the same file.

Current behavior: If I mute the audio, close the program, open a completely different file, then the audio is back to the default volume. Or if I set the audio to 20%, close the program, open a different file, then the audio is back to the default volume.

Expected behavior with a persistent volume option: If I mute a video, close the program, and open a completely different video, it should still be muted. Or if I set the volume to 20%, close the program, and open a different file, the volume should still be at 20%.

**Comment by stax76** [comment]
Thanks for the feedback. Very good description, I appreciate that! Chances are good for this.

**Comment by stax76** [comment]
It will be available in the next release, once released I'll close the issue.

**Comment by stax76** [comment]
New release is out.
