### ISSUE TITLE
Conflict with Symantec Endpoint Protection

### ISSUE THREAD

**Issue by RNiK** [stax76/mpv.net#66]
Just downloaded version 5 of the player on my PC (Microsoft Windows Version 10.0.16299.1087 + Symantec Endpoint Protection Version 14). 
I've tried with both portable version with the same result: mpvnet.exe is considered "Infected" (see image below).

![Symantec](https://user-images.githubusercontent.com/695453/62218389-a544b100-b3ac-11e9-8300-223a0de53382.png)

**Comment by stax76** [comment]
> WS.Reputation.1 is a detection for files that have a low reputation score based on analyzing data from Symantec’s community of users and therefore are likely to be security risks. Detections of this type are based on Symantec’s reputation-based security technology. Because this detection is based on a reputation score, it does not represent a specific class of threat like adware or spyware, but instead applies to all threat categories. 
> 
> The reputation-based system uses "the wisdom of crowds" (Symantec’s tens of millions of end users) connected to cloud-based intelligence to compute a reputation score for an application, and in the process identify malicious software in an entirely new way beyond traditional signatures and behavior-based detection techniques.

**Comment by bitsper2nd** [comment]
Here is my result from [Virus Total](https://www.virustotal.com/gui/file/9343dcd0b0dc90445ecfa5aa01f26bc6a4cef8479e003692d1c6b025c78794a6/detection). It is most likely a false positive from your end.

**Comment by RNiK** [comment]
> 
> 
> Here is my result from [Virus Total](https://www.virustotal.com/gui/file/9343dcd0b0dc90445ecfa5aa01f26bc6a4cef8479e003692d1c6b025c78794a6/detection). It is most likely a false positive from your end.

Yes, it is a false positive for sure, but it's not "on my end". It is for every Symantec Endpoint user.
I suggest you to contact them via [the apposite form](https://submit.symantec.com/false_positive/) in order to whitelist mpv.

**Comment by stax76** [comment]
> I suggest you to contact them via the apposite form in order to whitelist mpv.

I've submitted it.

**Comment by stax76** [comment]
> In relation to submission 162211.
> 
> Upon further analysis and investigation we have verified your submission and as such this detection will be removed from our products.
> 
> The updated detection will be distributed in the next set of virus definitions, available via LiveUpdate or from our website at https://www.symantec.com/security_response/definitions.jsp
