### ISSUE TITLE
canu u help me

### ISSUE THREAD

**Issue by arunpoornima** [stax76/mpv.net#67]
![Untitled](https://user-images.githubusercontent.com/38433143/62267312-92e46a80-b3e0-11e9-947e-035edbbe0823.png)

**Comment by stax76** [comment]
Use Visual Studio 2019.

**Comment by arunpoornima** [comment]
Thank U sir. I need your help to build a software, I'm a beginner in
programming.I request your help.

**Comment by stax76** [comment]
You'll have to install Visual Studio 2019.

**Comment by arunpoornima** [comment]
[image: image.png]


Now i am instaled visual studio 2019,But a error displayed when run the
project.

**Comment by stax76** [comment]
go to https://github.com/stax76/mpv.net

find the green button 'Clone or Download' select 'Download Zip'. Extract this either with Win 10 or 7zip, don't use another zip program, it might be broken.

Your last post don't contain any error.

**Comment by arunpoornima** [comment]
DllNotFoundException

Unable to load DLL 'mpv-1.dll': The specified module could not be found.
(Exception from HRESULT: 0x8007007E)

System.DllNotFoundException: Unable to load DLL 'mpv-1.dll': The specified
module could not be found. (Exception from HRESULT: 0x8007007E)
   at mpvnet.libmpv.mpv_observe_property(IntPtr mpvHandle, UInt64
reply_userdata, String name, mpv_format format)
   at mpvnet.mp.observe_property_bool(String name, Action`1 action)
   at mpvnet.MainForm..ctor()


[image: image.png]

**Comment by arunpoornima** [comment]
Problem solved dll file copy Bin folder

**Comment by arunpoornima** [comment]
[image: image.png]

I really liked your player,But what i need is a player like the one in this
image,Can you give me the code to make my player work from your project?.I
may not be able to find the code i want from your project because of my
lack of experience.Please help me.I'll donate a small amount for you before
my project ends.I'II try to do my project as best i can without disturbing
you.
I am from india and my full name is Arun.T If something goes wrong in my
English language please cooperate it.

**Comment by stax76** [comment]
> But what i need is a player like the one in this image

I don't see any image here.

**Comment by arunpoornima** [comment]
[image: image.png]

**Comment by stax76** [comment]
There is still no image visible here.

**Comment by arunpoornima** [comment]
i am send image now

**Comment by arunpoornima** [comment]
Can you see the image file?

**Comment by arunpoornima** [comment]
Can u help me? Can u see the image? Pls give me a answer

**Comment by arunpoornima** [comment]
What u mean Closed #67 <https://github.com/stax76/mpv.net/issues/67>.

**Comment by arunpoornima** [comment]
Any updates?

**Comment by stax76** [comment]
You probably don't have enough experience to build a player if you can't even post an image on the issue tracker. I might answer a simple question here and there but cannot give a full beginner programming course. It does not look like you have much patience but as a beginner you really need that. mpv both as player and as library is not designed for beginners, it's designed for nerds. Why do you need an own player, what's wrong with mpv.net? You understand that you can extend mpv.net with extensions? I was able to build this player because I had 15 years coding experience when I started it.

**Comment by arunpoornima** [comment]
The image tracker was not posted on the issue tracker beacuse of my low
internet speed.I don't need your programming class.mpv.net is ok I haven't
blamed your product.I have no intention of expanding your product.I have
not downplayed your 15 year experiance.


[image: image.png]

**Comment by arunpoornima** [comment]
The image tracker was not posted on the issue tracker beacuse of my low
internet speed.I don't need your programming class.mpv.net is ok I haven't
blamed your product.I have no intention of expanding your product.I have
not downplayed your 15 year experiance.

![image](https://user-images.githubusercontent.com/38433143/62443390-9abd4b00-b70f-11e9-8bba-5b160392f07a.png)

**Comment by arunpoornima** [comment]
I need your help to build a software.If you give me your email id,we can
discuss it more,We see this as a good business.

**Comment by arunpoornima** [comment]
Do I have to wait for you?Can you reply?

**Comment by stax76** [comment]
Sorry but I don't have enough time to help everybody with everything.

To play I think there are two ways.

1. setting property

mp.set_property_string("pause", "no");

https://mpv.io/manual/master/#options-pause

2. sending input command

mp.command("set pause no");

https://mpv.io/manual/master/#command-interface-set-%3Cname%3E-%3Cvalue%3E

If you are building a libmpv based player in C# then you are building a concurrent product, you already have all my code, why should I help a competitor even more, will your player be open source?

**Comment by arunpoornima** [comment]
Thank u so much for your reply.The links you have provided will surerly
help me.The mpv player would be very useful for me if you can tell me how
to add mpv player  up with my project.Hope you find it not difficult,I am a
beginner in programming,
Because of my less experiance please forgive me if i bother.How to add mpv
player in a new project.

NB: Regularly i will not trouble you
