### ISSUE TITLE
Single instance doesn't work

### ISSUE THREAD

**Issue by blackarcher21** [stax76/mpv.net#68]
mpv.net 5.1
I used to drag-n-drop to play video. now I try to associate my video with mpv.net, double-click it on explore, if window is open, player won't play the file.

**Comment by stax76** [comment]
Please use:

`Tools > OS Setup > Register Video...`

**Comment by blackarcher21** [comment]
I have registered file associations at the end of setup.
I just followed your instruction and still not working.

**Comment by stax76** [comment]
Then try:

`Tools > OS Setup > Manage Default Apps`

**Comment by blackarcher21** [comment]
I see, it failed because video files contain Korean characters.

**Comment by stax76** [comment]
Is it working now? Unicode is supposed to work.

**Comment by blackarcher21** [comment]
no, single instance doesn't work on file with CJK characters on filename here.

**Comment by stax76** [comment]
Please post the characters, I just tried unicode characters (Win+.) and it works.

**Comment by stax76** [comment]
Now I understand.

**Comment by stax76** [comment]
It will work in the next release, thanks for reporting.

**Comment by stax76** [comment]
I've uploaded a new build which fixes it.

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/f/s!ArwKS_ZUR01gySQIE1QCL2i9F_uR

**Comment by blackarcher21** [comment]
thanks, that fixes the issue :)
