### ISSUE TITLE
Syncplay Compatbility

### ISSUE THREAD

**Issue by fmohican** [stax76/mpv.net#69]
Hi Stax,

Can you add syncplay compatbility?
https://syncplay.pl/
https://github.com/Syncplay/syncplay

Also check https://github.com/Syncplay/syncplay/issues/246

**Comment by stax76** [comment]
Hi fmohican,

mpv.net should support all of mpv's streaming capabilities, if it works in mpv then it should also work in mpv.net (otherwise I have to examine it), if it's not working in mpv then you can request it on the mpv tracker.

**Comment by fmohican** [comment]
Syncplay ins't a file or container, syncplay its a 3rd party that synchronize "play" with other client eg:
client 1
client 2
client 3
want to play a movie, all 3 in same time, they open syncplay connect together, and syncplay "synchronize" media for all 3 client, MPV support that "application", please take a look at : https://github.com/Syncplay/syncplay/issues/246

**Comment by stax76** [comment]
It looks that syncplay passes --version, mpv.net has not an implementation for it.

**Comment by fmohican** [comment]
that is why I open issues there

**Comment by stax76** [comment]
Can you please test:

https://github.com/Syncplay/syncplay/issues/246#issuecomment-518436437

**Comment by fmohican** [comment]
It's work! Smooth!

**Comment by fmohican** [comment]
I forgot to confirm, all work veryfine!
