### ISSUE TITLE
small correction to the menu

### ISSUE THREAD

**Issue by 44vince44** [stax76/mpv.net#7]
Dear Stax, First thank you for the huge work done on right click menu. I was struggling to find the commands without success, and you gave them all.
Please correct this:
Shift+BS    set video-zoom 0 ; set video-pan-x 0 ; set video-pan-y 0 #menu: Alt+Backspace ; Pan && Scan > Reset
 
#menu says Alt+Backspace, it's Shift (silly bug;))

**Comment by stax76** [comment]
I've fixed it, thanks for reporting.

The work was derived from the mpv input.conf defaults found at:

https://github.com/mpv-player/mpv/blob/master/etc/input.conf

Adding those things I've also learned a lot I didn't know before and some commands found in the original mpv defaults were flawed and corrected in mpv.net, in the following commands the timeouts were missing

F8 show-text ${playlist}   **5000**
F9 show-text ${track-list} **5000**

which resulted in it was showed only less than a second, I've not reported this to their tracker.
