### ISSUE TITLE
When Title Bar (border) hide, the window can't scale.

### ISSUE THREAD

**Issue by wenmin92** [stax76/mpv.net#71]
The origin mpv support this.

**Comment by stax76** [comment]
It's kind of a problem because Windows don't seem to have this functionality built in, it requires a bunch of custom code it seems.

I'm a little bit proud that my main form is only 600 lines of code and adding 100 lines only for resizing would ruin that. I have to think about this.

**Comment by HubKing** [comment]
I came here for asking the same thing. PotPlayer can resize the window when it has no window chrome, but as you have said, it may require a lot of code to communicate with the Windows GUI system. If that is a lot of code, how about some keyboard shortcut or mouse gestures for doing the same thing? Right mouse button down + mouse wheel could be used to scale the window. I am tired of placing the mouse pointer to the thin window border region, anyway.

**Comment by stax76** [comment]
Sounds good, I'll investigate it, thanks for the feedback.

**Comment by stax76** [comment]
Please try this beta version:

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/f/s!ArwKS_ZUR01gySQIE1QCL2i9F_uR

**Comment by wenmin92** [comment]
I don't know if I was wrong or missed something, the window still can't scale using mouse to drag, but the right context menu has an addition menu (Window Size).

Now I can scale by <kbd>Alt</kbd>+<kbd>+</kbd> / <kbd>-</kbd>, which is a bit handy.
But there are some which not handy:
- The <kbd>+</kbd> / <kbd>-</kbd> keys only work in number region on keyboard?
- I can only scale a limit number of factors?
- When scale, a tip show would be better.
- I still want to scale by mouse drag.


Thanks for your hard work!

**Comment by stax76** [comment]
> The + / - keys only work in number region on keyboard?

Here it works on both keypad and normal +/-.

> I can only scale a limit number of factors?
> When scale, a tip show would be better.

You can remove no-osd in input.conf, it will always show 0.8 or 1.2 though because of the way I implemented this. The current size is always multiplied with 0.8 or 1.2 and after that mpv.net sets the window-scale to 1.0 without changing the size. It works as long as you stay within autofit-smaller and autofit-larger (mpv.net only supports integer values for that) bounds and within screen bounds.

> I still want to scale by mouse drag.

Maybe if more people request it. I don't like spending much time and add awful a lot of code for a very little feature.

**Comment by jamen** [comment]
For what its worth, the first day I started using mpv.net, I subscribed to this issue.

**Comment by stax76** [comment]
I'm still reluctant but I re-open the issue in case more people want to add +1.

**Comment by jamen** [comment]
Might be obvious, but to explain, I use borderless + always on top, to get:

![image](https://user-images.githubusercontent.com/6251703/67152497-c70b5100-f294-11e9-995e-0c4d0b930ded.png)

And my only grudge was I can't resize it without reenabling the borders each time. But otherwise, its a great little player for the corner of the screen.

**Comment by HubKing** [comment]
I could not find any new resizing feature in the beta version above, so I tried to do it myself. It was not difficult. I only added the following lines to the `MainForm.cs`, and now I can resize the borderless window by scrolling the wheel while holding down the right button. One problem is that if the size gets too small and the mouse pointer is no longer above the window, it does not get the wheel, and for that I may have to capture the mouse...

        bool IsHoldingRDown = false;

        protected override void OnMouseDown(MouseEventArgs e)
        {
            ...
            if(e.Button == MouseButtons.Right)
            {
                IsHoldingRDown = true;
            }
        }

        bool WheelResizeUsed = false;
        
        protected override void OnMouseWheel(MouseEventArgs e)
        {
            base.OnMouseWheel(e);
            if (IsHoldingRDown)
            {
                int newWidth = this.Width + (int)(e.Delta * 0.4);
                double ratio = (double)newWidth / (double)this.Width;
                int newHeight = (int)(this.Height * ratio);
                this.Size = new Size(newWidth, newHeight);
                WheelResizeUsed = true;
            }
        }

        protected override void WndProc(ref Message m)
        {
            switch (m.Msg)
            {
                case 0x020A: // WM_MOUSEWHEEL
                    if(IsHoldingRDown)
                    {
                        break;
                    }
                    else
                    {
                        goto case 0x0201;
                    }
                case 0x0205: // WM_LBUTTONUP
                    IsHoldingRDown = false;
                    if(WheelResizeUsed)
                    {
                        WheelResizeUsed = false;
                        return;
                    }
                    else
                    {
                        goto case 0x0201;
                    }
                case 0x0201: // WM_LBUTTONDOWN
               ....

**Comment by stax76** [comment]
input.conf is only generated when it's missing.

https://github.com/stax76/mpv.net/blob/master/mpv.net/Resources/inputConf.txt#L137
