### ISSUE TITLE
Error: MPV_ERROR_PROPERTY_NOT_FOUND

### ISSUE THREAD

**Issue by Harze2k** [stax76/mpv.net#72]
Hi! I get this error every time i start a movie, i click OK on the dialog and the movie starts. Is there anything I can do to fix it?

-Cheers

Exception

: MPV_ERROR_PROPERTY_NOT_FOUND

System.Exception: : MPV_ERROR_PROPERTY_NOT_FOUND
   at mpvnet.mp.set_property_string(String name, String value, Boolean throwOnException) in D:\Projekte\CS\mpv.net\mpv.net\mpv\mp.cs:line 479
   at mpvnet.mp.ProcessCommandLine() in D:\Projekte\CS\mpv.net\mpv.net\mpv\mp.cs:line 601

[mpv.log](https://github.com/stax76/mpv.net/files/3469040/mpv.log)

[mpv.txt](https://github.com/stax76/mpv.net/files/3469041/mpv.txt)
![image](https://user-images.githubusercontent.com/53750202/62489463-18905d80-b7c7-11e9-89fc-a81171866d99.png)

**Comment by stax76** [comment]
It's receiving an empty string or a space character as command line argument. I tried to reproduce it using the same startup path and same media file path. Since I cannot reproduce it I can only guess what went wrong, I guess the file association registration went wrong. How did you register the file associations? You can try to register again using the menu:

Tools > OS Setup > Register Video...

**Comment by stax76** [comment]
Also please check if it's really a x64 app, your startup path:

C:\Program Files **(x86)**\SVP 4\mpv64

**Comment by stax76** [comment]
Please post the exact download link from where you downloaded mpv.net

**Comment by stax76** [comment]
It's probably an invalid command line and mpv.net probably did not create this invalid command line. I would guess something like `--  fullscreen` instead of `--fullscreen`.

**Comment by Harze2k** [comment]
Hi! This is the link for mpv.net i used: https://github.com/stax76/mpv.net/releases/download/5.1/mpv.net-portable-x64-5.1.0.0.zip

The file associations was done with the mpv-install.bat file. I followed this guide: https://www.reddit.com/r/mpv/comments/buhyxb/tutorial_smoothvideo_project_svp_for_mpvnet/ so the mpv-install.bat file that was used was this: https://codeload.github.com/rossy/mpv-install/zip/master (I did one change in the bat file, using mpvnet.exe instead of mpv.exe as you can se was recommended in the reddit post).

Hope that helps you :)

**Comment by Harze2k** [comment]
I tried to register the file associations again using the GUI but no luck.

**Comment by blackarcher21** [comment]
try remove opengl-backend=angle

**Comment by Harze2k** [comment]
Will test when am back home, hope it helps :) For some reason i never get that error when opening a video via teamviewer to my home htpc 😖

**Comment by stax76** [comment]
You can change file associations with the 'Open with' feature of Windows file explorer.

**Comment by Harze2k** [comment]
Yeah i tried that yesterday, and pointed to mpvnet.exe but still got the same error. But ill let you know when i tested the "try remove opengl-backend=angle"

**Comment by stax76** [comment]
I don't think something like angle is causing this. It's likely the file associations stored in the registry.

**Comment by Harze2k** [comment]
You where right, got it to work :)

Working when i double klick a movie: "C:\Program Files (x86)\SVP 4\mpv64\mpvnet.exe" "%1

Dint work (default after installation, for me atleast): 
"C:\Program Files (x86)\SVP 4\mpv64\mpvnet.exe" --"%L
