### ISSUE TITLE
Excessive memory usage when opening files.

### ISSUE THREAD

**Issue by Vernetzt** [stax76/mpv.net#73]
### **Issue**
Memory usage skyrockets when using "Open With" or having set mpv.net as the default player for files but only when mpv.net isn't already open.

Win 8.1
mpv.net 5.2 (and 5.1)

### **Notes:**

- Resizing, entering fullscreen, enabling/disabling border, and even showing video stats or playlist will free the excessive memory. (See screenshot)
- Opening a file with mpv.net already open does not seem to have this issue.
- Opening a file with mpv (not .net) does not cause this issue.
- Memory usage depends of size of file opened.

This is with a 150MB MKV file. Opening larger files will use over 10GB+ of my available ram.
**https://i.imgur.com/efULvGz.png**

### **Steps to reproduce:**
1. Make sure mpv.net isn't running.
2. Open with or set mpv.net as default for a file.
3. Open file with mpv.net without mpv.net already running.

**Comment by 44vince44** [comment]
Vernetzt, I tried to reproduce that, but i couldn't. my mpv is always using around 230k only with FHD files... Please post your config files so i can test with them !

**Comment by Vernetzt** [comment]
When troubleshooting my config defaulted to my normal mpv's one so I was chasing a ghost apparently.

**osd-scale-by-window = no**

Adding this to a newly generated config seems to be what is causing this issue for me.
Same steps to reproduce.

**Comment by 44vince44** [comment]
I confirm the following behavior:
when    "start-threshold" is set to default (1500) and the line "osd-scale-by-window = no" is present, then the bug described by Vernetzt occurs.
If "start-threshold" is set to 0, and the line "osd-scale-by-window = no" is present, then there is no bug.
So there might be something with start-threshold ?

**Comment by stax76** [comment]
Just moving and simplifying some code had fixed it apparently.

Thanks for testing!

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/f/s!ArwKS_ZUR01gySQIE1QCL2i9F_uR

**Comment by 44vince44** [comment]
So far so good :-) nothing to report ! Thank you Stax!

**Comment by Vernetzt** [comment]
Seems fine so far on newer releases. Thanks.
