### ISSUE TITLE
Enhancement: Shift + Drag

### ISSUE THREAD

**Issue by Vernetzt** [stax76/mpv.net#77]
Drag and drop feature request I guess?

**Shift + Dragging** files or links onto a mpv window will appended them to a playlist or create one.

Any chance at implementing something similar? Probably not something commonly used but can be nice to build up a quick queue of sorts.

**Comment by stax76** [comment]
It's already implemented but using Ctrl.

**Comment by Vernetzt** [comment]
Guess I was wrong when I thought I tried Ctrl. Thanks for the quick response.
