### ISSUE TITLE
disable history/recent list tracking?

### ISSUE THREAD

**Issue by loopedice** [stax76/mpv.net#78]
So I use a shared computer and would rather not have my play history be visible. Is this something that can be disabled maybe via a config?

**Comment by stax76** [comment]
For history to be disabled you can delete the history.txt file.

For Recent to be disabled you can remove the menu item from input.conf, you can remove the history menu item as well.

mpv.net will still write recent files to the registry, to prevent this there will be a config setting recent-count in the next release, set this to 0.

**Comment by adasqg** [comment]
> For history to be disabled you can delete the history.txt file.
> 
> For Recent to be disabled you can remove the menu item from input.conf, you can remove the history menu item as well.
> 
> mpv.net will still write recent files to the registry, to prevent this there will be a config setting recent-count in the next release, set this to 0.

Hi, I want to ask how to remove the menu item
