### ISSUE TITLE
mpv_thumbnail_script will not work with mpv.net

### ISSUE THREAD

**Issue by Naomi010Sentzke** [stax76/mpv.net#79]
https://github.com/TheAMM/mpv_thumbnail_script

**Comment by stax76** [comment]
osc=yes was enforced, next build allows to disable it in mpv.conf, first test shows that mpv_thumbnail_script is working fine. Thanks for the feedback. I still try not to write much code, so I cannot tell you when it will be released.

**Comment by stax76** [comment]
I just reverted the code because I think it should work already, here it does.
