### ISSUE TITLE
Can't get the multimedia keys to work... any clue?

### ISSUE THREAD

**Issue by 44vince44** [stax76/mpv.net#8]
Dear Stax, Sorry for the multiple threads, but every one is a different subject.

I could not get any multimedia keys to work (they work with WMP, Foobar2000 but not mpv).

These lines that you put in the input.conf don't work for me:
 PLAY cycle pause
 PAUSE cycle pause
 PLAYPAUSE cycle pause
 STOP quit
 FORWARD seek 60
 REWIND seek -60

**Comment by stax76** [comment]
I don't have any device sending these so I can't test it, if it's not mpv.net specific but happens also in mpv you can report it at their tracker at:

https://github.com/mpv-player/mpv/issues

**Comment by 44vince44** [comment]
Ok I'll report it right now!!

**Comment by 44vince44** [comment]
Stax, the multimedia keys are working in the last build of mpv by shinchiro (git) https://sourceforge.net/projects/mpv-player-windows/files/64bit/
(file mpv-x86_64-20190316-git-dd83b66.7z)
I just downloaded it (after asking in the mpv-player forum) and it turned out that last version and build takes the multimedia keys!

**Comment by stax76** [comment]
libmpv is updated in version 1.4

**Comment by 44vince44** [comment]
Thanks Stax, I am testing and it still doesn't work. it won't take the multimedia keys...

**Comment by 44vince44** [comment]
The docs say: --input-media-keys=<yes|no>
    (OS X and Windows only) Enable/disable media keys support. Enabled by default (except for libmpv).
So it seems that libmpv is slightly different than the builds with no libmpv? could it mean something

**Comment by stax76** [comment]
does it work when you add input-media-keys=yes to the mpv conf, I found and fixed two input related problems available in the next release, Alt key not working and appcommand input not working

https://docs.microsoft.com/en-us/windows/desktop/inputdev/wm-appcommand

**Comment by stax76** [comment]
I hope it's fine in version 1.5

**Comment by 44vince44** [comment]
Thanks for the latest build Stax. Indeed the multimedia keys are sensed now, but after pressing any of them, mpvnet crashes!

With the command "mpvnet.exe --input-test --force-window --idle" i checked that the key is sensed correctly. Example: multimedia playpause gives: 
Key PLAYPAUSE is bound to:
1. 'Cycle pause' in <builtin>:1 (default)
and then after 4 or 5 seconds mpvnet crashes.
I tested with and without "input-media-keys=yes", it crashes

Of course, all normal keys work fine, no crash.

**Comment by stax76** [comment]
I could reproduce it by installing a virtual keyboard that is capable of sending WM_APPCOMMAND, I couldn't understand it but I found out how to make it work, it should be fine in the next release.

**Comment by 44vince44** [comment]
Anything you want me to test, I'm here!

**Comment by stax76** [comment]
I hope it's fixed in 1.6 which I just uploaded.

**Comment by 44vince44** [comment]
Yes it is fixed indeed. Thank you!!
playpause, prev, next are the keys on my keyboard and they all work fine, no crash.
