### ISSUE TITLE
Can't hear audio in any video [5.3]

### ISSUE THREAD

**Issue by azmodai** [stax76/mpv.net#80]
So yeah, nothing is coming through my speakers. Every other player works (vlc, mpc-hc) fine, Winamp works fine, browser etc. 

It detects the audio track no problems, but the speaker icon has a "X" in the player's taskbar. Pressing "m" to mute or unmute does not do anything.

**Comment by stax76** [comment]
Maybe the volume default to zere, please try plus on the keypad to increase the volume.

**Comment by azmodai** [comment]
> 
> 
> Maybe the volume default is set to zero, please try plus on the keypad to increase the volume.

That was it, works well now. Stupid user errors..
