### ISSUE TITLE
mpv.net can't open files with long file path name.

### ISSUE THREAD

**Issue by Naomi010Sentzke** [stax76/mpv.net#83]
Say, something like "D:\Videos\[ANK-Raws] Baka to Test to Shoukanjuu Ni! (BDrip 1920x1080 x264 FLAC AC3 Hi10P)\[ANK-Raws] Baka to Test to Shoukanjuu Ni! - Vol.1 (BDrip 1920x1080 x264 FLAC AC3 Hi10P)\[ANK-Raws] Baka to Test to Shoukanjuu Ni! - 01 (BDrip 1920x1080 x264 FLAC AC3 Hi10P).mkv" can be opened by mpv or PotPlayer, but not mpv.net.

**Comment by stax76** [comment]
I cannot reproduce this on Win 10 1903, it works here regardless of if the system has long path support enabled or not.

**Comment by Naomi010Sentzke** [comment]
It seems like Windows by default does not allow long file name paths, you must have enabled it in regedit or gpedit sometime. mpv can bypass it(but wont properly display file title), but mpv.net cant.
[Allow use of long file name paths.zip](https://github.com/stax76/mpv.net/files/3525095/Allow.use.of.long.file.name.paths.zip)
Regardless it can be enabled in the registry(I have included the edit).

**Comment by stax76** [comment]
Which OS version are you using?

**Comment by Naomi010Sentzke** [comment]
Windows 10 1903. Maybe its because I am using the portable version. In mpv even though it is portable it can open long file names without changing the registry(and so can PotPlayer). Its the same with the Blackbox script, unlike mpv, mpv.net does not have full access to file manager(but if you open the video from a torrent client, it has the access), this one I actually tested in another PC. I only use the portable version, so cant talk about installed version.
Although, the former can easily be solved with a registry edit.

**Comment by Naomi010Sentzke** [comment]
It seems like Github formatting didnt properly display the file path D:\Videos->ANK-Raws] Baka to Test to Shoukanjuu Ni! (BDrip 1920x1080 x264 FLAC AC3 Hi10P)->[ANK-Raws] Baka to Test to Shoukanjuu Ni! - Vol.1 (BDrip 1920x1080 x264 FLAC AC3 Hi10P)->ANK-Raws] Baka to Test to Shoukanjuu Ni! - 01 (BDrip 1920x1080 x264 FLAC AC3 Hi10P).mkv. Replace all '->' with '\'

**Comment by stax76** [comment]
This will work in the next release!

**Comment by TimDrayk** [comment]
Hey! You can use LongPathTool for deleting long path files.
