### ISSUE TITLE
mpv maximize script does not work properly with mpv.net

### ISSUE THREAD

**Issue by Naomi010Sentzke** [stax76/mpv.net#84]
The mpv script to maximize Windows on startup does not properly work with mpv.net.
https://github.com/kevinlekiller/mpv_scripts/tree/master/maximize/
Sometimes it does, sometimes it does not.

**Comment by Naomi010Sentzke** [comment]
Never mind. You have to set `start-threshold = 0` in mpvnet.conf.

**Comment by stax76** [comment]
next release has: added new setting to start with maximized window
