### ISSUE TITLE
history.txt comes back after deletion 

### ISSUE THREAD

**Issue by ll811** [stax76/mpv.net#87]
I've seen users be told to just delete this text document if they don't want their history logged, but this does not work. It'll work for a brief time, not sure how long it is but eventually history.txt will once again be created and start logging your files and it doesn't even ask you. I don't know if it is tied to how many minutes you spend with mpv open playing a file, or if it just creates itself after playing a few of them but it does come back.

**Comment by stax76** [comment]
Code inspection shows that you are right, I'll fix it.
