### ISSUE TITLE
Cant use Ekisu's webm script.

### ISSUE THREAD

**Issue by Naomi010Sentzke** [stax76/mpv.net#88]
https://github.com/ekisu/mpv-webm
It works fine mpv, but on mpv.net it gives ""Encode Failed! Check log for details"
I have included the log file.
But I guess this is the highlight

> [  20.671][i][webm] Encoding to E:\Anime\Hunter x Hunter\Hunter x Hunter Greed Island OVA (2003)\Hunter x Hunter 71 (Greed Island OVA)-[20.54.503-21.32.917].webm 
> [  20.671][v][webm] Command line: mpv E:\Anime\Hunter x Hunter\Hunter x Hunter Greed Island OVA (2003)\Hunter x Hunter 71 (Greed Island OVA).mkv --start=0:20:54.503 --end=0:21:32.917 --ovc=libvpx --oac=libvorbis --loop-file=no --vid=1 --sid=1 --aid=no --sub-ass-override=yes --sub-auto=fuzzy --sub-delay=0.000000 --video-rotate=0 --ovcopts-add=threads=4 --ovcopts-add=b=520k --ovcopts-add=crf=10 -o=E:\Anime\Hunter x Hunter\Hunter x Hunter Greed Island OVA (2003)\Hunter x Hunter 71 (Greed Island OVA)-[20.54.503-21.32.917].webm 
> [  20.671][d][cplayer] Run command: show-text, flags=64, args=[Started encode..., 5000, 0]
> [  20.671][d][cplayer] Run command: subprocess, flags=64, args=[mpv,E:\Anime\Hunter x Hunter\Hunter x Hunter Greed Island OVA (2003)\Hunter x Hunter 71 (Greed Island OVA).mkv,--start=0:20:54.503,--end=0:21:32.917,--ovc=libvpx,--oac=libvorbis,--loop-file=no,--vid=1,--sid=1,--aid=no,--sub-ass-override=yes,--sub-auto=fuzzy,--sub-delay=0.000000,--video-rotate=0,--ovcopts-add=threads=4,--ovcopts-add=b=520k,--ovcopts-add=crf=10,-o=E:\Anime\Hunter x Hunter\Hunter x Hunter Greed Island OVA (2003)\Hunter x Hunter 71 (Greed Island OVA)-[20.54.503-21.32.917].webm, no, 67108864, yes, no]
> [  20.672][v][webm] Command failed! Reason:  init  Killed by us?  no 
> [  20.672][v][webm] Command stdout:  
> [  20.672][v][webm]  
> [  20.672][d][cplayer] Run command: show-text, flags=64, args=[Encode failed! Check the logs for details., 5000, 0]

[log.txt](https://github.com/stax76/mpv.net/files/3569156/log.txt)

**Comment by Restia666Ashdoll** [comment]
Use this
https://github.com/occivink/mpv-scripts
That script is too limited. This one lets you use ffmpeg commands.
