### ISSUE TITLE
MBTN_LEFT not working for Play/Pause function

### ISSUE THREAD

**Issue by derude50** [stax76/mpv.net#89]
Current behavior: Setting Mouse button left to the 'cycle pause' function in the Input Editor does nothing. The space bar still works when set to this function, but even manually trying to set MBTN_LEFT to another cycle pause function or play function does not work.

Expected behavior: Left clicking once on the video area of the program should pause the video. Left clicking once on the video area again should play the video. Etc.

Other info: This was working perfectly up until 5.1 or a version near there. The latest version is not the one that broke this functionality. The left mouse button is being recognized to set the commands in the Input Editor, but the commands will not launch from the left mouse button.

**Comment by stax76** [comment]
I think it still works but the problem is the defaults, take a look at line 200:

https://github.com/stax76/mpv.net/blob/master/mpv.net/Resources/inputConf.txt#L200

Unfortunately I don't remember why it was changed. Maybe it was just stupid or maybe it had a good reason, I don't remember it. :(

**Comment by stax76** [comment]
Let me guess, it was probably stupid. I've removed it now.

**Comment by stax76** [comment]
I remember now why I had added this line, because when a terminal is attached for every click it will print: [input] No key binding found for key 'MBTN_LEFT'.

**Comment by rokweom** [comment]
For those looking for a solution, since @stax76's link isn't working anymore, the problem is the `MBTN_Left     ignore` line.
