### ISSUE TITLE
Issue with the fix: a thread synchonisation bug which caused the shutdown to be delayed

### ISSUE THREAD

**Issue by 44vince44** [stax76/mpv.net#9]
The fix introduced in v1.2.0.0 actually makes quitting mpv long.
I still have the same long quit delay (freeze for seconds) in v1.3.0.0.
In 1.1.0.0 and before I didn't have this delay !
Strange?

**Comment by stax76** [comment]
I'll upload a new build later today, it should be fine then.

**Comment by stax76** [comment]
The new release is online now.

**Comment by 44vince44** [comment]
Thanks for the release !! Downloading and testing, and write down the results tomorrow
