### ISSUE TITLE
chromecast

### ISSUE THREAD

**Issue by j-mas** [stax76/mpv.net#97]
Hello Stax,
could you add the possibility to play videos via chromecast on TV?!

This would be very nice!!!

j-mas

**Comment by stax76** [comment]
I don't know how to do it, does mpv support it?

**Comment by Restia666Ashdoll** [comment]
I would take Xinput over Chromecast any day. Regarding I think it's possible in mpv, so probably doable in mpv.net
https://github.com/celluloid-player/celluloid/issues/307
