### ISSUE TITLE
Config Editor formatting

### ISSUE THREAD

**Issue by Naomi010Sentzke** [stax76/mpv.net#99]
There are many issues with the way config editor formats the conf files
1. It ignores and removes profiles. Say, if I make a profile for jpeg images in mpv.conf, it will remove the profile tags and apply the profile settings to everything. Infact it pretty much ignores every profile tags. Those profile specific settings are supposed to apply only to that specific profile.
2. It removes comments. For example I have this in mpv.conf
```
#Audio delay
#Useful if you're watching with your headphones on PC, but output the video on your Television with a long HDMI cable (counter the delay)
#audio-delay=+0.084
```
If I edit anything in the Config Editor, the next time it will remove this comment.
3. It removes spaces. Spaces are there to group my configs.

[mpv.conf.zip](https://github.com/stax76/mpv.net/files/3640867/mpv.conf.zip)

**Comment by stax76** [comment]
I think about it, problem is that it's not easy to implement, takes many hours and requires complex code.

**Comment by Naomi010Sentzke** [comment]
Thanks for clarification.

**Comment by stax76** [comment]
Please try this beta version:

https://www.dropbox.com/sh/4ctl2y928xkak4f/AAADEZj_hFpGQaNOdd3yqcAHa?dl=0

https://1drv.ms/f/s!ArwKS_ZUR01gySQIE1QCL2i9F_uR

**Comment by Restia666Ashdoll** [comment]
Just tested it. Now, I can edit from the config editor without the fear of formatting.
